### ISSUE TITLE
ERROR Protocol not available (errno=92) SO_REUSEPORT failed. - Socket.cc:112

### ISSUE THREAD

**Issue by xzh0662** [chenshuo/muduo#107]
代码：
#include <muduo/net/EventLoop.h>
#include <muduo/net/TcpServer.h>

int main()
{

	muduo::net::EventLoop loop;
	muduo::net::InetAddress listenAddr(2007);

	muduo::net::TcpServer server(&loop, listenAddr, "test");

	return 0;
}

运行报错ERROR Protocol not available (errno=92) SO_REUSEPORT failed. - Socket.cc:112。

内核版本：
root@localhost ~]# uname -a
Linux localhost.localdomain 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ellusak** [comment]
I got same error:
CentOS 6.5
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)

In my environment, SO_REUSEPORT is defined, but setsockopt() always return "Protocol not available".

http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t
```````````
Prior to Linux 3.9, only the option SO_REUSEADDR existed.
```````````
