### ISSUE TITLE
在Singleton类中的init函数中的::atexit(destroy)如果调用失败呢？

### ISSUE THREAD

**Issue by demiaowu** [chenshuo/muduo#108]
在Singleton类中的init函数中的::atexit(destroy)如果调用失败呢？那么资源就可能出现泄漏了。我觉得如果使用一个内部的Gc类来实现回收资源可能更加的好~

**Comment by guochy2012** [comment]
atexit是在进程结束的时候调用。即使调用失败也无所谓的。

**Comment by demiaowu** [comment]
atexit是在init函数调用，怎么是在进程结束的时候调用呢？

**Comment by guochy2012** [comment]
口误，atexit是向系统注册一些函数，这些函数在进程结束的时候被调用。
其实单例模式不需要析构对象，因为这个对象本来就是要伴随整个进程周期。这不算资源泄露。

**Comment by demiaowu** [comment]
如果程序中打开了一些文件描述符之类的呢？不手动close能回收？

**Comment by guochy2012** [comment]
进程结束了，fd自然就会回收。如果是在单例对象中打开的，那么一般在运行期间不需要关闭，等到进程结束关闭，完全符合逻辑

**Comment by gfreewind** [comment]
进程级别的资源都没有问题，系统会在进程结束时候全部释放掉。但是系统级别的资源就麻烦了，比如信号量什么的——当然信号量可以通过undo来解决。

**Comment by demiaowu** [comment]
也许在析构函数可能有一些其他操作必须完成，比如自定义缓冲区刷新等！

**Comment by chenshuo** [comment]
如果你担心 ::atexit 失败的话，那给它加上 assert 好了。

**Comment by demiaowu** [comment]
assert()有助于我们发现问题出在什么地方？但是并不能帮助我们解决这个问题。我觉得加一个内部的Gc（garbage collection），一个静态的Gc对象，static Gc：：gc;这样这个Gc对象的内存回收由系统负责，这样我们在其析构函数中delete我们的Singleton对象，至少可以避免上面这种异常情况。

**Comment by chenshuo** [comment]
我认为功能上没区别，除非你能复现出 atexit 出错而你的方法能正常工作的场景。要不你先提个 pull request 来看看 static Gc::gc 到底长什么样？

**Comment by demiaowu** [comment]
see Add a Gc class to insure the Singleton's destructor invocation #109

**Comment by demiaowu** [comment]
1，系统级别的保证gc析构函数的调用本身是可信任，atexit()可能会出现异常，当然举一个极端的例子：一个大型的项目调用atexit()注册函数的开发人员很多， 我不能保证32一定够用，很有可能在你注册的时候已经超出了32个的大限，我们destory（）谁来调用。（当然这个例子很极端，我们可以通过规范和其他的手段来保证它不会超过32）但是这种规范和审查的保证肯定没有系统级别的保证可靠。

2，假如说atexit()失败了，assert()会打印出出错信息然后退出。但是我们destroy（）并没有被调用。assert（）只是让我们发现这个问题，但没有解决这个问题。

假设我们有一个日志类，为了提高效率，我自定义了一个缓冲区。那么，我们肯定希望我们缓冲区的日志最终在程序退出的时候能被刷新到磁盘中(这个刷新的操作我们放在日志类的析构函数中是一个不错的选择)。在使用atexit()至少会出现帅新缓冲区失败的情况，但是系统级别在可预见的范围之内没有这种情况出现。（当然程序因为其他的原因异常退出，这两种方法都没法很好处理）

**Comment by chenshuo** [comment]
Closed as per #109 .
