### ISSUE TITLE
I7的CPU(PC)编译的muduo程序，在E5(服务器)系列上运行发生SIGILL

### ISSUE THREAD

**Issue by lf723** [chenshuo/muduo#111]
#include <stdio.h>
	#include <unistd.h>
	#include <muduo/base/Types.h>
	#include <muduo/base/Logging.h>
	#include <boost/algorithm/string.hpp>
	#include <muduo/net/TcpServer.h>
	#include <muduo/net/EventLoop.h>
	#include <muduo/net/InetAddress.h>
	#include <muduo/net/Buffer.h>
	#include <muduo/base/Timestamp.h>
	#include <vector>
	using namespace std;
	using namespace muduo;
	using namespace muduo::net;
	#include <boost/bind.hpp>
	using namespace boost::algorithm;

	#include <stdio.h>
	#include <time.h>
	#include <errno.h>

	class Svr
	{
		public:
			Svr(EventLoop* loop,InetAddress& addr);
			void Start();
			void Stop();
			void LogicLoop();
			void OnConnected(const TcpConnectionPtr& conn);
			void OnMessage(const TcpConnectionPtr& conn,Buffer* msg,Timestamp ts);
		private:
			TcpServer svr_;
	};

	Svr::Svr(EventLoop* loop,InetAddress& addr): svr_(loop,addr,"svr"){}

	void Svr::Start()
	{
		svr_.setConnectionCallback(boost::bind(&Svr::OnConnected,this,_1));
		svr_.setMessageCallback(boost::bind(&Svr::OnMessage,this,_1,_2,_3));
		svr_.start();
		svr_.getLoop()->runEvery(0.01f,boost::bind(&Svr::LogicLoop,this));
		
		svr_.getLoop()->loop();
	}

	void Svr::Stop()
	{
		svr_.getLoop()->quit();
	}

	void Svr::LogicLoop()
	{
		static int i;
		printf("loop...%d\n",++i);
	}

	void Svr::OnConnected(const TcpConnectionPtr& conn)
	{
		printf("Connected\n");
	}

	void Svr::OnMessage(const TcpConnectionPtr& conn,Buffer* msg,Timestamp ts)
	{
		printf("recv\n");
	}

	int main(int argc, char* argv[])
	{
		EventLoop loop;
		InetAddress saport(8000);
		Svr saac(&loop,saport);
		saac.Start();
		return 0;
	}

SIGILL发生处:
    Program received signal SIGILL, Illegal instruction.
0x00000000004037f8 in SaacSvr::Start() ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6_5.2.x86_64 libgcc-4.4.7-11.el6.x86_64 libstdc++-4.4.7-11.el6.x86_64
(gdb) 
(gdb) 
(gdb) 
(gdb) where
#0  0x00000000004037f8 in SaacSvr::Start() ()
#1  0x0000000000403990 in main ()
(gdb) 

1、E5系列的服务器编译的demo在I7的PC上运行正常
2、I7的PC上编译的demo放在E5上则发生SIGILL
3、2个系统均为centos6.5 x86_64
4、g++版本为
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

**Comment by chenshuo** [comment]
把 https://github.com/chenshuo/muduo/blob/master/CMakeLists.txt#L27 改成适合你们系统的值。

**Comment by lf723** [comment]
thanks，初始指定的-march=native

**Comment by lf723** [comment]
thanks，初始指定的-march=native
