### ISSUE TITLE
Connector.cc 中断言有误

### ISSUE THREAD

**Issue by txsniper** [chenshuo/muduo#119]
void Connector::connecting(int sockfd)
{
  setState(kConnecting);
  assert(!channel_);
  channel_.reset(new Channel(loop_, sockfd));
  channel_->setWriteCallback(
      boost::bind(&Connector::handleWrite, this)); // FIXME: unsafe
  channel_->setErrorCallback(
      boost::bind(&Connector::handleError, this)); // FIXME: unsafe

  // channel_->tie(shared_from_this()); is not working,
  // as channel_ is not managed by shared_ptr
  channel_->enableWriting();
}

assert(!channel_) 应该是 assert(channel_ != NULL) 或 assert(channel_)吧？

**Comment by chenshuo** [comment]
你提这个 issue 之前测试过吗？

**Comment by txsniper** [comment]
这里是我搞错了。这个函数的想法是在connecting的时候，channel_应该为空，创建一个新的channel_并设定事件处理函数开始工作。
