### ISSUE TITLE
Socket are not closing properly

### ISSUE THREAD

**Issue by MichalKruszewicz** [chenshuo/muduo#128]
I am have some sever based on muduo and after some time i get:

20150301 19:25:40.340338Z  8594 ERROR Too many open files (errno=24) in Acceptor::handleRead - Acceptor.cc:77
20150301 19:25:40.340362Z  8594 ERROR Too many open files (errno=24) in Socket::accept - SocketOps.cc:123

And the server dont accept more incoming connections (on error there was only 8 connected clients)

**Comment by chenshuo** [comment]
Steps to reproduce?

**Comment by MichalKruszewicz** [comment]
I have a list of structures. 
class conn_data
{
        muduo::net::TcpConnectionPtr clientCon;
        toSendList toSendList_;
	uint32_t packetNr;
	uint32_t sesionCounterL;
};
typedef std::list<conn_data> ConnectionList;

And on connection close, i removed class from list (with pointer) , but the fd (file description) is not releasing so after while i reach the limit (default 1024 fd per app)
