### ISSUE TITLE
handleClosed可能导致服务端的数据不能完整的发送到客户端？

### ISSUE THREAD

**Issue by cf593796769** [chenshuo/muduo#130]
如果客户端调用shutdown关闭写，服务端handleRead将读取到0，并调用handleClose。 而handleClose中会调用`channel_->disableAll();` 停止监听该TcpConnection上的所有事件（包括POLLOUT）。并且最后的` closeCallback_(guardThis);`将会把channel从eventloop中移除。 **如果这时TcpConnection还有数据在outputBuffer_中，那么这些在buf中的数据将没有机会发送到客户端了。**

**Comment by chenshuo** [comment]
客户端为什么要在没有收完数据之前就调用shutdown？

**Comment by cf593796769** [comment]
比如是一个应答模型：客户端发完数据了，就将socket的写端关闭了，只保留读端来接收服务器的响应报文。

**Comment by chenshuo** [comment]
你需要重新设计协议。

**Comment by cf593796769** [comment]
那如果是协议就要求这样的效果呢：只允许服务端向客户端发送数据，不允许客户端发数据到服务端。

另外再问一哈，在shutdownInLoop中只通过 channel_->isWriting()来判定是否还有数据要写。 
但是如果这时候还存在其它线程发过来的数据在 EventLoop的 pendingFunctors_ ,那么这些将要发送的数据是不是就不能发到客户端了？

还有`TcpConnection::send`函数中的boost::bind 为什么要传this而不是shared_ptr呢，我看代码上注释了FIXME，但是没有写原因。 用this的话，在跨线程调用`TcpConnection::send`会有安全隐患的啊。

**Comment by guochunyang** [comment]
bind是把成员函数适配成类似全局函数的function对象，是要消除send函数的隐式参数，这和shared_ptr无关

**Comment by chenshuo** [comment]
且不论你这单向协议设计是否合理，只要客户端不shutdown，服务端就可以一直发数据，有什么问题？

你为什么要在其他线程有可能发数据的情况下调用shutdown？

既然你要跨线程使用TcpConnection，你需要正确管理其生命期。

**Comment by cf593796769** [comment]
1. 关于handleClosed的问题，我只是举例说明，muduo作为服务端时存在出错的可能性。 当然如果客户端严格按照约定进行，当然不会存在任何问题。 但是这样对客户端的约束也太多了，客户端编码的时候也会考虑更多的问题。 既然muduo这里存在可能出错的漏洞，为什么不选择堵上呢？

2. @guochunyang 我明白bind的用途，我意思是TcpConnection产生的对象在muduo里面是使用shared_ptr管理的，但是这里出现了this的裸指针。 这样会存在安全隐患的——TcpConnection对象消亡了，但是function对象还存在。。

3. muduo的 TcpConnection::send的设计是允许跨线程使用的，那么muduo内部就应该保证在各种合理的情况下，跨线程发送不会存在问题。 
> 你为什么要在其他线程有可能发数据的情况下调用shutdown？

调用shutdown的原因可能是TcpConnecton所在的线程主动shutdown的；也可能是由于客户端关闭写端，导致handleRead返回0而关闭的（现在muduo的代码是直接销毁这个TcpConnection）。

> 既然你要跨线程使用TcpConnection，你需要正确管理其生命期。 

 比如： 线程B调用线程A的TcpConnection::send发送数据，这时线程A的TcpConnection还是合法的，然后线程B产生的数据发送被封装为function放到的线程A的pendingFunctors_中。 然后这时候线程A由于一些原因调用了shutdown。 这种情况是完全合法的，但是却会导致pendingFunctors_中的数据丢失，如果function对象中保存的是this指针，还可能会出现非法指针的使用。

**Comment by liyuan989** [comment]
>比如： 线程B调用线程A的TcpConnection::send发送数据，这时线程A的TcpConnection还是合法的，然>后线程B产生的数据发送被封装为function放到的线程A的pendingFunctors_中。 然后这时候线程A由于一>些原因调用了shutdown。 这种情况是完全合法的，但是却会导致pendingFunctors_中的数据丢失，如果>function对象中保存的是this指针，还可能会出现非法指针的使用。
如果你使用的是TcpServer和TcpClient是不会出现这种情况的。
但如果你是自己单独封装使用TcpConnection的话，就像陈硕说的那样，需要自己正确管理其生命期。

**Comment by chenshuo** [comment]
1. 我没见过哪个协议会在 shutdown 之后还指望对方继续发数据，这种协议或许存在，但不属于muduo支持的范围。关键是client调用shutdown和close对于server来说是不可区分的（server 只能通过尝试发送数据来探测client有没有close，但作为library无权替用户发这种探测数据），因此我认为read读到0就关闭连接是合理的，能应付大多数场合，而且library代码逻辑清晰，也不打算修改muduo现有的行为。如果你的client一定要在读完数据之前就shutdown，我认为这个程序不适合用muduo来写。

2. 你需要构造一个例子，说明这个race condition确实会发生，才好进一步分析。

**Comment by Solaris-wj** [comment]
管理这个TcpConnection的生命周期太难了。多个线程写一个channel 不会出问题，但是由那个线程来负责关闭呢？  如果写之前判断关闭的话，那么多线程判断关闭与否然后进行写会有竞态问题。
这种多线程写一个channel 我觉得很难处理，java的netty貌似也有这个问题。

**Comment by chenshuo** [comment]
Any update?
