### ISSUE TITLE
idleconnection 里面的桶支持多线程？

### ISSUE THREAD

**Issue by hzhxxx** [chenshuo/muduo#142]
typedef boost::unordered_set<EntryPtr> Bucket;
  typedef boost::circular_buffer<Bucket> WeakConnectionList;
按理是不支持多线程的，如果
void EchoServer::start()
{
  server_.setThreadNum(5);
  server_.start();
}

如果这样，是不是对桶的访问需要加锁。

**Comment by guochunyang** [comment]
需要

**Comment by hzhxxx** [comment]
如果对方主动关闭连接，桶里面进行清理，也需要固定循环完成一个周期，这点是否能优化。

**Comment by hzhxxx** [comment]
第二个缺陷就是如果连接数比较多，比如 1w,但是桶circular_buffer里面分配了值120(120s超时)，
数据发送也比较频繁，每秒发送一个数据包，基本每个同里面都有1w的元素。
那桶 typedef boost::unordered_set<EntryPtr> Bucket 里面的 Entry 会非常多，比较消耗内存。
而且，每次一个桶被挤出，也会进行多次引用计数递减。

**Comment by hzhxxx** [comment]
当然，可以提高检查频率来减少清理。
loop->runEvery(1.0, boost::bind(&EchoServer::onTimer, this));
加大检测间隔。

**Comment by hzhxxx** [comment]
因为连接属只属于于一个 IO 线程，是否在每个 IO线程内构建这些连接桶，由IO线程管理属于自己内部的这些连接。

**Comment by chenshuo** [comment]
this is not a forum.
