### ISSUE TITLE
muduo 库使用 fastcgi 的问题

### ISSUE THREAD

**Issue by hzhxxx** [chenshuo/muduo#143]
int main(int argc, char *argv[])
{    

    /*char name[256];
    strncpy(name, "aa.log", 256);
    g_logFile.reset(new muduo::LogFile(::basename(name), 200*1000));
    muduo::Logger::setOutput(outputFunc);
    muduo::Logger::setFlush(flushFunc);*/

    while (FCGI_Accept() >= 0)
    {
        printf("Content-Type:text/plain\n\n");
        //LOG_INFO << "pid = " << getpid();
        char *p = 0;
        bool result = 0;
        //get_post_content(&p);
        if(result)
        {
            std::string jsonstr = p;
            free(p);
            //do_request(jsonstr);            
        }
        else
        {
            //LOG_ERROR << "get_post_content fail:\n";
            //LOG_ERROR << "get_post_content fail:\n";
            print_errmsg(2,"get_post_content fail");
        }
    }
        
    return 0;
}

apache-httpd 2.4
mod_fcgid 2.3.9
链接的 C库版本的 fcgi(http://www.fastcgi.com/drupal/node/5)

只要包含了任何有关 muduo 的库，编译出来的 fastcgi 放到 httpd-2.4 下的 mod_fcgid 解析，这些cgi通过 http 请求来驱动执行，全部报 500 错误。查看 apache 日志,
End of script output before headers: recommand.fcgi
使用strace 跟踪了这些 cgi 的执行,并没有发现输出异常(非 HTTP格式)数据。
怀疑是muduo::logger,因为只有这个才会向 cgi 的输出终端写数据，写的数据被发送到httpd 服务器，导致错误。但是把 log 输出到文件，也没有解决问题。
把日志文件设置为最高 FATAL 也不对。

**Comment by hzhxxx** [comment]
换了一个 centos,可以了，看来不是 muduo 的问题。

**Comment by guochunyang** [comment]
具体是什么原因呢？
