### ISSUE TITLE
About the function of Condition.wait()

### ISSUE THREAD

**Issue by demiaowu** [chenshuo/muduo#145]
为什么在Condition.wait()方法中使用MutexLock::UnassignGuard ug(mutex_);这一步将mutex_.holder_ 设置为0？

**Comment by liyuan989** [comment]
因为在pthread_cond_wait内部，线程进入等待的时候，系统会对mutex_解锁，所以将mutex_holder_恢复为0。

**Comment by demiaowu** [comment]
但是pthread_cond_wait()返回之后，mutex已经被加锁了，但是mutex_.holder的状态没有被继续维护

**Comment by liyuan989** [comment]
当pthread_cond_wait被唤醒返回，Condition::wait结束，MutexLock::UnassignGuard ug析构时就会恢复mutex_holder_的状态

**Comment by demiaowu** [comment]
你是对的，Sorry，我没有注意到~/强~

**Comment by guochunyang** [comment]
看了 @liyuan989 的解释才真正明白。

我之前自己封装Condition时，在wait前加了一行断言，断定mutex已经lock，muduo某个版本之前也是这样做的，这样做有问题。

**Comment by chenshuo** [comment]
@guochunyang muduo 哪个版本会在 wait 之前断言 mutex 已经 lock？
