### ISSUE TITLE
每个connection都注册一个定时器(runEvery)到EventLoop中合理吗？

### ISSUE THREAD

**Issue by xiaoNEC** [chenshuo/muduo#146]
如题，我想请教关于TimerQueue的使用。每个连接在处理心跳时，各自AddTimer到TimerQueue中合理吗？理由是什么？

我现在在1)添加一个定时器，在这个定时器中处理所有连接的心跳(需要自己判断是否需要心跳)；和2)为每个连接添加一个定时器，定时器到时即处理心跳;之间犹豫。希望大家指点？

困惑的原因是我在chenshuo的博客上看到说，不应该在TimerQueue中添加10个以上的定时器(文章发表时间较早)。而在《Linux多线程服务端编程》中暂时也没看到相关介绍。

**Comment by guochunyang** [comment]
没必要每个连接一个定时器，参考《断开空闲连接》那一节的内容。

**Comment by chenshuo** [comment]
This is not a forum.
