### ISSUE TITLE
Some issues about the  kLargeBuffer

### ISSUE THREAD

**Issue by demiaowu** [chenshuo/muduo#147]
In the LogStream.cc we have define the 
    const int kSmallBuffer = 4000;
    const int kLargeBuffer = 4000*1000;
Why not define as fellowing:
    const int kSmallBuffer = 4096;
    const int kLargeBuffer = 4096*1024;
I think It's might a little bit amity for the OS's memory managerment.

**Comment by chenshuo** [comment]
This is not a forum.

**Comment by demiaowu** [comment]
@chenshuo Maybe we need a forum ^_^
