### ISSUE TITLE
muduo的c++11版本/支持Mac

### ISSUE THREAD

**Issue by yedf** [chenshuo/muduo#150]
muduo是一个设计十分优雅的库，我从muduo中学到了许多网络编程的技巧，同时看到大家对muduo非常关注，因此写了一个muduo的c++11版本[handy](https://github.com/yedf/handy)，可以在支持g++4.8以及Mac上面运行，欢迎大家测试并提出宝贵意见

**Comment by chenshuo** [comment]
irrelevant
