### ISSUE TITLE
How to know Tcpclient fail to connect with a server?

### ISSUE THREAD

**Issue by tachoi** [chenshuo/muduo#158]
I can not find a function(or method) to detect the connection failure with a server when TcpClient try to connect with a server. How to know connection failure?

**Comment by yedf** [comment]
you can find an example in examples/simple/chargenclient/chargenclient.cc

**Comment by tachoi** [comment]
I wrote code as followed:
 1.  client_.setConnectionCallback(boost::bind(&SdpController::onConnection, this, _1));
 2.  SdpController::connect(void) { client_.connect(); }

After SdpController::connect was called:
when the server is alive, SdpController::onConnection is called. But, SdpController::onConnection is not called when the server is down.

**Comment by tachoi** [comment]
Tested using "asio_chat_client".

I modified the code as followed:
class ChatClient : boost::noncopyable
{
 public:
  ChatClient(EventLoop* loop, const InetAddress& serverAddr)
    : client_(loop, serverAddr, "ChatClient"),
      codec_(boost::bind(&ChatClient::onStringMessage, this, _1, _2, _3))
  {
    client_.setConnectionCallback(
        boost::bind(&ChatClient::onConnection, this, _1));
    client_.setMessageCallback(
        boost::bind(&LengthHeaderCodec::onMessage, &codec_, _1, _2, _3));
    //client_.enableRetry();
  }

As  above , TcpClient is not enabled to retry. But the log message show that connection was retried as followed log messages:

2015/08/05 06:21:33.218462Z 22307 INFO  pid = 22307 - client.cc:83
2015/08/05 06:21:33.218671Z 22307 INFO  TcpClient::TcpClient[ChatClient] - connector 0x1EE0170 - TcpClient.cc:71
2015/08/05 06:21:33.218690Z 22307 INFO  TcpClient::connect[ChatClient] - connecting to 192.168.4.33:400 - TcpClient.cc:109
2015/08/05 06:21:33.220726Z 22308 WARN  Channel::handle_event() POLLHUP - Channel.cc:91
2015/08/05 06:21:33.220744Z 22308 ERROR Connector::handleError state=1 - Connector.cc:201
2015/08/05 06:21:33.220775Z 22308 INFO  Connector::retry - Retry connecting to 192.168.4.33:400 in 500 milliseconds.  - Connector.cc:217
2015/08/05 06:21:33.726199Z 22308 WARN  Channel::handle_event() POLLHUP - Channel.cc:91
2015/08/05 06:21:33.726212Z 22308 ERROR Connector::handleError state=1 - Connector.cc:201
2015/08/05 06:21:33.726233Z 22308 INFO  Connector::retry - Retry connecting to 192.168.4.33:400 in 1000 milliseconds.  - Connector.cc:217

**Comment by yedf** [comment]
I can not find the callback also.
Connection will reconnect when it's closed by server if retry option set. It will always retry when connecting.

**Comment by chenshuo** [comment]
Use a timer if you want this.

**Comment by yedf** [comment]
you may try github.com/yedf/handy
example can be found https://github.com/yedf/handy/blob/master/examples/codec-cli.cc

**Comment by tachoi** [comment]
When session is disconnected by server, Connector's state is still 'kConnected'. So, segment fault occurred at 'Connector::startInLoop'  after trying calling TcpClient::connect'.
I modified the code as followed:

void Connector::start()
{
  connect_ = true;
  if( state_ != kDisconnected) restart();
  else loop_->runInLoop(boost::bind(&Connector::startInLoop, this)); // FIXME: unsafe
}

**Comment by tachoi** [comment]
I also modified code:

in Connector.h file:
void enableRetry() { retry_ = true; }

In Connector.cc file:

void Connector::stopInLoop()
{
  loop_->assertInLoopThread();
  if (state_ == kConnecting)
  {
    setState(kDisconnected);
    int sockfd = removeAndResetChannel();
    if( retry_) retry(sockfd);
  }
}

void Connector::handleError()
{
  LOG_ERROR << "Connector::handleError state=" << state_;
  if (state_ == kConnecting)
  {
    int sockfd = removeAndResetChannel();
    int err = sockets::getSocketError(sockfd);
    LOG_TRACE << "SO_ERROR = " << err << " " << strerror_tl(err);
    if( retry_) retry(sockfd);
  }
}

**Comment by chenshuo** [comment]
Code example to reproduce segment fault in Connector::start() ?

**Comment by tachoi** [comment]
I added the code "if( state_ != kDisconnected) restart();" to protect the fault. If I delete the code from "Connector::start()" as followed, the segment fault occurred  when the function is called after the session is disconnected by a server.

void Connector::start()
{
  connect_ = true;
  //if( state_ != kDisconnected) restart();
  //else loop_->runInLoop(boost::bind(&Connector::startInLoop, this)); // FIXME: unsafe
  loop_->runInLoop(boost::bind(&Connector::startInLoop, this)); // FIXME: unsafe
}


The result of segment fault is

sdp_gateway: /home/sdp/muduo-1.0.4/muduo/net/Connector.cc:54: void muduo::net::Connector::startInLoop(): Assertion `state_ == kDisconnected' failed.

Program received signal SIGABRT, Aborted.
0x0000003439632625 in raise (sig=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
64        return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
Missing separate debuginfos, use: debuginfo-install libnetfilter_queue-1.0.1-3.el6.x86_64 libnfnetlink-1.0.0-1.el6.x86_64

**Comment by chenshuo** [comment]
You shall not call TcpClient::client() more than once.

**Comment by chenshuo** [comment]
And it is not segment fault, it's assertion failure, means you are doing something wrong.

**Comment by tachoi** [comment]
You are fright. It's assertion failure.

The problem is that Connector's state does not change 'kConnected' to 'kDisconnected' in spite of the disconnected session. When the session is disconnected by a server, 'onConnection' callback is called and TcpConnection's state also changed 'kConnected' to 'kDisconnected', but Connector's state still remain 'kConnected'.

When I call the TcpClient::connect, assertion failure is occurred at the Connector::startInLoop(), because Connector's state is not 'kDiscoonected'.

**Comment by chenshuo** [comment]
How many times did you call TcpClient::connect() ? It should only be called once.

**Comment by tachoi** [comment]
twice. As I mentioned previously, I modified the code of Connector to make user can select automatically retry to connect or not. Above case is that Connector do not retry to connect.
I want to make the application can select to connect a server or another server .

**Comment by chenshuo** [comment]
You shall not call TcpClient::client() more than once.
