### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yangwen-2007** [chenshuo/muduo#159]
when I excuted build.sh, I got following errors:
/home/yangwen.yw/code/muduo/muduo/base/AsyncLogging.cc:1: error: bad value (native) for -march= switch

env:
kernal:2.6.32
gcc version 4.1.2 20080704 (Red Hat 4.1.2-51)
cmake version 2.8.12.2
boost:1.58.0

Why? Please help

**Comment by chenshuo** [comment]
GCC version is too low, use 4.4 or higher.

**Comment by yangwen-2007** [comment]
OK，I will try that，thx！
