### ISSUE TITLE
timeZone.cc 闰秒

### ISSUE THREAD

**Issue by DongweiLee** [chenshuo/muduo#163]
1. toLocaltime函数 中gmtime_r 和 fromLocaltime 中函数timegm所传的参数均为本地时间，可能转换结果有一秒的闰秒误差
   比如北京时间2015年7月1号7:59:60出现，在此处添加了闰秒，相应地gmt2015年6月30号23:59:60插入闰秒; 现在timegm传入时间北京本地时间2015年7月1号 07:00:00, 则timegm返回结果中将会加入最后一次闰秒，而实际此处是不应添加的
  gmtime_r有同样的问题
  更进一步，在闰秒添加附近的时间，toLocaltime和FromLocaltime的互逆性可能难以保证

2.toUtcTime 和fromUtcTime中完全没有考虑闰秒的影响，而UTC的定义是“协调世界时是以原子时秒长为基础，在时刻上尽量接近于世界时的一种时间计量系统。”，定义中尽量接近的方式就是添加闰秒，所以如果没有考虑闰秒的话，则这两个函数最好换一个名字

3.glibc中的时间处理函数多有全局锁，所以最好能完全去掉gmtime_r和timegm的使用，以免高频调用toLocaltime和FromLocaltime的多线程程序串行化

**Comment by DongweiLee** [comment]
上述提到的第3点不算问题

第1点也影响不大，但是应有说明吧
第2点感觉换命确实很有必要

最近在看《linux端服务端编程》,收获很多

**Comment by chenshuo** [comment]
Unix timestamp (time_t) 无法表示闰秒。

**Comment by DongweiLee** [comment]
我之前错以为 UNIX时间戳秒数增长的方式完全跟随原子钟  谢指正
