### ISSUE TITLE
gettimeofday时光倒流问题

### ISSUE THREAD

**Issue by zakilo** [chenshuo/muduo#165]
今天和朋友讨论，gettimeofday函数会出现相继两次调用，后者的时间值会比前者小。
参看这个blog：[gettimeofday的时间倒转（回溯）现象与解决](http://blog.chinaunix.net/uid-24830931-id-3864566.html)

muduo是否也该将gettimeofday换成clock_gettime？
（代码位置muduo/base/Timestamp.cc  Timestamp::now()）

**Comment by red-chen** [comment]
这个使用场景不一样的，gettimeofday表示当前时间，clock_gettime表示系统重启动到现在的时间，clock_gettime递增一般用于比如延时（Latency）的计算.

gettimeofday的确有“时间跳跃”的问题，但是用于记录当前事件的发生，如日志中的时间打印，没有任何问题

**Comment by zakilo** [comment]
clock_gettime可以表示当前时间呀，将第一个参数clk_id传为CLOCK_REALTIME。
我只看了muduo一小部分，，请问muduo这里gettimeofday只用于记录事件发生时间，而且时间跳跃的误差小到可以忽略吗？另外，Timestamp并没有用到延迟的计算吗？若是如此，是否muduo不能用于计算较精确时间差？（比如我想用Timestamp类计时时）

**Comment by chenshuo** [comment]
gettimeofday 和 clock_gettime(REALTIME) 一样会受 NTP 控制。

http://stackoverflow.com/a/3527632 ：
> this means that CLOCK_REALTIME can jump forwards and backwards as the system time-of-day clock is changed, including by NTP.
