### ISSUE TITLE
定时器 失效问题

### ISSUE THREAD

**Issue by yukuilong** [chenshuo/muduo#168]
发现一个题 ，runEvery这个定时器 ，在更改系统时间后就失效了，不会再执行回调了。

**Comment by chenshuo** [comment]
1. 请提供完整的复现步骤。
2. 服务器一般会用 NTP 同步系统时钟，手工“更改系统时间”是很少见的。

**Comment by yukuilong** [comment]
1，loop->runEvery(1.0, boost::bind(&RecordServer::cycleTask, this));设置了一个循环执行的定时器，通过命令data -s "2015-11-04 10:06:00"设置系统时间，或者是通过settimeofday函数修改系统时间都会照成这个定时器失效，cycleTask不会执行了。
2，muduo目前用到了嵌入式上面，只连接局域网，NTP用起来比较麻烦，而需求需要对嵌入式系统进行时间设置等管理，所以就要发送网络命令通过settimeofday来设置系统时间。

**Comment by chenshuo** [comment]
muduo的定时器是基于绝对时间，如果你把时间往前调（3:00调到2:00），那么事件会延迟一个小时发生。如果确实不能用NTP，那么一个比较简单的解决办法是起一个线程，通过while(true) { nanosleep(); } 来定时，然后用 EventLoop::runInLoop 把事件发到主线程。

**Comment by yukuilong** [comment]
好的，非常感谢
