### ISSUE TITLE
关于启动tcp服务器退出的问题

### ISSUE THREAD

**Issue by yuanmartin** [chenshuo/muduo#169]
陈老师，你好！
       本人使用muduo库来做一个tcp服务器，在用调用InetAddress类通过传进监听端口创建对象时，程序马上退出，用gdb调试core文件时bt显示的队盏如下：
[root@localhost accesserver]# gdb datasvr core.18694 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-64.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/eco/accesserver/datasvr...done.
[New LWP 18694]
[New LWP 18703]
[New LWP 18702]
  [Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./datasvr'.
Program terminated with signal 4, Illegal instruction.
#0  __bswap_32 (__bsx=0) at /usr/include/bits/byteswap.h:47
47	  return __builtin_bswap32 (__bsx);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-78.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.12.2-14.el7.x86_64 libcom_err-1.42.9-7.el7.x86_64 libgcc-4.8.3-9.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libstdc++-4.8.3-9.el7.x86_64 openssl-libs-1.0.1e-42.el7.x86_64 pcre-8.32-14.el7.x86_64 xz-libs-5.1.2-9alpha.el7.x86_64 zlib-1.2.7-13.el7.x86_64
(gdb) bt
#0  __bswap_32 (__bsx=0) at /usr/include/bits/byteswap.h:47
#1  0x000000000046f932 in muduo::net::sockets::hostToNetwork32 (host32=0)
    at /opt/sourcecode/muduo/muduo/net/Endian.h:38
#2  0x000000000046f5c6 in muduo::net::InetAddress::InetAddress (this=0x7fff6c6a9370, port=7788, 
    loopbackOnly=false) at /opt/sourcecode/muduo/muduo/net/InetAddress.cc:50
#3  0x000000000045b8ec in CTCPServiceModule::StartTCPServer (this=0x1e6e830, port=7788, num=10)
    at ../muduotcp/TCPServiceModule.cpp:68
#4  0x0000000000414e5f in CIntelligentGatewayAcceptor::StartTcpServer (this=0x7fff6c6a9440, 
    port=7788, num=10) at IntelligentGatewayAcceptor.cpp:24
#5  0x000000000040ab8d in main () at datasvr.cpp:102
(gdb) ^CQuit
(gdb) 

     这个程序是运行在centos 7上的，在有些同样装的centos 7的机器上可以，但是有些机器上不行，不知道是什么原因，请陈老师指点下

**Comment by chenshuo** [comment]
编译的时候去掉 -march=native 选项：
https://github.com/chenshuo/muduo/blob/master/CMakeLists.txt#L27

或者在CPU最老的机器上编译。
