### ISSUE TITLE
muduo编译时出错

### ISSUE THREAD

**Issue by ponlee** [chenshuo/muduo#174]
编译环境： 
系统   x86_64-redhat-linux
编译器版本： gcc version 4.4.6

出错信息：
[  1%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/AsyncLogging.cc.o
cc1plus: error: unrecognized command line option "-mbmi-msse4.2"
make[2]: *** [muduo/base/CMakeFiles/muduo_base.dir/AsyncLogging.cc.o] Error 1
make[1]: *** [muduo/base/CMakeFiles/muduo_base.dir/all] Error 2

**Comment by chenshuo** [comment]
muduo代码里没有使用过 -mbmi 等参数，你找找在哪里定义的。
