### ISSUE TITLE
muduo logstream_test 链接时报错

### ISSUE THREAD

**Issue by dachuan1229** [chenshuo/muduo#175]
编译环境： 
系统：Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu
编译器版本： gcc version 4.8.4  
错误信息：
[ 16%] Building CXX object muduo/base/tests/CMakeFiles/singleton_test.dir/Singleton_test.cc.o
Linking CXX executable ../../../bin/logstream_test
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, int, int>':
/usr/include/boost/test/tools/old/impl.hpp:92: undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, __gnu_cxx::__versa_string<char>, __gnu_cxx::__versa_string<char> >':
/usr/include/boost/test/tools/old/impl.hpp:92: undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `testLogStreamFloats::test_method()':
/home/summer/dachuan/muduo-master/muduo/base/tests/LogStream_test.cc:157: undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, int, int>':
/usr/include/boost/test/tools/old/impl.hpp:92: undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
/usr/include/boost/test/tools/old/impl.hpp:92: undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)':
/usr/include/boost/test/tree/test_unit.hpp:249: undefined reference to `boost::unit_test::test_case::test_case(boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long, boost::function<void ()> const&)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `__static_initialization_and_destruction_0':
/home/summer/dachuan/muduo-master/muduo/base/tests/LogStream_test.cc:13: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/home/summer/dachuan/muduo-master/muduo/base/tests/LogStream_test.cc:26: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/home/summer/dachuan/muduo-master/muduo/base/tests/LogStream_test.cc:43: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/home/summer/dachuan/muduo-master/muduo/base/tests/LogStream_test.cc:113: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/home/summer/dachuan/muduo-master/muduo/base/tests/LogStream_test.cc:172: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o:/home/summer/dachuan/muduo-master/muduo/base/tests/LogStream_test.cc:186: more undefined references to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [bin/logstream_test] Error 1
make[1]: *** [muduo/base/tests/CMakeFiles/logstream_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable ../../../bin/singleton_test
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 16%] Built target singleton_test
make: *** [all] Error 2

**Comment by chenshuo** [comment]
贴
dpkg -l |grep libboost
的完整输出。

**Comment by dachuan1229** [comment]
root@ubuntu:/home/summer/dachuan/muduo-master# dpkg -l |grep libboost
ii  libboost-dev                        1.54.0.1ubuntu1                  amd64        Boost C++ Libraries development files (default version)
ii  libboost-iostreams1.54.0:amd64      1.54.0-4ubuntu3.1                amd64        Boost.Iostreams Library
ii  libboost-test-dev:amd64             1.54.0.1ubuntu1                  amd64        components for writing and executing test suites (default version)
ii  libboost-test1.54-dev:amd64         1.54.0-4ubuntu3.1                amd64        components for writing and executing test suites
ii  libboost-test1.54.0:amd64           1.54.0-4ubuntu3.1                amd64        components for writing and executing test suites
ii  libboost1.54-dev                    1.54.0-4ubuntu3.1                amd64        Boost C++ Libraries development files

**Comment by chenshuo** [comment]
先卸载 libboost-test*，再编译试试。

**Comment by dachuan1229** [comment]
编译通过了，非常感谢！！
