### ISSUE TITLE
muduo库的多线程异步日志自带的测试文件AsyncLogging_test.cc将LOG_INFO改为LOG_WARN,LOG_FATAL,LOG_ERROR编译不能正常输出日志

### ISSUE THREAD

**Issue by HUETGET** [chenshuo/muduo#176]
硕哥，项目需要打算采用muduo的异步日志功能，测试了一番，为了避免引入其他多线程的问题，只用你写的AsyncLogging_test.cc重新测试了一下，经过测试发现你的代码用的LOG_INFO这个宏可以正常输出日志到文件，当使用LOG_WARN时输出的日志文件如我所提到的是16进制的结果，使用LOG_ERROR,LOG_FATAL,时出现了段错误，程序自动退出，输出的日志文件为16进制如下：（截取使用LOG_WARN的输出的部分文件）
3230 3136 3031 3034 2030 373a 3336 3a30
352e 3735 3830 3539 5a20 3132 3538 3920 
5741 524e 0045 4865 6c6c 6f20 3031 3233 
3435 3637 3839 2061 6263 6465 6667 6869 
6a6b 6c6d 6e6f 7071 7273 7475 7677 7879 
7a20 2030 202d 2041 7379 6e63 4c6f 6767

具体的代码如下：（AsyncLogging_test.cc）
××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××
for (int i = 0; i < kBatch; ++i)
{ 
            LOG_INFO << "Hello 0123456789" << " abcdefghijklmnopqrstuvwxyz "
           << (longLog ? longStr : empty)
           << cnt; //正常输出，没有问题
}
/×日志正常输出到文件，截取日志如下：
20160104 07:23:25.530532Z 12436 INFO Hello 0123456789 abcdefghijklmnopqrstuvwxyz 0 - 
 20160104 07:23:25.530574Z 12436 INFO Hello 0123456789 abcdefghijklmnopqrstuvwxyz 1 - 
20160104 07:23:25.530580Z 12436 INFO Hello 0123456789 abcdefghijklmnopqrstuvwxyz 2×/

××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××
LOG_DEBUG << "Hello 0123456789" << " abcdefghijklmnopqrstuvwxyz "; << (longLog ? longStr : empty) << cnt; 
//直接就是没有输出，控制输出的时间了LOG_INFO相比比较小，推测可能是时间太短没有flush到硬盘程序就执行结束了
×××××××××××××××××××××××××××××××××××××××××××××××××××××××××××
LOG_WARN << "Hello 0123456789" ; //输出16进制的字符，结果见开头
×××××××××××××××××××××××××××××××××××××××××××××××××××××××××××
LOG_ERROR << "Hello 0123456789" ; //出现段错误，直接退出
×××××××××××××××××××××××××××××××××××××××××××××××××××××××××××
LOG_FATAL << "Hello 0123456789" ； //出现段错误，直接退出××××××××××××××××××××××××××××××××××××××××××××××××××××××××××× }
为了避免相互影响，上面的日志语句都是单独测试程序，可以看出只有LOG_INFO能够正常输出，其他的都存在一些问题。
最后，我只是能够发现问题，还没有找到解决问题的办法，希望硕哥能解答我的疑惑！也希望muduo库变得越来越健壮！

**Comment by chenshuo** [comment]
LOG_DEBUG 没有输出是正常的，你要设置环境变量 MUDUO_LOG_DEBUG=1。
LOG_WARN 输出16进制究竟是什么现象？我这里无法复现。你用 less/cat 看日志文件内容是什么？
LOG_ERROR 出现段错误在我这里也无法复现。
LOG_FATAL 本来就应该退出程序。
你要把完整的编译运行环境说清楚，包括硬件平台、Linux版本、编译器版本、boost库版本等等。你是怎么编译运行 asynglogging_test 的？
还要把你改过的代码完整地贴出来，或者贴diff -u的完整输出。
