### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by xiaopeifeng** [chenshuo/muduo#179]
when i build the newset version of muduo, i found the compile errror info as follows:
muduo/net/protobuf/ProtobufCodecLite.cc:30:7: error: '{anonymous}::dummy' defined but not used [-Werror=unused-variable]
int dummy = ProtobufVersionCheck();

**Comment by chenshuo** [comment]
Show me the output of `gcc -v`

**Comment by xiaopeifeng** [comment]
the output of gcc -v is:
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /build/gcc/src/gcc-5-20160209/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 5.3.0 (GCC)

**Comment by chenshuo** [comment]
Add
`-Wnoerror=unused-variable`
to CMakeFiles.txt

**Comment by xiaopeifeng** [comment]
thanks a lot

**Comment by linghutf** [comment]
@chenshuo Maybe is `-Wno-error=unused-variable`
