### ISSUE TITLE
客户端使用线程池出现死锁情况

### ISSUE THREAD

**Issue by motorleo** [chenshuo/muduo#180]
对自己写的轮子RPC进行吞吐量测试时，客户端单线程运行正常，使用线程池发起连接时有时侯出现死锁，有时候上锁崩溃：
testClient: /home/maxiaoda/muduo/muduo/base/Mutex.h:81: lock: Unexpected error: Invalid argument.
已放弃

吞吐量测试代码与示例中的乒乓协议测试代码差不多

**Comment by motorleo** [comment]
`class testClient : public RpcClientLite
{
public:
    testClient(EventLoop* loop,const InetAddress& addr,bench* owner)
        :RpcClientLite(loop,addr),
		stub_(getChannel()),
		messagecount_(0),
		owner_(owner),
		exit_(false)
    {
    }

	int messagecount() { return messagecount_;}

	void setExit() { exit_ = true; }
private:
    virtual void initCallback(const TcpConnectionPtr& conn);
    
    void doneCallback(test::testMessage* request);

    test::testService_Stub stub_;
	int messagecount_;
	bench* owner_;
	bool exit_;
};

class bench
{
public:
	bench(EventLoop* loop,
			const InetAddress& addr,
			int nClient,
			int nMessageSize,
			int Timeout)
		:loop_(loop),threadPool_(loop,""),ClientCount_(0),timeout_(Timeout)
	{
		loop->runAfter(Timeout, boost::bind(&bench::setExit, this));
		for (int i = 0;i < nMessageSize;++i)
		{
			string_ += 'i';
		}

		//threadPool_.setThreadNum(2);
		threadPool_.start();

		for (int i = 0;i < nClient;++i)
		{
			testClient* client = new testClient(threadPool_.getNextLoop(),addr,this);
			client->connect();
			testVec_.push_back(client);
		}
	}

	void setExit()
	{
		std::vector<testClient*>::iterator iter = testVec_.begin();
		for (;iter < testVec_.end();++iter)
		{
			(*iter)->setExit();
		}
	}

	int getTimeout() { return timeout_;}

	const std::string& getString() { return string_; }

	void onDisconnect()
	{
		if (--ClientCount_ == 0)
		{
			int messageCount = 0;
			std::vector<testClient*>::iterator iter = testVec_.begin();
			for (;iter < testVec_.end();++iter)
			{
				messageCount += (*iter)->messagecount();
				delete (*iter);
			}
			LOG_WARN << "all client done.";
			LOG_WARN << "Total send message:" << messageCount;
			LOG_WARN << static_cast<long long>(messageCount * string_.size()) / (getTimeout() * 1024 * 1024)
				     << " MB/s throughput.";
			LOG_WARN << messageCount / getTimeout() << " /s request.";
			loop_->quit();	
		}
	}

	void increaseCount() { ++ClientCount_; }
private:
	EventLoop* loop_;
	EventLoopThreadPool threadPool_;
	std::vector<testClient*> testVec_;
	std::string string_;
	int ClientCount_;
	int timeout_;
};

void testClient::initCallback(const TcpConnectionPtr& conn)
{   
	owner_->increaseCount();
	test::testMessage request;
	request.set_echostring(owner_->getString());
	test::testMessage* response(new test::testMessage());
	stub_.Echo(NULL,&request,response,NewCallback(this,&testClient::doneCallback,response));
}

void testClient::doneCallback(test::testMessage* request)
{   
	++messagecount_;
	if (!exit_)
	{
		if (request)
		{
			test::testMessage* response(new test::testMessage());
			stub_.Echo(NULL,request,response,NewCallback(this,&testClient::doneCallback,response));
		}
	}
	else
	{
		disconnect();
		owner_->onDisconnect();
	}
	delete request;
}

int main(int argc,char** argv)
{
	if (argc >= 5)
	{
		Logger::setLogLevel(Logger::WARN);
		EventLoop loop;
		InetAddress address(argv[1],9981);
		int nClient = atoi(argv[2]);
		int MessageSize = atoi(argv[3]);
		int timeout = atoi(argv[4]);
		bench client(&loop,address,nClient,MessageSize,timeout);
		loop.loop();
	}
	else
	{
		printf("Usage:<%s> <host_ip> <nClient> <MessageSize> <Timeout>!\n",argv[0]);
	}
}`

**Comment by chenshuo** [comment]
通常的原因是对象生命期管理出了错，比如 Mutex 析构之后再调用 lock()。

**Comment by motorleo** [comment]
感谢，已找到原因
