### ISSUE TITLE
FixedBuffer  reset 为什么不等同于 bzero？

### ISSUE THREAD

**Issue by lebinhe** [chenshuo/muduo#182]
在使用LogStream resetBuffer 时会造成困惑，resetBuffer后继续Log新的内容，可能会有脏数据，因为buffer并没有被清空，只是cur_指向到buffer头而已

**Comment by lebinhe** [comment]
另外 const char* data() const { return data_; } 与 string toString() const { return string(data_, length()); } 在结果上也存在不一致，是故意这么设计的？

**Comment by neverchanje** [comment]
所谓清空不是把内存块的每个byte都赋值为0就叫清空的。。。你只要把 cur_ 指向头指针就可以了呀。你的脏数据从何而来？每次log都会在末尾加 '\0'，表示字符串终结。或许你需要去了解c++字面量(literal)的知识。

**Comment by lebinhe** [comment]
void append(const char* /*restrict*/ buf, size_t len)
  {
    // FIXME: append partially
    if (implicit_cast<size_t>(avail()) > len)
    {
      memcpy(cur_, buf, len);
      cur_ += len;
    }
  }
没有加 '\0'啊，单元测试都通不过，就是因为每次append都没有'\0'，只有加上长度信息才是正确的，即toString方法是ok的，data方法就不行
比如这个：
TEST(LogStream, testLogStreamStrings)
{
     muduo::LogStream os;
     const muduo::LogStream::Buffer& buf = os.buffer();
 
     os << "Hello ";
     EXPECT_STREQ(buf.data(), "Hello ");
 
     string chenshuo = "Shuo Chen";
     os << chenshuo;
     EXPECT_STREQ(buf.data(), "Hello Shuo Chen");
}

muduo/base/ut/LogStream_test.cc:192: Failure
Value of: "Hello Shuo Chen"
Expected: buf.data()
Which is: "Hello Shuo Chen51615"
[  FAILED  ] LogStream.testLogStreamStrings (0 ms)

"Hello Shuo Chen51615"  里面的数字就是脏数据啊，上面一个TEST留下的，前面的部分覆盖了，后面的还在。。。
os << std::numeric_limits<uint64_t>::max();
 EXPECT_STREQ(buf.toString().c_str(), "18446744073709551615");
 os.resetBuffer();

**Comment by yongzhizhan** [comment]
这个是buffer，不是string，不要互相混淆了。对于buffer来说，\0不能说明数据的结束，只有通过长度来确定有效数据的范围。

2016-03-01 22:23 GMT+08:00 lebinhe <notifications@github.com>:

**Comment by lebinhe** [comment]
agree
