### ISSUE TITLE
muduo功能回归测试失败

### ISSUE THREAD

**Issue by DongweiLee** [chenshuo/muduo#186]
1. 使用版本1.0.7
2. uname -a 输出
Linux 10-10-14-62 2.6.32-431.11.15.el6.ucloud.x86_64 #1 SMP Fri Aug 14 15:14:16 CST 2015 x86_64 x86_64 x86_64 GNU/Linux
3. g++ --version  输出 g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
4.boost版本，1.59 从源码完整编译
5. 功能测试报错如下
![image](https://cloud.githubusercontent.com/assets/7995985/13915297/cf96a64c-ef8e-11e5-8500-8a71a8465183.png)
6. 对于其中的 TimerQueue_unittest报错
   自己另外编译 TimerQueue_unittest.cc
   编译命令 g++ TimerQueue_unittest.cc -o a.out -I../../../../build/release-install/include/  -L../../../../build/release-install/lib/ -lmuduo_base -lmuduo_net -lpthread
    执行时会出现core文件，跟踪core文件
![image](https://cloud.githubusercontent.com/assets/7995985/13915439/a237a1dc-ef8f-11e5-8249-c9c76a3668c0.png)
网上说是 vmovsd 命令不支持

    但是我使用的boost 和muduo都是在一个机器上编译的，搞不懂为什么

**Comment by DongweiLee** [comment]
ps 1. 之所以使用1.0.7版本而不是1.0.8是因为 ，1.0.8通不过编译，报错如下
![image](https://cloud.githubusercontent.com/assets/7995985/13915670/fc8c6dba-ef90-11e5-8ac1-c4faeb56b81a.png)

**Comment by chenshuo** [comment]
1. 去掉 CMakeLists.txt 里的 -march=native 试试。
2. 你的gcc版本太低，可以去掉59/60两行试试。

**Comment by DongweiLee** [comment]
去掉 -march=native 之后，test只剩一个错误了，即最上图中的 buffer_cpp11_uniittest 中的报错
这个是测c11 特性的，应该不影响使用吧

**Comment by DongweiLee** [comment]
1.0.8 版本 在去掉 werror 和 wconversion 编译标志后 也编译通过了，用自带的测试工具测试结果和v1.0.7
一样只剩下buffer_cpp11_uniittest 一个错误，应该没问题了，多谢了
