### ISSUE TITLE
TcpClient的析构导致崩溃问题

### ISSUE THREAD

**Issue by fdxuwei** [chenshuo/muduo#194]
我的需求是在程序运行时，根据从配置中心获取的ip地址动态的创建和删除TcpClient，但是删除TcpClient的时候经常导致程序崩溃。主要原因有：
1、删除TcpClient时，如果其对应的TcpConnection还未关闭，会导致~TcpConnection里面的assert(state_ == kDisconnected)失败;
2、当Connector的析构函数里面有时会assert(!channel_)失败；
3、Connector::stop里面把this指针传给其他线程，可能会产生无效指针；
请问有没有好的办法来解决这个问题？

**Comment by chenshuo** [comment]
最好能提供复现你说这些现象的代码。
1. 要么你先关闭连接，要么你让TcpConnection活到连接关闭之后再析构。
2. Connector 必须在停止使用之后才能析构。
3. 你可以用shared_ptr<TcpClient>把stop转到eventloop所在的线程，这样能防止无效指针。
如果你的程序只用一两个 TcpClient，那么不妨直接用阻塞IO，不必动态创建和删除 TcpClient。

**Comment by fdxuwei** [comment]
提供以下我最新的解决办法，测试没有coredump：
1、TcpConnection未关闭而析构导致assert失败：析构TcpClient前forceClose即可，forceClose内绑定了TcpConnectionPtr，可以保证TcpConnection 先关闭后析构；
2、但上面的方法又会导致新的问题：TcpConnection::handleClose会调用TcpClient::removeConnection， 但此时TcpClient可能已经被析构；虽然TcpClient析构函数里面有重置TcpConnection 的closeCallback函数，但是这个操作并不能保证一定先于TcpConnection::handleClose，所以出现了无效指针的错误。解决办法是先TcpConnection::forceClose, 再把TcpClientPtr转到其对应的loop线程，使TcpClient的析构在TcpConnection关闭之后。
3、TcpConnection::forceClose之前调用TcpClient::stop, 一是防止TcpClient ::retry， 二是避免Connector析构时的assert(!channel)错误。

以下是我的部分代码：
```
// TcpClients是封装的TcpClient池，内部结合EventLoopThreadPool实现多线程
void TcpClients::removeTcpClientInLoop(const std::string &ip, int port)
{
	// only run in main loop
	loop_->assertInLoopThread();
	//
	// 以对端服务的ip、port来标识一个TcpClient
	string clientName = makeClientName(ip, port);
	TcpClientMap::iterator itr = tcpClients_.find(clientName);
	if(tcpClients_.end() != itr)
	{
		// 先保存TcpClient
		TcpClientPtr cp= itr->second;
		// 停止TcpClient
		cp->stop();
		if(cp->connection())
		{
			// 关闭连接
			cp->connection()->forceClose();
			// 把TcpClient转至TcpConnection所在线程，使其在连接关闭之后析构
			// removeTcpClient 实质是空函数
			cp->connection()->getLoop()->runInLoop(boost::bind(&TcpClients::removeTcpClient, this, cp));
		}
		// 移除map中的TcpClient，此时TcpClient不会析构
		tcpClients_.erase(itr);
	}
}
```

**Comment by fdxuwei** [comment]
加大了测试规模，还是core了：
void muduo::MutexLock::lock(): Assertion `errnum == 0' failed.
在TcpClient.cc:158行：
```
void TcpClient::newConnection(int sockfd)
{
  ...
  {
    MutexLockGuard lock(mutex_);
    connection_ = conn;
  }
}
```

**Comment by chenshuo** [comment]
你一般同时有多少个 TcpClient ？

**Comment by fdxuwei** [comment]
最多有10-20个

**Comment by chenshuo** [comment]
那不妨直接用阻塞IO （可加 timeout，可以专门用一个两个线程）去 connect，等连接建立好拿到 socket file descriptor 之后再创建 TcpConnection 对象。
muduo TcpClient 目前不是设计来动态创建和销毁的。

**Comment by chris-shenzhen-china** [comment]
请教下这个问题解决了吗？如何使用能够更好的关闭 tcpClient
