### ISSUE TITLE
错误：‘NewCallback’在此作用域中尚未声明

### ISSUE THREAD

**Issue by docterling** [chenshuo/muduo#195]
[ 48%] Building CXX object muduo/net/protorpc/CMakeFiles/muduo_protorpc.dir/RpcChannel.cc.o
/root/p2nsrv/ling/muduo-1.0.8/muduo/net/protorpc/RpcChannel.cc: 在成员函数‘void muduo::net::RpcChannel::onRpcMessage(const TcpConnectionPtr&, const RpcMessagePtr&, muduo::Timestamp)’中:
/root/p2nsrv/ling/muduo-1.0.8/muduo/net/protorpc/RpcChannel.cc:142:90: 错误：‘NewCallback’在此作用域中尚未声明
                                 NewCallback(this, &RpcChannel::doneCallback, response, id));
                                                                                          ^
/root/p2nsrv/ling/muduo-1.0.8/muduo/net/protorpc/RpcChannel.cc:142:90: 附注：建议的替代：
In file included from /usr/local/include/google/protobuf/stubs/common.h:48:0,
                 from /usr/local/include/google/protobuf/service.h:104,
                 from /root/p2nsrv/ling/muduo-1.0.8/muduo/net/protorpc/RpcChannel.h:18,
                 from /root/p2nsrv/ling/muduo-1.0.8/muduo/net/protorpc/RpcChannel.cc:9:
/usr/local/include/google/protobuf/stubs/callback.h:508:32: 附注：  ‘google::protobuf::internal::NewCallback’
 inline ResultCallback1<R, A1>* NewCallback(R (*function)(P1, A1), P1 p1) {
                                ^
make[2]: *** [muduo/net/protorpc/CMakeFiles/muduo_protorpc.dir/RpcChannel.cc.o] 错误 1
make[1]: *** [muduo/net/protorpc/CMakeFiles/muduo_protorpc.dir/all] 错误 2
make: *** [all] 错误 2
[root@lingCentOS muduo-1.0.8]# protoc --version
libprotoc 3.0.0
[root@lingCentOS muduo-1.0.8]# uname -a
Linux lingCentOS 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
CentOs-6.6

**Comment by chenshuo** [comment]
Protobuf >= 3.0 is not release or supported by muduo.
