### ISSUE TITLE
Which Boost library and gcc are supposed to use?

### ISSUE THREAD

**Issue by chenlucan** [chenshuo/muduo#197]
Can you specify the supported environment and library versions ?

- gcc version
- boost
- others

Also, is building as dynamic libraries in the TODO list? I can improve this part if needed

**Comment by chenshuo** [comment]
Use the default versions from your Linux distro, eg on Ubuntu, apt-get install libboost-dev g++.
Dynamic libraries are bad, muduo should be statically linked to your server.

**Comment by chenlucan** [comment]
yes, i'm using the default versions. 

Since modern gcc changes a lot, muduo should specify on which version gcc it has been tested on.

**Comment by chenlucan** [comment]
To the point "Dynamic libraries are bad". Can you elaborate a bit more, why it's "bad" ?

dynamic library has its own use case. Many libraries e.g. Boost provide dynamic versions.

As a library itself, it should not have assumptions on how people would be using it.

**Comment by liuluheng** [comment]
https://cloud.github.com/downloads/chenshuo/documents/CppPractice.pdf section 5 and 6.

**Comment by chenshuo** [comment]
As the author of a library, I do have assumptions on how people should use it.

**Comment by chenlucan** [comment]
@liuluheng  Thanks for providing the relevant link.

@chenshuo  I have no doubt you're the owner. I'm questioning the "assumptions" part, not the "author". Thanks for sharing anyway.
