### ISSUE TITLE
too many close_wait on aliyun ecs

### ISSUE THREAD

**Issue by woodlgz** [chenshuo/muduo#198]
Hi,Shuo Chen,I am glad you share this project with the community and I have to say muduo is greate work.
I am currently working on a project in which I am using muduo to build a httpserver on Aliyun ECS.
but it worked not perfectly as I once expected .The problem is that after running for a while,  a bunch of close_wait was generated consuming the system resources,assumingly due to memory leak of TcpConnection?The code in my project is just as simple as the case in http_test demo of muduo.
Sincerely look forward to your response,and any other willing to help is welcome.

**Comment by chenshuo** [comment]
close_wait means you did not close the connection. Did you keep TcpConnectionPtr somewhere ?

**Comment by woodlgz** [comment]
Negative.I am still working on that.
Following is some code snippet from my project.

void onRequest(const HttpRequest& req, HttpResponse* resp)
{
    try{
        if (req.path() == "/v"||req.path()=="/s")
        {
            ParamMap paramMap;
            protocol::log::LogItem log;
            resp->setStatusCode(HttpResponse::k200Ok);
            commonLogic(paramMap,log,req,*resp,protocol::log::LogPhaseType::SHOW);
            bool needLog = true;
            showLogic(paramMap,log,*resp,needLog);
            if(needLog)
                doLog(log);
        }
        else if (req.path() == "/c")
        {
            ParamMap paramMap;
            protocol::log::LogItem log;
            resp->setStatusCode(HttpResponse::k200Ok);
            commonLogic(paramMap,log,req,*resp,protocol::log::LogPhaseType::CLICK);
            clickLogic(paramMap,log,*resp);
            doLog(log);
        }else if (req.path() == "/jt.html")
        {
            resp->setStatusCode(HttpResponse::k200Ok);
        }
        else
        {
            resp->setStatusCode(HttpResponse::k404NotFound);
            resp->setStatusMessage("Not Found");
            resp->setCloseConnection(true);
        }
    }catch(std::exception& e){
        resp->setStatusCode(HttpResponse::k500ServerError);
        resp->setStatusMessage("error");
        resp->setContentType("text/html");
        resp->setCloseConnection(true);
    }
}

int main(int argc, char* argv[])
{
    ConfigManager::init();
    configManager = &(ConfigManager::getInstance());
    ServerConfig* serverConfig = (ServerConfig*)configManager->get(CONFIG_SERVICE);
    int httpThreads = serverConfig->coreHttpThreads;
    int port = serverConfig->corePort;
    setLogLevel(serverConfig->loggingLevel);

    LogConfig* logConfig = (LogConfig*)configManager->get(CONFIG_LOG);
    serviceLogger = LogPusher::getLogger(SERVICE_LOGGER,
                                                         logConfig->loggerThreads,
                                                         !logConfig->logRemote);
    serviceLogger->start();

    loadShowTemplates();

    EventLoop loop;
    HttpServer server(&loop, InetAddress(port), "server test");
    server.setHttpCallback(onRequest);
    server.setThreadNum(httpThreads);
    server.start();
    loop.loop();
    AdSelectManager::release();
    ThreadLocalManager::getInstance().destroy();
    ConfigManager::exit();
}

**Comment by chenshuo** [comment]
1. if you can reproduce the issue with muduo's http server example, then it's a bug of muduo, otherwise, it's a bug of your code.
2. the code snippets that you gave is helpless to solve the issue.
3. muduo is not design to work with exceptions.

**Comment by woodlgz** [comment]
So it is possible to have close_wait unhandled even if I did not touch any TcpConnectionPtr?
More werid thing is that it works well when I use ab (from httpd toolset) starting 2000 concurrent connections to simulate load pressure while under production senario we did not even confront with that much concurrency.

**Comment by giantchen** [comment]
1. Can you reproduce the issue with muduo's http server example? If yes, show me the steps.
2. If not, provide a SSCCE (sscce.org) that reproduces the issue.
3. Otherwise, I cannot help by just talking.

**Comment by chenshuo** [comment]
1. Can you reproduce the issue with muduo's http server example? If yes, show me the steps.
2. If not, provide a SSCCE (sscce.org) that reproduces the issue.
3. Otherwise, I cannot help by just talking or speculating.

**Comment by woodlgz** [comment]
Fixed the problem with fastcgi implementation.Again,greate work.
