### ISSUE TITLE
非常容易出现PIPE错误

### ISSUE THREAD

**Issue by ituncle** [chenshuo/muduo#201]
用muduo库写了一个非常简单的echo server，然后向server快速发一段数据，发完立马close client。
也就是说，client只管发不管收，但并没有禁止收，只是不给client时间去接收。
这时候，server非常容易出现PIPE错误。
查了下，问题出在sendInLoop里面。
原因是，这个sendInLoop并不等到有writable事件再去写。
而是：只要server里面的某个线程调用了TcpConnection::send，就立马把该write动作追加到loop的pendingFunctors_队列里，在下次loop唤醒的时候就会尝试write，但这时候并不一定有writable事件，更极端的，可能有REST事件，但loop还是会义无反顾的去write，于是就pipe了。

sendInLoop这样用是不是没处理好？

**Comment by yedf** [comment]
你应当注册SIGPIPE信号的处理函数

**Comment by ituncle** [comment]
@yedf 
我知道应该加SIGPIPE信号处理，并且muduo本身已经加了。

我提的是，有bug会错误地导致频繁的PIPE信号。

**Comment by ituncle** [comment]
@yedf @chenshuo 
> 20160531 17:56:41.670153 10639 TRACE onConnection() --- accept a new connection from 127.0.0.1:50693 - FtTcpServer.h:79
20160531 17:56:41.678607 10639 INFO  onWriteComplete() --- send data completely to 127.0.0.1:50693 - FtTcpServer.h:94
20160531 17:56:41.685211 10639 ERROR handleError() --- TcpConnection::handleError [echo-0.0.0.0:8888#2] - SO_ERROR = 104 Connection reset by peer - TcpConnection.cc:361
20160531 17:56:41.685624 10639 INFO  onWriteComplete() --- send data completely to 127.0.0.1:50693 - FtTcpServer.h:94
20160531 17:56:41.685672 10639 INFO  onWriteComplete() --- send data completely to 127.0.0.1:50693 - FtTcpServer.h:94
20160531 17:56:41.685687 10639 INFO  onWriteComplete() --- send data completely to 127.0.0.1:50693 - FtTcpServer.h:94
20160531 17:56:41.685701 10639 INFO  onWriteComplete() --- send data completely to 127.0.0.1:50693 - FtTcpServer.h:94
20160531 17:56:41.685860 10639 ERROR Broken pipe (errno=32) TcpConnection::sendInLoop - TcpConnection.cc:145
20160531 17:56:41.685993 10639 ERROR Broken pipe (errno=32) TcpConnection::sendInLoop - TcpConnection.cc:145
20160531 17:56:41.686141 10639 ERROR Broken pipe (errno=32) TcpConnection::sendInLoop - TcpConnection.cc:145
20160531 17:56:41.687416 10639 TRACE onConnection() --- the connection from 127.0.0.1:50693 disconnect - FtTcpServer.h:81
20160531 17:56:41.687494 10639 WARN  sendInLoop() --- disconnected, give up writing - TcpConnection.cc:129

这是错误日志，在sendInLoop前面，poller已经发现了Connection reset by peer错误，但是后面仍然闷着头继续发。完全可以弄个flag什么的标记一下，阻止后续继续发啊。

**Comment by chenshuo** [comment]
“频繁的PIPE信号”有什么问题？是否影响了软件的正确性？
“阻止后续继续发”有什么好处？除了少一些 error message？

**Comment by ituncle** [comment]
没影响正确性。
这样想也对。。毕竟只有在特定的情况下才会出现。。
不知道这算不算是一个“瑕疵”呢。。如果能在不影响总体性能的基础上优化掉就就更好了。。
最后，感谢分享muduo，个人觉得很不错~~

**Comment by chenshuo** [comment]
出现这个error，是因为server想发数据却发送失败。这有可能是client程序有bug，或者网络出了故障。
如果你把它“优化掉”，其实是掩盖了错误，到时候真的遇到server数据发送失败，查起来就麻烦多了。
