### ISSUE TITLE
关于日志库的锁机制的一点想法

### ISSUE THREAD

**Issue by ituncle** [chenshuo/muduo#205]
我看到muduo的日志库可以在线程安全和线程不安全中做出选择，一般多线程程序肯定就得选线程安全的版本吧。
而线程安全是通过mutex来实现的，我想是不是用CAS更好一些呢，原因如下：
1、CAS是硬件提供的同步机制，更高效
2、信号安全，可重入
这两点优点非常值得关注吧，特别是第二点我更期待，用CAS的话就能在信号句柄中自由自在地写日志了。
CAS还有其它的优点，比如不会死锁。

我想问下，从整个系统的设计来说，将日志库的mutex改成CAS除了开发难度大一些之外，会不会造成隐含的问题？

**Comment by chenshuo** [comment]
你先把日志库改用CAS实现，我们看到代码再来讨论。

**Comment by ituncle** [comment]
`Log(msg) {
	static int lock = 1;
	while (!CAS(&lock, 1, 0)) {}
	Write(msg);
	CAS(&lock, 0, 1);
}`
核心代码类似这样的，可以吗？

**Comment by chenshuo** [comment]
你的做法跟 spin lock 有什么区别？
为什么你认为这种做法比 mutex 更好？有没有数据支持你的观点？

**Comment by ituncle** [comment]
暂时没有数据支持。仅仅是理论上的。
最重要的是，这种做法是可重入的，在信号句柄里可以随意的写日志啊，这岂不是很爽。。

**Comment by chenshuo** [comment]
首先，你的做法不是可重入的。

如果在 Write() 执行期间进入 signal handler，那么 signal handler 调用 Log() 会死锁，而且是 busy-loop 死锁。进而所有调用 Log() 的线程都会死锁，耗尽 CPU 资源。没有什么比这更糟糕的了。

其次，信号句柄是错误的翻译，handle 和 handler 是两个词。

**Comment by ituncle** [comment]
确实。。我说的这种是错的。。受教了~~
