### ISSUE TITLE
请教下日志格式

### ISSUE THREAD

**Issue by liubotao** [chenshuo/muduo#206]
在muduo中,日志定义和使用格式如下
` LOG_TRACE << conn->name() << " recv " << msg.size() << " bytes at " << time.toString();`

在平常的C++基础库中,日志库都习惯定义成这样
`log_error("profiler disabled by default, threshold has been set to %d", profiler_threshold);`

在JAVA程序中，一般也习惯用
` log.info("progress : {} {}", handler1.meter().count(), handler2 .meter().count());`

muduo的log是诸多的<<拼接起来,这样就切割了一个完整的句子,在阅读维护过程中相比普通日志阅读流畅度会有降低。

想请教下,项目中如果想使用muduo网络库,但是不想在同一套系统里面维护二个log库,需要怎么处理呢？

**Comment by zieckey** [comment]
可以基于muduo的log自己实现一套C的`printf`形式的接口，应该也不难。

**Comment by v2hack** [comment]
用C封装rsyslog的接口不成吗？还简单，只要自己定义格式就可以了


nanye@peersafe.cn
 
发件人： zieckey
发送时间： 2016-06-14 15:52
收件人： chenshuo/muduo
主题： Re: [chenshuo/muduo] 请教下日志格式 (#206)
可以基于muduo的log自己实现一套C的printf形式的接口，应该也不难。

**Comment by yedf** [comment]
leveldb里面的日志系统是c的printf风格，很简洁的，可以参考

**Comment by chenshuo** [comment]
要支持 string，不想每次都 .c_str()，用 << 是最方便的。
