### ISSUE TITLE
CountDownLatch读取count是否一定要加锁？

### ISSUE THREAD

**Issue by zxylvlp** [chenshuo/muduo#211]
https://github.com/chenshuo/muduo/blob/master/muduo/base/CountDownLatch.cc#L38
这一行在读count的时候不加锁是不是也可以？只要ACCESS_ONCE一下就好了？

**Comment by chenshuo** [comment]
一定要加锁。

**Comment by foobar** [comment]
Would you mind elaborating more on why the locking is needed?
It looks safe unless reading `count` is not atomic, say, the machine WORD size is less than sizeof(int).

**Comment by chenshuo** [comment]
Try your favorite thread checker.
