### ISSUE TITLE
定时器小逻辑

### ISSUE THREAD

**Issue by SmallXing** [chenshuo/muduo#212]
void TimerQueue::cancelInLoop(TimerId timerId)
{
  loop_->assertInLoopThread();
  assert(timers_.size() == activeTimers_.size());
  ActiveTimer timer(timerId.timer_, timerId.sequence_);
  ActiveTimerSet::iterator it = activeTimers_.find(timer);
  if (it != activeTimers_.end())**// ------------------ 此处有可能也处于  callingExpiredTimers_==true的状态**
  {
    size_t n = timers_.erase(Entry(it->first->expiration(), it->first));
    assert(n == 1); (void)n;
    delete it->first; // FIXME: no delete please
    activeTimers_.erase(it);
  }
  else if (callingExpiredTimers_)
  {
    cancelingTimers_.insert(timer);
  }
  assert(timers_.size() == activeTimers_.size());
}

**Comment by chenshuo** [comment]
So what?

**Comment by SmallXing** [comment]
if (it != activeTimers_.end() **&& !callingExpiredTimers_**)
{
size_t n = timers_.erase(Entry(it->first->expiration(), it->first));
assert(n == 1); (void)n;
delete it->first; // FIXME: no delete please
activeTimers_.erase(it);
}

**Comment by chenshuo** [comment]
你的改动是错的。

**Comment by SmallXing** [comment]
恕我愚钝，现在都没察觉

**Comment by chenshuo** [comment]
首先，你认为原来的代码有什么问题？会造成什么后果？能不能用代码（test case）证明你的观点？

**Comment by SmallXing** [comment]
确实是我的的错误，谢谢
