### ISSUE TITLE
muduo link faild

### ISSUE THREAD

**Issue by MironWong** [chenshuo/muduo#213]
i have installed  muduo secceed, including the test example . While i want to compile the example code by myself, it runs error. The code is in the  muduo/examples/simple/echo 

[root@localhost echo]# g++ ./main.cc   -L/home/git_code/build/release-install/lib   
-lmuduo_base  -lmuduo_net
In file included from ./main.cc:1:0:
./echo.h:4:23: fatal error: TcpServer.h: No such file or directory
 #include "TcpServer.h"

env:
muduo Version :1.0.8 .
CentOS Linux release 7.2.1511 (Core)
[root@localhost echo]# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by MironWong** [comment]
i change the include in echo.h from #include <muduo/net/TcpServer.h> to  #include<TcpServer.h> , it all runs errors.

**Comment by chenshuo** [comment]
g++ -I/home/git_code/build/release-install/include

**Comment by MironWong** [comment]
thx. it runs well.
