### ISSUE TITLE
channel的handleEvent处理事件用if是否有问题

### ISSUE THREAD

**Issue by 1suming** [chenshuo/muduo#214]
在handleEvent函数中，如下：
 
void Channel::handleEventWithGuard(Timestamp receiveTime)
{
  eventHandling_ = true;
 ......
  if (revents_ & (POLLERR | POLLNVAL))
  {
    if (errorCallback_) errorCallback_();
  }
  if (revents_ & (POLLIN | POLLPRI | POLLRDHUP))
  {
    if (readCallback_) readCallback_(receiveTime);
  }
 
epoll中，POLLIN,POLLOUT,POLLERR这3个事件可能同时到达，如果有pollerr ,用if 会往下继续执行pollin
这样会造成读错误。

**Comment by chenshuo** [comment]
代码没有错误，能正确处理你说的情况，你去看看errorCallback_的内容就知道了，就算没有errorCallback_也不影响正确性。
