### ISSUE TITLE
Some doubt about TcpServer dctor

### ISSUE THREAD

**Issue by JackDrogon** [chenshuo/muduo#216]
Why was TcpServer dctor written like that

``` cpp
TcpConnectionPtr conn = it->second;
it->second.reset();
conn->getLoop()->runInLoop(
    boost::bind(&TcpConnection::connectDestroyed, conn));
conn.reset();
```

not

```
conn->getLoop()->runInLoop(
    boost::bind(&TcpConnection::connectDestroyed, conn));
it->second.reset();
```

Avoid for TcpConnection::connectDestroyed unsuccessfully casuing TcpConnection leak?

**Comment by feixintianxia** [comment]
TcpConnection::connectDestroyed must be  executed  before TcpServer dctor。So, you need keep the conn    
 alive. :+1:
