### ISSUE TITLE
Mac 使用muduo库失败

### ISSUE THREAD

**Issue by xiaofannn** [chenshuo/muduo#218]
环境：
   muduo version: MAC branch
   将mac 编译出来的 release-install分别copy 到 /usr/local/include/ /usr/local/lib. 而后编写一个简单的echo server。

error info:
➜  learn_muduo make
clang++  main.cpp -o echoserver  -lmuduo_net -lmuduo_base  -v \
	-g -DMUDUO_STD_STRING -D_FILE_OFFSET_BITS=64 -Wall -Wextra -Wconversion -Wno-unused-parameter -Wno-sign-conversion -Wold-style-cast -Woverloaded-virtual \
	-Wpointer-arith -Wshadow -Wwrite-strings -march=native -O2 -DNDEBUG
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -disable-llvm-verifier -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu broadwell -target-feature -sse4a -target-feature -avx512bw -target-feature +cx16 -target-feature -tbm -target-feature +xsave -target-feature -fma4 -target-feature -avx512vl -target-feature +prfchw -target-feature +bmi2 -target-feature +adx -target-feature -xsavec -target-feature +fsgsbase -target-feature +avx -target-feature -avx512cd -target-feature -avx512pf -target-feature -rtm -target-feature +popcnt -target-feature +fma -target-feature +bmi -target-feature +aes -target-feature +rdrnd -target-feature -xsaves -target-feature +sse4.1 -target-feature +sse4.2 -target-feature +avx2 -target-feature -avx512er -target-feature +sse -target-feature +lzcnt -target-feature +pclmul -target-feature -avx512f -target-feature +f16c -target-feature +ssse3 -target-feature +mmx -target-feature +cmov -target-feature -xop -target-feature +rdseed -target-feature +movbe -target-feature -hle -target-feature +xsaveopt -target-feature -sha -target-feature +sse2 -target-feature +sse3 -target-feature -avx512dq -target-linker-version 264.3.102 -v -dwarf-column-info -debug-info-kind=standalone -dwarf-version=2 -resource-dir /Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.3.0 -D MUDUO_STD_STRING -D _FILE_OFFSET_BITS=64 -D NDEBUG -stdlib=libc++ -O2 -Wall -Wextra -Wconversion -Wno-unused-parameter -Wno-sign-conversion -Wold-style-cast -Woverloaded-virtual -Wpointer-arith -Wshadow -Wwrite-strings -fdeprecated-macro -fdebug-compilation-dir /Users/xiaofan/study/c++/learn_muduo -ferror-limit 19 -fmessage-length 80 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /var/folders/02/fz78n55j1d3ftlcr00vw6lnm0000gn/T/main-62a324.o -x c++ main.cpp
clang -cc1 version 7.3.0 (clang-703.0.31) default target x86_64-apple-darwin15.6.0
ignoring nonexistent directory "/usr/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.3.0/include
 /Library/Developer/CommandLineTools/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.11.0 -o echoserver /var/folders/02/fz78n55j1d3ftlcr00vw6lnm0000gn/T/main-62a324.o -lmuduo_net -lmuduo_base -lc++ -lSystem /Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.3.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "EchoServer::start()", referenced from:
      _main in main-62a324.o
  "EchoServer::EchoServer(muduo::net::EventLoop*, muduo::net::InetAddress const&)", referenced from:
      _main in main-62a324.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [echoserver] Error 1

**Comment by chenshuo** [comment]
你的 main.cpp 里有 EchoServer 的实现吗？

**Comment by xiaofannn** [comment]
makefile  忘记cpp 加进去了。。。
