### ISSUE TITLE
是否应当去除singleton.h中的atexit ?  测试出现coredump

### ISSUE THREAD

**Issue by cloudusers** [chenshuo/muduo#221]
[PackageExtractor.cpp.txt](https://github.com/chenshuo/muduo/files/421735/PackageExtractor.cpp.txt)
[Uploading PackageExtractor.h.txt…]()
[Uploading singleton.h.txt…]()
![Uploading stack.jpg…]()
[core_test.cpp.txt](https://github.com/chenshuo/muduo/files/421736/core_test.cpp.txt)

core_test.cpp
（1）pthread_detach换成pthread_join
（2）SignHandler直接调用exit(0)

**Comment by chenshuo** [comment]
如果去掉，那么 Singleton 何时释放？
你可以用 no_destroy 来避免析构。

**Comment by cloudusers** [comment]
多谢回复
我明白你的意思，我意思是这个atexit注册的函数被调用时一定是在对应的进程退出时让他做些清理，进程都退了内存OS应该会回收这块内存，所以我个人觉得不需要这个atexit做回收动作

另一方面，这个singleton应该是在全局静态段中， 因为类中（比如类PackageExtractor）可能会使用栈上空间， 而atexit调用的退出时即栈上可能是个突然被修改的内容导致对应析构时出现问题
运行测试时有时发生有时不发生core个人觉得栈上的数据有时是否被修改引起

可能个人理解的不对，还请指教 :)

**Comment by cloudusers** [comment]
多谢回复，我明白你意思，
（1）定义了no_destroy后就不会调用atexit对应的销毁函数，这个没问题
（2）不定义no_destroy的话如果使用atexit注册的销毁函数就可能存在问题（如下是疑问，不知道理解的对不对，这也正是发题询问是否直接去除atexit的原因）
还请帮解答： 
因为singleton中的value是static的，如果当用户程序中手动调用exit退出时（比如将exit放入信号处理函数中时），因为exit手册中对behavior进行了说明，即objects with static storage duration are destroyed and functions registered by calling atexit are called....
所以真正执行atexit对应的析构时可能内存中的数据或指针被破坏从而导至在exit退出时由于析构而使程序操作非法内存

所以我的理解是不需要加入对应的atexit完成销毁逻辑， 本身有这个动作的时候说明进程退了从而占用的内存也会自动被回收，反而加这个逻辑的话就要求使用者必须要定义一个no_destroy来进行释放（即指明不用atexit）
【我现在只能程序中加一个没有任何操作的no_destroy空函数让他不使用atexit功能来避免程序退出时出现非法内存访问】

**Comment by cloudusers** [comment]
PS：
在core_test.cpp中复现
（1）pthread_detach换成pthread_join
（2）SignHandler直接调用exit(0)

**Comment by chenshuo** [comment]
你认为 Singleton 应该默认不释放内存，除非特殊指明。
我认为 Singleton 应该默认释放内存，除非特殊指明。
