### ISSUE TITLE
请问几个问题，

### ISSUE THREAD

**Issue by githublaohu** [chenshuo/muduo#224]
与在QQ群聊的时候。
对 mudou的评价是
他那个库 还有很多不完善的地方 要在实际项目中应用感觉 还有待时机 目前成功的大项目应该用的也不多
 
Muduo  说白了 本身就是参考ACE的设计实现的 只是去掉了跨平台而已 有很多东西也不完善

感觉muduo的文档的确很少。

在博览上订阅了，网络编程的课程。静待 大师。解读 muduo。

**Comment by lsytj0413** [comment]
不太明白你到底想说明什么。
针对muduo, @chenshuo 有一本出版的书进行过具体的讲解。

**Comment by Yrp** [comment]
能否将不完善的地方说清楚

2016年8月31日星期三，pine yang <notifications@github.com> 写道：

**Comment by chenshuo** [comment]
你认为完善的、大项目用得多的、文档丰富的网络库有哪些？

**Comment by githublaohu** [comment]
1,libevent2 
2,Boost.Asio
这两个库在网络的教程，还是很多的。
boost方面还有书籍，虽然对asio说的不多。

很多redis使用者一致建议作者 使用libevent2，但是为了让redis无依赖，一直没有使用

ace的确真心，头疼。各种不友好。
但是 腾讯，华为使用了很多年了。各种文档还是比较多的。 

Linux 多线程服务端编程：使用 muduo C++ 网络库，我在13年已经购买，今年是16年了。不知道有多少变化。。。

**Comment by chenshuo** [comment]
既然你找到了你认为好用的网络库，那就用它们好了。

**Comment by zieckey** [comment]
@githublaohu 你说的那几个库也都是成熟的库，应用起来没有问题。但muduo与他们相比，都有优缺点吧。

libevent1.4 和2.0 目前用起来应该是最多也是最广泛，但其相对来说还是较为底层，对C++程序员来说不够友好。它也没有线程池概念。
asio 相对来说较为复杂，不容易掌握，整体性能与libevent也有一定的差距。
muduo虽然说较为年轻，但其设计目标就是现代C++编程模式，接口很友好，性能与libevent相当，有线程池。如果是一个独立的项目，推荐尝试一下使用muduo；如果是大项目，且其他组件对libevent有依赖的话，可能libevent更合适。

**Comment by githublaohu** [comment]
@zieckey  现在的确想使用 mudou，对开发的确太友好了，然后符合 c++的编程规范。
使用 ace 真他的那难受。


主要问题是，mudou文档比较少，使用者少，头疼的问题。
还有的问题是，自己c++功底差，英语非常不好。

努力克服这些问题吧。
直接引用 mudou 真舒服，正如 使用 muduo C++ 网络库  里面说的，静态链接，动态链接，比如 直接引用。

**Comment by zieckey** [comment]
@githublaohu muduo代码相对来说比libevent、asio、ace等还是要简单很多。文档不多，请看muduo作者自己写的书  《Linux多线程服务端编程：使用muduo C++网络库(写给每一位C++程序员，功力为证，集编程思想、经验之大成)》 http://product.dangdang.com/23162953.html 。这本书不仅仅是介绍muduo的实现本身，还介绍了很多C++方面的编程实践，非常值得一读。

其实还是应该花时间看看源码，如果出现问题，不知道源码实现的话，也是很头疼的。

**Comment by githublaohu** [comment]
@zieckey  《Linux多线程服务端编程：使用muduo C++网络库(写给每一位C++程序员，功力为证，集编程思想、经验之大成)》
这本书，2013年就买了，每年都读一，两篇，是很精辟，很好。每次都有收获。
感觉有点难懂，反复读，
承认，我是一名主攻java（也是自学）自学c++的高中生，看起来好费劲 ，尤其是c++方面基础实践。
算是一个建议，大师，的确集 c++ 方面大成，不管是 书籍，文章，视频，都很精辟，但是难懂。

努力吧，哈哈。

**Comment by wangxiaofei6485** [comment]
您好，
向您请教一个问题：我们之前的公司的项目比较大，采用的DDD的方式来封装C++代码，大家都是用封装后的宏来做开发。Muduo多采用组合的方式来定义类，较少用模板等，我个人也比较喜欢这个方式。但是有点疑问：大型项目里，该用哪种方式？如何来选择基于哪种方式来开发呢？
谢谢！
