### ISSUE TITLE
在mac上

### ISSUE THREAD

**Issue by hi-jimmee** [chenshuo/muduo#227]
我用的是mac的Darwin Kernel Version 14.1.0版本，按例子编写EchoServer， 编译出现：

g++  -o "test"  ./src/test.o   -lc++ -lpthread -lboost_system -lmuduo_base -lmuduo_net
Undefined symbols for architecture x86_64:
  "muduo::net::TcpServer::TcpServer(muduo::net::EventLoop*, muduo::net::InetAddress const&, __gnu_cxx::__versa_string<char, std::char_traits<char>, std::allocator<char>, __gnu_cxx::__sso_string_base> const&, muduo::net::TcpServer::Option)", referenced from:
      EchoServer::EchoServer(muduo::net::EventLoop*, muduo::net::InetAddress const&) in test.o
      EchoServer::EchoServer(muduo::net::EventLoop*, muduo::net::InetAddress const&) in test.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [test] Error 1

是什么问题呀

**Comment by chenshuo** [comment]
MAC is not supported, use Linux please.
