### ISSUE TITLE
TimerQueue的问题

### ISSUE THREAD

**Issue by guojunhong** [chenshuo/muduo#229]
1）测试代码：在runAfter,runEvery中调用cancel（虽然这样调用没什么意义）
void cancelSelf()
{
  printf("cancelSelf\n");
  g_loop->cancel(toCancel);  
}

 toCancel = loop.runAfter(2, cancelSelf);

2）TimerQueue.cc源码
TimerQueue::cancelInLoop     cancelingTimers_.insert(timer);
TimerQueue::handleRead         cancelingTimers_.clear();

3）问题
如果没有下次定时器超时，cancelingTimers_将一直保存一个ActiveTimer对象。

**Comment by chenshuo** [comment]
有什么问题？
