### ISSUE TITLE
请问发送的时候，如果历史数据没发完，为什么不尝试直接发送它呢？

### ISSUE THREAD

**Issue by ituncle** [chenshuo/muduo#233]
原代码见：https://github.com/chenshuo/muduo/blob/master/muduo/net/TcpConnection.cc#L151

```
// if no thing in output queue, try writing directly
  if (!channel_->isWriting() && outputBuffer_.readableBytes() == 0)
```

这里为什么只有当 "outputBuffer_.readableBytes() == 0" 时，才尝试发送呢？
为什么不这样呢：
先判断 outputBuffer_ 是否为空，不为空，发送之，直到为空或遇到阻塞错误；
如果发完了 outputBuffer_ 且没有遇到阻塞错误，就尝试发送 data，直到全部发出去或遇到阻塞错误；

请教，谢谢~~

**Comment by zhoudayang** [comment]
这两个条件同时满足吧？

**Comment by chenshuo** [comment]
首先，你说的做法有什么好处？你可以试验一下你的想法，看看有多少机会能成功发送数据。
