### ISSUE TITLE
muduo epoll 为什么使用默认的 LT 模式？ 

### ISSUE THREAD

**Issue by yjhjstz** [chenshuo/muduo#234]
ET 性能高于 LT，为什么不考虑呢？或者说您是怎样想的？

**Comment by chenshuo** [comment]
书第 206 页。
另外，”ET 性能高于 LT“是你听说的还是实测的？

**Comment by yjhjstz** [comment]
谢谢, nginx 用了 ET。

**Comment by chenshuo** [comment]
你可以试试把 nginx 改成 LT ，看看性能有无变化，估计只需要改一行代码。

**Comment by ygm521** [comment]
每次提问，都是无结果。 强烈推荐国内openresty!!
