### ISSUE TITLE
compile question using build.sh

### ISSUE THREAD

**Issue by pzz2011** [chenshuo/muduo#235]
I hava found the answer in google, while don't find the proper answer.
I have a confusion on the command  `make $*` in the build.sh .
Hope to receive your reply if you have see this issue. Thanks here.

**Comment by chenshuo** [comment]
What's the question?

**Comment by pzz2011** [comment]
I have a confusion on the command make $* in the build.sh .
It seems that $* has no effect at all in muduo.

and I found that after I execute build.sh in the root folder of muduo, I just found `build` folder in the parent folder of muduo root folder, and the INSTALL_DIR `release-install`

**Comment by chenshuo** [comment]
./build.sh install

**Comment by pzz2011** [comment]
thanks.
