### ISSUE TITLE
boost revision used in muduo

### ISSUE THREAD

**Issue by eyauwag** [chenshuo/muduo#238]
Hi chensuo, What's the boost revision used in muduo currently?

**Comment by ygm521** [comment]
我使用的60和53， “限制连接数目和踢掉空闲连接综合下， 测试限制连接数目”， 结果挂了。

**Comment by ygm521** [comment]
我使用的是main ractor+many sub ractor+ thread pool模式处理的，且结合了bucket剔除空闲连接和限制连接数目。目的，测试连接数限制是否可用，但是结果挂了，如下：
exception caught in Thread subEventThPool1
reason: boost::bad_any_cast: failed conversion using boost::any_cast
已放弃(吐核)

调试：
Program terminated with signal 6, Aborted.
#0 0x00007fcabb03b5f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56 return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) bt
#0 0x00007fcabb03b5f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1 0x00007fcabb03cce8 in GI_abort () at abort.c:90
#2 0x0000000000447626 in runInThread (this=0x1d83ff0) at /home/wbq/muduo-master/muduo/base/Thread.cpp:103
#3 muduo::detail::startThread (obj=0x1d83ff0) at /home/wbq/muduo-master/muduo/base/Thread.cpp:126
#4 0x00007fcabc161dc5 in start_thread (arg=0x7fcab5f91700) at pthread_create.c:308
#5 0x00007fcabb0fcced in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
**死到onStringMessage函数了， solve中没办法使用非静态成员connectionBuckets**。
void SudokuServer::onStringMessage(const TcpConnectionPtr& conn, const string& message, Timestamp)
{
processRequest(conn, message);
assert(!conn->getContext().empty());
WeakEntryPtr weakEntry(boost::any_cast(conn->getContext()));
EntryPtr entry(weakEntry.lock());
if (entry) {
connectionBuckets.back().insert(entry);
}
}
void SudokuServer::solve(const TcpConnectionPtr& conn,
const string& request)
{
muduo::net::Buffer buf;
buf.append("hello");
int32_t len = static_cast<int32_t>(strlen("hello"));
int32_t be32 = muduo::net::sockets::hostToNetwork32(len);
buf.prepend(&be32, sizeof be32);
conn->send(&buf);
}

void SudokuServer::processRequest(const TcpConnectionPtr& conn, const string& request)
{
threadPool_.run(boost::bind(&solve, conn, request));
}

加锁也不好使。
if (mutex_){
MutexLockGuard lock(*mutex_);
connectionBuckets_.back().insert(entry);
}

**Comment by chenshuo** [comment]
The version comes with your OS, eg. apt-get install libboost-dev

**Comment by ygm521** [comment]
boost 51
