### ISSUE TITLE
异步日志没有使用吗？

### ISSUE THREAD

**Issue by oyld** [chenshuo/muduo#242]
我看就在测试代码中使用了异步日志，没有在muduo库中使用啊？

**Comment by ygm521** [comment]
每次提问，都是无结果。 强烈推荐国内openresty!!

**Comment by chenshuo** [comment]
你可以根据需要在自己的程序中用异步日志。
muduo 库只使用日志库的前端（LOG_INFO 等宏），它不管日志是写到控制台还是文件。
