### ISSUE TITLE
归并多台后端回复结果，框架请教？

### ISSUE THREAD

**Issue by ygm521** [chenshuo/muduo#244]
陈哥， 您好！
       我现在想使用muduo作为代理， 一个客户端请求时muduo构造请求给后端多台服务器， 当后端服务器全部或者部分返回数据后，muduo对结果做处理再回复给客户端。 我现在能想到的是：第一种， 客户端请求到时候，创建一个select且设置超时时间， 新建多个socket加入select中，访问后端服务器，等待结果回复客户端。 假设后端有一台服务器没有回复，则异常判断靠select超时保证的。 
不知道您有什么好的办法，推荐下，非常感谢！

**Comment by zieckey** [comment]
muduo 有 TcpClient，可以用这个来连接后端服务器，并且TcpClient都放到EventLoop中，设置好定时器，就可以完成你说的超时管理了

**Comment by ygm521** [comment]
说的太笼统了，还是不明白。

**Comment by chenshuo** [comment]
你这个需求适合用 Go 来实现。

**Comment by ygm521** [comment]
Go是什么呀？ 可以和muduo结合使用？

**Comment by zieckey** [comment]
Golang是Google出的一门新的适合网络编程的语言，简称Go。

**Comment by ygm521** [comment]
muduo main event loop+many sub event loop + thread pool 模式， 如何处理这种问题呢？ 陈哥， 请耐心指点指点，谢谢！ 看中muduo， 但是目前束手无策。

**Comment by ygm521** [comment]
阿里 使用nginx+lua 或者 nginx+子请求实现此功能。

**Comment by chenshuo** [comment]
我建议你先定一个小一点的目标：用单线程 EventLoop 实现你的需求。
在正确实现之后，如果发现性能瓶颈在 CPU，再考虑多线程并行处理。

**Comment by ygm521** [comment]
每次提问，都是无结果。 强烈推荐国内openresty!!
