### ISSUE TITLE
TcpConnection的setContext和getContext的线程安全性问题

### ISSUE THREAD

**Issue by fdxuwei** [chenshuo/muduo#245]
我的场景是，TcpServer里面，子线程执行onConnection，在onConnection里面setContex
，主线程对所有tcp连接做一些统计，需要getContext，此时如果正在setContext，就会冲突。我的想法是在TcpConnection里面加个原子变量hasContext_来表示是否setContext完毕，请问是否有更好的办法？

**Comment by chenshuo** [comment]
首先，你的做法是错的，应该用mutex 。
另外，我认为你误用了 context ，context 应该看作连接的private 数据，只在 onMessage 和 onConnection 里访问。
