### ISSUE TITLE
程序运行报错：Illegal instruction

### ISSUE THREAD

**Issue by arhlong** [chenshuo/muduo#248]
程序运行报错：Illegal instruction

用GDB查看core文件，bt如下：
#0  0x00000000004f7759 in muduo::LogFile::getLogFileName(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long*) () at /usr/local/include/c++/4.8.5/bits/char_traits.h:259
#1  0x00000000004f78e6 in muduo::LogFile::rollFile() () at /home/suyl/project/muduo-1.0.9/muduo/base/LogFile.cc:93
#2  0x00000000004f7cb6 in muduo::LogFile::LogFile(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, bool, int, int) () at /home/suyl/project/muduo-1.0.9/muduo/base/LogFile.cc:28
#3  0x00000000004f6a1b in muduo::AsyncLogging::threadFunc() () at /home/suyl/project/muduo-1.0.9/muduo/base/AsyncLogging.cc:57
#4  0x00000000004fc79a in muduo::detail::startThread(void*) () at /usr/local/include/boost/function/function_template.hpp:771
#5  0x0000003d168079d1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003d164e89dd in clone () from /lib64/libc.so.6

请问有遇到过吗？怎么解决？

注：编译选项使用了-DMUDUO_STD_STRING

**Comment by chenshuo** [comment]
Search "Illegal" you will find: #111 #169 #177
