### ISSUE TITLE
开一个微信讨论群如何?

### ISSUE THREAD

**Issue by elithnever** [chenshuo/muduo#250]
感觉在github上讨论问题效率比较低, 陈老师能否考虑开设一个微信讨论群呢? 方便使用muduo的朋友们讨论和交流.

**Comment by chenshuo** [comment]
我不认为微信讨论群适合用来讨论技术问题，因为

0. 不方便贴 code，就算你在电脑上用 web 版发了代码，手机也看不清楚。
1. 没有 topic，一人一句七嘴八舌，就像菜市场、聊天室。
2. 没有 history，要找以前的讨论内容很不方便。
3. 不能 search。

讨论技术问题最好是 maillist：
https://groups.google.com/forum/#!forum/muduo-library

**Comment by elithnever** [comment]
哦, 原来有个讨论组, 谢谢
