### ISSUE TITLE
Problem in making and installing muduo

### ISSUE THREAD

**Issue by sl950313** [chenshuo/muduo#252]
Hi, I have a problem in running ./build 
My system enviroment is : x86_64 GNU/Linux 3.19.0-25-generic
And the output of ./build : 

+ pwd
+ SOURCE_DIR=/root/sl/muduo
+ BUILD_DIR=../build
+ BUILD_TYPE=release
+ INSTALL_DIR=../release-install
+ BUILD_NO_EXAMPLES=0
+ mkdir -p ../build/release
+ cd ../build/release
+ cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=../release-install -DCMAKE_BUILD_NO_EXAMPLES=0 /root/sl/muduo
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.63.0
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.35.0") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- found cares
-- found curl
-- found zlib
-- CXX_FLAGS = -g -DCHECK_PTHREAD_RETURN_VALUE -D_FILE_OFFSET_BITS=64 -Wall -Wextra -Werror -Wconversion -Wno-unused-parameter -Wold-style-cast -Woverloaded-virtual -Wpointer-arith -Wshadow -Wwrite-strings -march=native -rdynamic -O2 -finline-limit=1000 -DNDEBUG
-- Looking for accept4
-- Looking for accept4 - found
-- Configuring done
-- Generating done
-- Build files have been written to: /root/sl/build/release
+ make
Scanning dependencies of target muduo_base
[  1%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/AsyncLogging.cc.o
[  1%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Condition.cc.o
[  1%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/CountDownLatch.cc.o
[  2%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Date.cc.o
[  2%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Exception.cc.o
[  2%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/FileUtil.cc.o
[  3%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/LogFile.cc.o
[  3%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Logging.cc.o
[  3%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/LogStream.cc.o
[  4%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/ProcessInfo.cc.o
[  4%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Timestamp.cc.o
[  6%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/TimeZone.cc.o
[  6%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Thread.cc.o
[  6%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/ThreadPool.cc.o
Linking CXX static library ../../lib/libmuduo_base.a
[  6%] Built target muduo_base
Scanning dependencies of target muduo_base_cpp11
[  7%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/AsyncLogging.cc.o
[  7%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Condition.cc.o
[  7%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/CountDownLatch.cc.o
[  8%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Date.cc.o
[  8%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Exception.cc.o
[  8%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/FileUtil.cc.o
[  9%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/LogFile.cc.o
[  9%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Logging.cc.o
[ 10%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/LogStream.cc.o
[ 10%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/ProcessInfo.cc.o
[ 10%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Timestamp.cc.o
[ 12%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/TimeZone.cc.o
[ 12%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Thread.cc.o
[ 12%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/ThreadPool.cc.o
Linking CXX static library ../../lib/libmuduo_base_cpp11.a
[ 12%] Built target muduo_base_cpp11
Scanning dependencies of target asynclogging_test
[ 12%] Building CXX object muduo/base/tests/CMakeFiles/asynclogging_test.dir/AsyncLogging_test.cc.o
Linking CXX executable ../../../bin/asynclogging_test
[ 12%] Built target asynclogging_test
Scanning dependencies of target atomic_unittest
[ 13%] Building CXX object muduo/base/tests/CMakeFiles/atomic_unittest.dir/Atomic_unittest.cc.o
Linking CXX executable ../../../bin/atomic_unittest
[ 13%] Built target atomic_unittest
Scanning dependencies of target blockingqueue_bench
[ 13%] Building CXX object muduo/base/tests/CMakeFiles/blockingqueue_bench.dir/BlockingQueue_bench.cc.o
Linking CXX executable ../../../bin/blockingqueue_bench
[ 13%] Built target blockingqueue_bench
Scanning dependencies of target blockingqueue_cpp11_test
[ 14%] Building CXX object muduo/base/tests/CMakeFiles/blockingqueue_cpp11_test.dir/BlockingQueue_test.cc.o
Linking CXX executable ../../../bin/blockingqueue_cpp11_test
[ 14%] Built target blockingqueue_cpp11_test
Scanning dependencies of target blockingqueue_test
[ 14%] Building CXX object muduo/base/tests/CMakeFiles/blockingqueue_test.dir/BlockingQueue_test.cc.o
Linking CXX executable ../../../bin/blockingqueue_test
[ 14%] Built target blockingqueue_test
Scanning dependencies of target boundedblockingqueue_test
[ 15%] Building CXX object muduo/base/tests/CMakeFiles/boundedblockingqueue_test.dir/BoundedBlockingQueue_test.cc.o
Linking CXX executable ../../../bin/boundedblockingqueue_test
[ 15%] Built target boundedblockingqueue_test
Scanning dependencies of target date_unittest
[ 16%] Building CXX object muduo/base/tests/CMakeFiles/date_unittest.dir/Date_unittest.cc.o
Linking CXX executable ../../../bin/date_unittest
[ 16%] Built target date_unittest
Scanning dependencies of target exception_test
[ 16%] Building CXX object muduo/base/tests/CMakeFiles/exception_test.dir/Exception_test.cc.o
Linking CXX executable ../../../bin/exception_test
[ 16%] Built target exception_test
Scanning dependencies of target fileutil_test
[ 18%] Building CXX object muduo/base/tests/CMakeFiles/fileutil_test.dir/FileUtil_test.cc.o
Linking CXX executable ../../../bin/fileutil_test
[ 18%] Built target fileutil_test
Scanning dependencies of target fork_test
[ 18%] Building CXX object muduo/base/tests/CMakeFiles/fork_test.dir/Fork_test.cc.o
Linking CXX executable ../../../bin/fork_test
[ 18%] Built target fork_test
Scanning dependencies of target gzipfile_test
[ 18%] Building CXX object muduo/base/tests/CMakeFiles/gzipfile_test.dir/GzipFile_test.cc.o
Linking CXX executable ../../../bin/gzipfile_test
[ 18%] Built target gzipfile_test
Scanning dependencies of target logfile_test
[ 18%] Building CXX object muduo/base/tests/CMakeFiles/logfile_test.dir/LogFile_test.cc.o
Linking CXX executable ../../../bin/logfile_test
[ 18%] Built target logfile_test
Scanning dependencies of target logging_test
[ 18%] Building CXX object muduo/base/tests/CMakeFiles/logging_test.dir/Logging_test.cc.o
Linking CXX executable ../../../bin/logging_test
[ 18%] Built target logging_test
Scanning dependencies of target logstream_bench
[ 19%] Building CXX object muduo/base/tests/CMakeFiles/logstream_bench.dir/LogStream_bench.cc.o
Linking CXX executable ../../../bin/logstream_bench
[ 19%] Built target logstream_bench
Scanning dependencies of target logstream_test
[ 19%] Building CXX object muduo/base/tests/CMakeFiles/logstream_test.dir/LogStream_test.cc.o
Linking CXX executable ../../../bin/logstream_test
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, int, int>':
/usr/local/include/boost/test/tools/old/impl.hpp:92: undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, __gnu_cxx::__versa_string<char>, __gnu_cxx::__versa_string<char> >':
/usr/local/include/boost/test/tools/old/impl.hpp:92: undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `testLogStreamFloats::test_method()':
/root/sl/muduo/muduo/base/tests/LogStream_test.cc:157: undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, int, int>':
/usr/local/include/boost/test/tools/old/impl.hpp:92: undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
/usr/local/include/boost/test/tools/old/impl.hpp:92: undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)':
/usr/local/include/boost/test/tree/test_unit.hpp:249: undefined reference to `boost::unit_test::test_case::test_case(boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long, boost::function<void ()> const&)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o: In function `__static_initialization_and_destruction_0':
/root/sl/muduo/muduo/base/tests/LogStream_test.cc:13: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/root/sl/muduo/muduo/base/tests/LogStream_test.cc:26: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/root/sl/muduo/muduo/base/tests/LogStream_test.cc:43: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/root/sl/muduo/muduo/base/tests/LogStream_test.cc:113: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
/root/sl/muduo/muduo/base/tests/LogStream_test.cc:172: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
CMakeFiles/logstream_test.dir/LogStream_test.cc.o:/root/sl/muduo/muduo/base/tests/LogStream_test.cc:186: more undefined references to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [bin/logstream_test] Error 1
make[1]: *** [muduo/base/tests/CMakeFiles/logstream_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by chenshuo** [comment]
try 
`sudo apt-get install libboost-test-dev` .
