### ISSUE TITLE
建议去掉 accept 线程,accept 功能合并到IO线程

### ISSUE THREAD

**Issue by hzhxxx** [chenshuo/muduo#256]
//全局的线程之间共享变量
int listenfd = socket();
const int IO_THREAD_TOTAL = 3;
const int ONCE_ACCEPT_MAX_COUNT= 10;
std::atomic<int> accept_thread_index(0);

//线程本地变量
int accept_count = 0;
//1<=myself_thread_index<=ONCE_ACCEPT_MAX_COUNT
const int myself_thread_index = 1;

for(;;){
	int n = epoll_wait(epfd,events,maxevents,1000);
	for(int i = 0;i< n;++i){
		if(events[i].fd == listenfd){
			int newconn = -1;
			newconn = accept4(listenfd,addr,addrlen,flags);
			if(newconn >= 0){
				accept_count++;
				//do_with(newconn);
			}
			if(ONCE_ACCEPT_MAX_COUNT<= accept_count){
				//删除IO线程epoll里面的listenfd
				if(0 == epoll_ctl(epfd,EPOLL_CTL_DEL,listenfd,event)){
					//单次接收新连接满,释放权限,切换到其他IO
					//线程去接收,从1到最大,周而复始
					accept_count = 0;
                                        int next_io = myself_thread_index;
					next_io = myself_thread_index >=
					 IO_THREAD_TOTAL ? 1 : ++next_io;
					accept_thread_index.store(next_io);
				}					
			}
		}
		//处理其他epoll事件
	}
	
	if(myself_thread_index == accept_thread_index.load())
	{
		//考虑减少epoll操作次数,可以先 accept
		//newconn = accept4(listenfd,addr,addrlen,flags);

		//接管listenfd
		if(ONCE_ACCEPT_MAX_COUNT> accept_count
			&& 0 == epoll_ctl(epfd,EPOLL_CTL_ADD,listenfd,event)){
			accept_thread_index.store(INT_MAX);				
		}		
	}
}

**Comment by hzhxxx** [comment]
思路是 IO 线程合并 accept 的功能，减少 accept 接收的连接在传送一次。
1. IO 线程通过一个原子变量 atomic<int> accept_thread_index(0) 持有 listenfd,持有 listenfd 的线程可以进行accept
2. 持有 listenfd 的线程如果接进来的新连接 到达了了设定的值 const int ONCE_ACCEPT_COUNT = 10 这样就把控制权转给下一个 IO 线程，周而复始。

**Comment by chenshuo** [comment]
你直接用 SO_REUSEPORT 就行了，多个 EventLoop，每个 EventLoop 上 run 一个 TcpServer，这些 TcpServer 的线程数为 0。

**Comment by hzhxxx** [comment]
Linux kernel 3.9之前的版本，一个ip+port组合，只能被监听bind一次。这样在多核环境下，往往只能有一个线程（或者进程）是listener，在高并发情况下，往往这就是性能瓶颈。于是Linux kernel 3.9之后，Linux推出了端口重用SO_REUSEPORT选项。


linux  3.9,部分 linux 用户未能升级。

**Comment by hzhxxx** [comment]
nginx 也是支持两种配置的。

**Comment by hzhxxx** [comment]
2015-05-26	
nginx-1.9.1 mainline version has been released, with the reuseport parameter of the “listen” directive.
