### ISSUE TITLE
eventloop_unittest runs failed

### ISSUE THREAD

**Issue by weizili** [chenshuo/muduo#262]
This line will cause a crush core dump:
https://github.com/chenshuo/muduo/blob/master/muduo/net/tests/EventLoop_unittest.cc#L18

One thread can run only one `EventLoop`.

<pre>
#0  0x0000003801a32625 in raise () from /lib64/libc.so.6
#1  0x0000003801a33e05 in abort () from /lib64/libc.so.6
#2  0x0000000000448955 in muduo::Logger::~Logger (this=0x7ffff7ac9570, __in_chrg=<value optimized out>) at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/base/Logging.cc:200
#3  0x000000000043355d in muduo::net::EventLoop::EventLoop (this=0x7ffff7aca5e0) at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/net/EventLoop.cc:80
#4  0x00000000004325ee in callback () at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/net/tests/EventLoop_unittest.cc:18
#5  0x0000000000432f4c in boost::detail::function::void_function_invoker0<void (*)(), void>::invoke (function_ptr=...) at /usr/include/boost/function/function_template.hpp:112
#6  0x0000000000435999 in boost::function0<void>::operator() (this=0x7ffff0000cb0) at /usr/include/boost/function/function_template.hpp:767
#7  0x0000000000441270 in muduo::net::Timer::run (this=0x7ffff0000cb0) at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/net/Timer.h:50
#8  0x0000000000440838 in muduo::net::TimerQueue::handleRead (this=0x7ffff0000a00) at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/net/TimerQueue.cc:191
#9  0x00000000004459ed in boost::_mfi::mf0<void, muduo::net::TimerQueue>::operator() (this=0x7ffff0000a50, p=0x7ffff0000a00) at /usr/include/boost/bind/mem_fn_template.hpp:49
#10 0x0000000000445228 in boost::_bi::list1<boost::_bi::value<muduo::net::TimerQueue*> >::operator()<boost::_mfi::mf0<void, muduo::net::TimerQueue>, boost::_bi::list1<muduo::Timestamp&> > (this=0x7ffff0000a60, f=..., a=...)
    at /usr/include/boost/bind/bind.hpp:253
#11 0x0000000000444dec in boost::_bi::bind_t<void, boost::_mfi::mf0<void, muduo::net::TimerQueue>, boost::_bi::list1<boost::_bi::value<muduo::net::TimerQueue*> > >::operator()<muduo::Timestamp> (this=0x7ffff0000a50, a1=...)
    at /usr/include/boost/bind/bind_template.hpp:32
#12 0x00000000004444db in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf0<void, muduo::net::TimerQueue>, boost::_bi::list1<boost::_bi::value<muduo::net::TimerQueue*> > >, void, muduo::Timestamp>::invoke (function_obj_ptr=..., a0=...) at /usr/include/boost/function/function_template.hpp:153
#13 0x0000000000447642 in boost::function1<void, muduo::Timestamp>::operator() (this=0x7ffff0000a48, a0=...) at /usr/include/boost/function/function_template.hpp:767
#14 0x0000000000446bbf in muduo::net::Channel::handleEventWithGuard (this=0x7ffff0000a10, receiveTime=...) at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/net/Channel.cc:107
#15 0x0000000000446795 in muduo::net::Channel::handleEvent (this=0x7ffff0000a10, receiveTime=...) at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/net/Channel.cc:79
#16 0x0000000000433c55 in muduo::net::EventLoop::loop (this=0x7ffff7acfa20) at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/net/EventLoop.cc:125
#17 0x000000000043272e in threadFunc () at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/net/tests/EventLoop_unittest.cc:29
#18 0x0000000000432f4c in boost::detail::function::void_function_invoker0<void (*)(), void>::invoke (function_ptr=...) at /usr/include/boost/function/function_template.hpp:112
#19 0x0000000000435999 in boost::function0<void>::operator() (this=0x6664c0) at /usr/include/boost/function/function_template.hpp:767
#20 0x00000000004502fb in muduo::detail::ThreadData::runInThread (this=0x6664c0) at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/base/Thread.cc:94
#21 0x000000000044fabe in muduo::detail::startThread (obj=0x6664c0) at /home/weizili/workspace/github.com/chenshuo/muduo/muduo/base/Thread.cc:124
#22 0x00000038022079d1 in start_thread () from /lib64/libpthread.so.0
#23 0x0000003801ae89dd in clone () from /lib64/libc.so.6
</pre>

**Comment by chenshuo** [comment]
The purpose of this unittest is to verify that no two EventLoop can run in the same thread.
It is expected to crash,

**Comment by zieckey** [comment]
OK. Got it.  Maybe we can add some comments to make that purpose clear.
