### ISSUE TITLE
无法找到函数定义

### ISSUE THREAD

**Issue by jnxyatmjx** [chenshuo/muduo#270]
我把CountDownLatch，Mutex，Thread，Condition拿出来单独编译，引用了相关头文件和命名空间。，发现了这个问题main.cpp:26: undefined reference to `muduo::CountDownLatch::CountDownLatch(int)' ，陈老师觉得是什么问题？

**Comment by yongzhizhan** [comment]
依赖了静态库吗？

2017-05-10 14:30 GMT+08:00 jnxyatmjx <notifications@github.com>:
