### ISSUE TITLE
请问这个返回栈内存没有问题吗？

### ISSUE THREAD

**Issue by rwen2012** [chenshuo/muduo#271]
https://github.com/chenshuo/muduo/blob/master/muduo/base/Date.cc

string Date::toIsoString() const
{
  char buf[32];
  YearMonthDay ymd(yearMonthDay());
  snprintf(buf, sizeof buf, "%4d-%02d-%02d", ymd.year, ymd.month, ymd.day);
  return buf;
}

菜鸟一枚，请教大侠，谢谢。

**Comment by byronyi** [comment]
注意返回值，这里隐式调用了string的构造函数，返回的是拷贝过的字符串

**Comment by rwen2012** [comment]
明白，感谢。
