### ISSUE TITLE
examples/pingpong/bench.cc中全局变量g_loop引用局部变量loop导致coredump

### ISSUE THREAD

**Issue by octocat9lee** [chenshuo/muduo#272]
由于g_loop引用局部变量loop，导致局部变量loop析构后，boost::ptr_vector<Channel> g_channels中的元素才析构，从而使用已经析构的loop，导致coredump。

**Comment by chenshuo** [comment]
欢迎提 pull request。

**Comment by chenshuo** [comment]
Fixed by  44879bf .
