### ISSUE TITLE
线程池实现的问题

### ISSUE THREAD

**Issue by NearXdu** [chenshuo/muduo#276]
陈硕老师好,参考muduo的ThreadPool我自己实现了一个,踩了一些坑...有一个问题想请教:
在muduo中线程池有如下代码实现:
```cpp
ThreadPool::Task ThreadPool::take()
{
    MutexLockGuard lock(mutex_);
    // always use a while-loop, due to spurious wakeup
    while (queue_.empty() && running_)
    {
	notEmpty_.wait();
    }
    Task task;
    if (!queue_.empty())
//此处我改成了   if(running_)
    {
	task = queue_.front();
	queue_.pop_front();
	if (maxQueueSize_ > 0)
	{
	    notFull_.notify();
	}
    }
    return task;
}
```
上面代码`if(!queue_.empty())`改成了`if(running_)`

这是我的改写的测试程序,删去了CountDonwLatch同步
```cpp
void task()
{
    std::cout<<"hello"<<std::endl;
    
}
void test(int maxSize)
{
  muduo::ThreadPool pool("MainThreadPool");
  pool.setMaxQueueSize(maxSize);
  pool.start(2);//2
  sleep(1);//等待线程start

  pool.run(task);//run
  pool.stop();
}
```
如果直接编译运行,线程将不会有任何打印(任务没被执行线程就回收了?),但是`strace`和`gdb`调试都是正常的...测试代码中,我删去了`CountDownLatch`来复现

最后发现是running_变量在多线程环境下被stop()函数赋值成了false,导致take最终return了一个空的task,而runInthread的循环也结束,pthread_join返回...

我的问题是:
您在书中说道: 条件变量的wait是会原子的释放锁并等待wait执行完返回时会自动加锁,当我在主线程调用run方法时,会notify线程,此时线程重新拿到锁,这个时候主线程的stop调用如何再拿到锁修改running_变量为false?

**Comment by chenshuo** [comment]
Is this an issue in muduo's code ?

**Comment by NearXdu** [comment]
@chenshuo No... It's just a question when I'm learning muduo as well as the book...

**Comment by alwaysused** [comment]
说一下我的看法哈。
        可能那个threadpool的线程当时并没有开始执行（只能说可能性很小吧。）；也可能主线程run之后仍继续执行，stop获得锁，也就是说在run和stop之间如果阻塞的线程没有立即执行（这个是不可预知的。）是没有上锁的。然后主线程继续执行，stop获得锁，更改running值，线程池里的线程执行检测running的值，退出。
       你可以在stop的开始处，和while{notEmpty. wait();}下面加各一句打印的代码，就知道谁先谁后了。
       顺便说一句，线程池的意义在于保证所有要执行的任务都执行了，所以无论去掉CountAndLatch或者检测running的值而不是!empty()都不是合乎情理的。

**Comment by alwaysused** [comment]
@NearXdu 
        说一下我的看法哈。
        可能那个threadpool的线程当时并没有开始执行（只能说可能性很小吧。）；也可能主线程run之后仍继续执行，stop获得锁，也就是说在run和stop之间如果阻塞的线程没有立即执行（这个是不可预知的。）是没有上锁的。然后主线程继续执行，stop获得锁，更改running值，线程池里的线程执行检测running的值，退出。
       你可以在stop的开始处，和while{notEmpty. wait();}下面加各一句打印的代码，就知道谁先谁后了。
       顺便说一句，线程池的意义在于保证所有要执行的任务都执行了，所以无论去掉CountAndLatch或者检测running的值而不是!empty()都不是合乎情理的。

**Comment by chenshuo** [comment]
Then it is not an issue of muduo.
