### ISSUE TITLE
创建Thread对象的时候出现错误

### ISSUE THREAD

**Issue by JieTrancender** [chenshuo/muduo#281]
#include <muduo/base/Thread.h>
	#include <muduo/base/CurrentThread.h>
	#include <muduo/net/EventLoop.h>

	#include <cstdio>
	#include <functional>

	#include <boost/bind.hpp>
	#include <boost/function.hpp>

	void threadFunc()
	{
	    printf("threadFunc(): pid = %d, tid = %d\n", getpid(), muduo::CurrentThread::tid());
	    
	    muduo::net::EventLoop loop;
	    loop.loop();
	}

	int main(int argc, char* argv[])
	{
	    printf("threadFunc(): pid = %d, tid = %d\n", getpid(), muduo::CurrentThread::tid());

	    muduo::net::EventLoop loop;

	    //wrong
	    muduo::Thread thread(threadFunc);
	    thread.start();

	    loop.loop();
	    pthread_exit(nullptr);
	}

链接的时候提示Thread::Thread(boost::function<void()>&&..)移动构造函数未定义
应该是我的环境没有__GXX_EXPERIMENTAL_CXX0X__宏所以导致确实没有定义移动构造函数
但是我直接muduo::Thread thread(threadFunc);不应该出错才对？

// 试验了一下这个方式也过不去，依旧是未定义
std::function<void()> func(threadFunc);
Thread thread(func)

// 这样依旧过不去
muduo::Thread thread((boost::function<void()>)threadFunc);

// 最后采用这种方式成功
muduo::Thread::ThreadFunc func(threadFunc);
muduo::Thread thread(func);

**Comment by chenshuo** [comment]
If you compile your code with -std=c++11, you should link libmuduo_base_cpp11.a .

**Comment by JieTrancender** [comment]
all right.
