### ISSUE TITLE
编译muduo-1.0,2 报错

### ISSUE THREAD

**Issue by ma-nuli** [chenshuo/muduo#282]
/home/manuli/下载/muduo-1.0.2/muduo/net/protobuf/ProtobufCodecLite.cc:30:7: error: ‘{anonymous}::dummy’ defined but not used [-Werror=unused-variable]
   int dummy = ProtobufVersionCheck();
       ^
cc1plus: all warnings being treated as errors
muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec_cpp11.dir/build.make:62: recipe for target 'muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec_cpp11.dir/ProtobufCodecLite.cc.o' failed
make[2]: *** [muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec_cpp11.dir/ProtobufCodecLite.cc.o] Error 1
CMakeFiles/Makefile2:2053: recipe for target 'muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec_cpp11.dir/all' failed
make[1]: *** [muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec_cpp11.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
 求陈大神 帮忙指点一下 感激不尽 最近在精读  大神那本多线程使用 muduo

**Comment by wuzhiguocarter** [comment]
把顶层CMakeLists.txt里-Werror  -Wno-unused-parameter选项注释掉
