### ISSUE TITLE
acceptor中的回调设置

### ISSUE THREAD

**Issue by hfxmath** [chenshuo/muduo#284]
在Accetor类中,构造函数的时候最后一行:
 acceptChannel_.setReadCallback(boost::bind(&Acceptor::handleRead, this));
而acceptor中的成员函数handRead的原型为void Acceptor::handleRead()
但是accetpChannel设置回调函数的时候：

typedef boost::function<void(Timestamp)> ReadEventCallback;

            void setReadCallback(const ReadEventCallback &cb)
            {
                readCallback_ = cb;
            }
 ReadEventCallback readCallback_;
这个回调函数的参数类型不匹配啊， 这个是什么意思？

**Comment by chenshuo** [comment]
This is not an issue of muduo.
