### ISSUE TITLE
TcpConnection::handleRead里面readFd死循环循环返回-1，导致日志写满磁盘

### ISSUE THREAD

**Issue by fdxuwei** [chenshuo/muduo#286]
生产环境出现这样的问题：
TcpConnection::handleRead里面的readFd在同一个连接上面死循环返回-1，errno=EAGAIN，导致日志写满磁盘，请问这种问题怎么解决？

**Comment by chenshuo** [comment]
First step: reproduce the problem with sscce.org
https://zhuanlan.zhihu.com/p/20752519

**Comment by fdxuwei** [comment]
很抱歉这个问题没能在测试环境重现，在生产环境也只是偶尔才会出现。目前新观察到的现象就是在一个连接上不断的产生EPOLLPRI事件。

**Comment by chenshuo** [comment]
Paste output of `strace` here.

**Comment by fdxuwei** [comment]
生产环境的连接很多，数据交互也很多，不能一直开着trace日志，也来不及在问题发生时来查看进程的状态，因为很快就能写满50g的磁盘。已观察到的现象是通过修改muduo代码，通过计算一个连接上持续的eagain次数，当大于100时，修改日志等级为TRACE，当eagain持续增加超过110时，再关闭trace日志，并关闭该有问题的连接，以使线上服务正常运行。
man-page poll(2) 关于EPOLLPRI的说明：
       POLLPRI
              There is some exceptional condition on the file descriptor.
              Possibilities include:

              *  There is out-of-band data on a TCP socket (see tcp(7)).

              *  A pseudoterminal master in packet mode has seen a state
                 change on the slave (see ioctl_tty(2)).

              *  A cgroup.events file has been modified (see cgroups(7)).
我正在研究这三种情况。
另外我觉的muduo在处理EPOLLPRI事件时调用普通的read函数不是很合理，是不是应该调用recv，加上MSG_OOB标志？不过我对tcp带外数据不是很熟悉，正在研究中。

**Comment by chenshuo** [comment]
发生此现象时，用 http://man7.org/linux/man-pages/man1/strace.1.html 这个工具看一下，把结果贴出来。

**Comment by fdxuwei** [comment]
部分strace（10秒总共两万多行）：
10:36:15.070879 read(7, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.070913 write(107, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.070944 epoll_wait(5, {{EPOLLIN, {u32=11036336, u64=11036336}}}, 16, 10000) = 1
10:36:15.071265 accept4(14, {sa_family=AF_INET, sin_port=htons(21080), sin_addr=inet_addr("10.184.33.4")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 227027
10:36:15.071308 getsockname(227027, {sa_family=AF_INET, sin_port=htons(5003), sin_addr=inet_addr("10.187.211.142")}, [16]) = 0
10:36:15.071350 write(104, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.071416 epoll_wait(5, {{EPOLLIN, {u32=11029184, u64=11029184}}}, 16, 10000) = 1
10:36:15.071705 read(7, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.071736 write(32, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.071856 close(244753)           = 0
10:36:15.071893 epoll_wait(5, {{EPOLLIN, {u32=11030496, u64=11030496}}}, 16, 10000) = 1
10:36:15.072406 accept4(10, {sa_family=AF_INET, sin_port=htons(19415), sin_addr=inet_addr("10.184.32.156")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 235250
10:36:15.072459 getsockname(235250, {sa_family=AF_INET, sin_port=htons(5001), sin_addr=inet_addr("10.187.211.142")}, [16]) = 0
10:36:15.072503 write(68, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.072536 epoll_wait(5, {{EPOLLIN, {u32=11029744, u64=11029744}}}, 16, 10000) = 1
10:36:15.073097 accept4(8, {sa_family=AF_INET, sin_port=htons(17485), sin_addr=inet_addr("10.184.32.87")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 235302
10:36:15.073137 getsockname(235302, {sa_family=AF_INET, sin_port=htons(5000), sin_addr=inet_addr("10.187.211.142")}, [16]) = 0
10:36:15.073177 write(32, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.073210 epoll_wait(5, {{EPOLLIN, {u32=11029184, u64=11029184}}}, 16, 10000) = 1
10:36:15.075891 read(7, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.075929 write(47, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.075960 epoll_wait(5, {{EPOLLIN, {u32=11036336, u64=11036336}}}, 16, 10000) = 1
10:36:15.076759 accept4(14, {sa_family=AF_INET, sin_port=htons(34802), sin_addr=inet_addr("10.184.33.106")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 199737
10:36:15.076802 getsockname(199737, {sa_family=AF_INET, sin_port=htons(5003), sin_addr=inet_addr("10.187.211.142")}, [16]) = 0
10:36:15.076845 write(107, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.076877 epoll_wait(5, {{EPOLLIN, {u32=11029184, u64=11029184}}}, 16, 10000) = 1
10:36:15.078235 read(7, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.078273 write(71, "\1\0\0\0\0\0\0\0", 8) = 8
10:36:15.078315 close(11218)            = 0

相应的日志：
20170816 10:36:15.070879 300316 ERROR TcpConnection::handleError [:10.187.211.142:5001#4388409] - SO_ERROR = 0 Success - TcpConnection.cc:419
20170816 10:36:15.070882 300316 ERROR Resource temporarily unavailable (errno=11) TcpConnection::handleRead - TcpConnection.cc:341
20170816 10:36:15.070883 300316 ERROR TcpConnection::handleError [:10.187.211.142:5001#4388409] - SO_ERROR = 0 Success - TcpConnection.cc:419
20170816 10:36:15.070886 300316 ERROR Resource temporarily unavailable (errno=11) TcpConnection::handleRead - TcpConnection.cc:341
20170816 10:36:15.070887 300316 ERROR TcpConnection::handleError [:10.187.211.142:5001#4388409] - SO_ERROR = 0 Success - TcpConnection.cc:419
20170816 10:36:15.070890 300316 ERROR Resource temporarily unavailable (errno=11) TcpConnection::handleRead - TcpConnection.cc:341
20170816 10:36:15.070892 300316 ERROR TcpConnection::handleError [:10.187.211.142:5001#4388409] - SO_ERROR = 0 Success - TcpConnection.cc:419
20170816 10:36:15.070895 300316 ERROR Resource temporarily unavailable (errno=11) TcpConnection::handleRead - TcpConnection.cc:341
20170816 10:36:15.070896 300316 ERROR TcpConnection::handleError [:10.187.211.142:5001#4388409] - SO_ERROR = 0 Success - TcpConnection.cc:419
20170816 10:36:15.070899 300316 ERROR Resource temporarily unavailable (errno=11) TcpConnection::handleRead - TcpConnection.cc:341
20170816 10:36:15.070901 300316 ERROR TcpConnection::handleError [:10.187.211.142:5001#4388409] - SO_ERROR = 0 Success - TcpConnection.cc:419
20170816 10:36:15.070904 300316 ERROR Resource temporarily unavailable (errno=11) TcpConnection::handleRead - TcpConnection.cc:341
20170816 10:36:15.070905 300316 ERROR TcpConnection::handleError [:10.187.211.142:5001#4388409] - SO_ERROR = 0 Success - TcpConnection.cc:419
20170816 10:36:15.070908 300316 ERROR Resource temporarily unavailable (errno=11) TcpConnection::handleRead - TcpConnection.cc:341
20170816 10:36:15.070910 300316 ERROR TcpConnection::handleError [:10.187.211.142:5001#4388409] - SO_ERROR = 0 Success - TcpConnection.cc:419
20170816 10:36:15.070913 300316 ERROR Resource temporarily unavailable (errno=11) TcpConnection::handleRead - TcpConnection.cc:341
20170816 10:36:15.070915 300316 ERROR TcpConnection::handleError [:10.187.211.142:5001#4388409] - SO_ERROR = 0 Success - TcpConnection.cc:419
20170816 10:36:15.070918 300316 ERROR Resource temporarily unavailable (errno=11) TcpConnection::handleRead - TcpConnection.cc:341
20170816 10:36:15.070919 300316 ERROR TcpConnection::handleError [:10.187.211.142:5001#4388409] - SO_ERROR = 0 Success - TcpConnection.cc:419
20170816 10:36:15.070922 300316 ERROR Resource temporarily unavailable (errno=11) TcpConnection::handleRead - TcpConnection.cc:341

strace和日志好像对不上，strace里面的read没有eagain，而且strace的系统调用次数偏少。

**Comment by chenshuo** [comment]
`strace` 是不是看的 300316 这个线程？

**Comment by fdxuwei** [comment]
加了-f：
300319 10:46:42.333388 epoll_wait(60,  <unfinished ...>
300318 10:46:42.333401 epoll_wait(57,  <unfinished ...>
300317 10:46:42.333412 epoll_wait(54,  <unfinished ...>
300316 10:46:42.333422 epoll_wait(51,  <unfinished ...>
300315 10:46:42.333432 epoll_wait(48,  <unfinished ...>
300314 10:46:42.333445 epoll_wait(45,  <unfinished ...>
300313 10:46:42.333456 epoll_wait(42,  <unfinished ...>
300312 10:46:42.333467 epoll_wait(39,  <unfinished ...>
300311 10:46:42.333477 epoll_wait(36,  <unfinished ...>
300310 10:46:42.333487 epoll_wait(33,  <unfinished ...>
300309 10:46:42.333499 epoll_wait(30,  <unfinished ...>
300308 10:46:42.333510 epoll_wait(27,  <unfinished ...>
300307 10:46:42.333520 futex(0x8b799c, FUTEX_WAIT_PRIVATE, 5281, NULL <unfinished ...>
300306 10:46:42.333531 epoll_wait(24,  <unfinished ...>
300305 10:46:42.333547 epoll_wait(21,  <unfinished ...>
300304 10:46:42.333558 epoll_wait(18,  <unfinished ...>
300303 10:46:42.333567 restart_syscall(<... resuming interrupted call ...> <unfinished ...>
300302 10:46:42.333577 restart_syscall(<... resuming interrupted call ...> <unfinished ...>
300301 10:46:42.333588 epoll_wait(5,  <unfinished ...>
300332 10:46:42.333605 <... getsockopt resumed> [0], [4]) = 0
300327 10:46:42.333620 <... epoll_wait resumed> {{EPOLLIN, {u32=729585552, u64=729585552}}}, 32, 10000) = 1
300315 10:46:42.333643 <... epoll_wait resumed> {{EPOLLIN, {u32=641372064, u64=641372064}}}, 32, 10000) = 1
300332 10:46:42.333670 epoll_wait(99,  <unfinished ...>
300327 10:46:42.333681 readv(143194,  <unfinished ...>
300315 10:46:42.333734 readv(195195,  <unfinished ...>
300332 10:46:42.333765 <... epoll_wait resumed> {{EPOLLPRI, {u32=760503104, u64=760503104}}}, 32, 10000) = 1
300327 10:46:42.333779 <... readv resumed> [{"\0\312\7\322{\"APPID\":101,\"OS_VERSION\":\"2"..., 1024}, {"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 65536}], 2) = 202
300315 10:46:42.333885 <... readv resumed> [{"\0\4\0\0{\"APPID\":101,\"OS_VERSION\":\"2"..., 1024}, {"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 65536}], 2) = 4
300336 10:46:42.333939 <... epoll_wait resumed> {{EPOLLIN, {u32=815405856, u64=815405856}}}, 64, 10000) = 1
300332 10:46:42.333964 readv(68354,  <unfinished ...>
300327 10:46:42.333977 sendmsg(57505, {msg_name(0)=NULL, msg_iov(1)=[{"\1\10\1\fm\0\0\0\0\0\0\0(\0\0\0\0\0\0\0H\0\0\0\0\0\0\0\0\0\0\0"..., 257}], msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_
NOSIGNAL <unfinished ...>
300315 10:46:42.334020 futex(0x8b7824, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x8b7820, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1} <unfinished ...>
300336 10:46:42.334054 readv(169179,  <unfinished ...>
300344 10:46:42.334070 <... futex resumed> ) = 0
300332 10:46:42.334080 <... readv resumed> 0x7f5d175e4520, 2) = -1 EAGAIN (Resource temporarily unavailable)
300327 10:46:42.334098 <... sendmsg resumed> ) = 257
300315 10:46:42.334112 <... futex resumed> ) = 1
300344 10:46:42.334135 futex(0x8b77e8, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
300336 10:46:42.334145 <... readv resumed> [{"\0\4\0\0\0\312\7\322{\"APPID\":101,\"OS_VERSION"..., 1024}, {"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 65536}], 2) = 4
300332 10:46:42.334189 getsockopt(68354, SOL_SOCKET, SO_ERROR,  <unfinished ...>
300327 10:46:42.334202 read(57505,  <unfinished ...>
300315 10:46:42.334218 futex(0x8b77e8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
300344 10:46:42.334237 <... futex resumed> ) = -1 EAGAIN (Resource temporarily unavailable)
300336 10:46:42.334249 write(169179, "\0\4\0\1", 4 <unfinished ...>
300332 10:46:42.334273 <... getsockopt resumed> [0], [4]) = 0
300315 10:46:42.334287 <... futex resumed> ) = 0
300344 10:46:42.334317 futex(0x8b77e8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>

**Comment by chenshuo** [comment]
看起来有可能是 OOB，你先配置防火墙，看看能不能屏蔽或断开这样的连接。
我这两天会写个 patch。

**Comment by fdxuwei** [comment]
生产环境：Centos6.5，Linux 2.6.32-504.16.2.el6.x86_64
muduo版本不记得了，一年之前拉的master分支。

**Comment by chenshuo** [comment]
使用 `SO_OOBINLINE` 之后还有没有这个现象？

**Comment by fdxuwei** [comment]
今天刚上线，观察两天。
理论上分析：设置SO_OOBINLINE，把OOB当做正常数据来读，程序最终会读到无法识别的协议号，或者无法解析的数据体，然后断开连接。

**Comment by chenshuo** [comment]
我试过，如果只是发一次 OOB 数据，不会造成此现象。

**Comment by fdxuwei** [comment]
是的，我测试也是这样。而且连续发一个字节的OOB时，服务端只随机把部分数据当做OOB，其他的通过普通的read也能读到数据。

**Comment by fdxuwei** [comment]
设置了SO_OOBINLINE，问题还是出现了。
