### ISSUE TITLE
ubuntu 16.04 build bin/logstream_test 报错

### ISSUE THREAD

**Issue by berlinhuang** [chenshuo/muduo#287]
/home/berlin/下载/clion-2017.2/bin/cmake/bin/cmake --build /home/berlin/code/github/muduo/cmake-build-debug --target all -- -j 1
[  1%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/AsyncLogging.cc.o
[  1%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Condition.cc.o
[  1%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/CountDownLatch.cc.o
[  1%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Date.cc.o
[  2%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Exception.cc.o
[  2%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/FileUtil.cc.o
[  2%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/LogFile.cc.o
[  2%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Logging.cc.o
[  3%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/LogStream.cc.o
[  3%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/ProcessInfo.cc.o
[  3%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Timestamp.cc.o
[  3%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/TimeZone.cc.o
[  3%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/Thread.cc.o
[  5%] Building CXX object muduo/base/CMakeFiles/muduo_base_cpp11.dir/ThreadPool.cc.o
[  5%] Linking CXX static library ../../lib/libmuduo_base_cpp11.a
[  5%] Built target muduo_base_cpp11
[  5%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/AsyncLogging.cc.o
[  5%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Condition.cc.o
[  6%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/CountDownLatch.cc.o
[  6%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Date.cc.o
[  6%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Exception.cc.o
[  6%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/FileUtil.cc.o
[  7%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/LogFile.cc.o
[  7%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Logging.cc.o
[  7%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/LogStream.cc.o
[  7%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/ProcessInfo.cc.o
[  9%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Timestamp.cc.o
[  9%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/TimeZone.cc.o
[  9%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/Thread.cc.o
[  9%] Building CXX object muduo/base/CMakeFiles/muduo_base.dir/ThreadPool.cc.o
[  9%] Linking CXX static library ../../lib/libmuduo_base.a
[  9%] Built target muduo_base
[  9%] Building CXX object muduo/base/tests/CMakeFiles/timezone_unittest.dir/TimeZone_unittest.cc.o
[  9%] Linking CXX executable ../../../bin/timezone_unittest
[  9%] Built target timezone_unittest
[  9%] Building CXX object muduo/base/tests/CMakeFiles/threadpool_test.dir/ThreadPool_test.cc.o
[ 10%] Linking CXX executable ../../../bin/threadpool_test
[ 10%] Built target threadpool_test
[ 10%] Building CXX object muduo/base/tests/CMakeFiles/threadlocalsingleton_test.dir/ThreadLocalSingleton_test.cc.o
[ 10%] Linking CXX executable ../../../bin/threadlocalsingleton_test
[ 10%] Built target threadlocalsingleton_test
[ 10%] Building CXX object muduo/base/tests/CMakeFiles/processinfo_test.dir/ProcessInfo_test.cc.o
[ 10%] Linking CXX executable ../../../bin/processinfo_test
[ 10%] Built target processinfo_test
[ 10%] Building CXX object muduo/base/tests/CMakeFiles/date_unittest.dir/Date_unittest.cc.o
[ 10%] Linking CXX executable ../../../bin/date_unittest
[ 10%] Built target date_unittest
[ 10%] Building CXX object muduo/base/tests/CMakeFiles/boundedblockingqueue_test.dir/BoundedBlockingQueue_test.cc.o
[ 10%] Linking CXX executable ../../../bin/boundedblockingqueue_test
[ 10%] Built target boundedblockingqueue_test
[ 10%] Building CXX object muduo/base/tests/CMakeFiles/timestamp_unittest.dir/Timestamp_unittest.cc.o
[ 11%] Linking CXX executable ../../../bin/timestamp_unittest
[ 11%] Built target timestamp_unittest
[ 13%] Building CXX object muduo/base/tests/CMakeFiles/fileutil_test.dir/FileUtil_test.cc.o
[ 13%] Linking CXX executable ../../../bin/fileutil_test
[ 13%] Built target fileutil_test
[ 14%] Building CXX object muduo/base/tests/CMakeFiles/threadlocal_test.dir/ThreadLocal_test.cc.o
[ 14%] Linking CXX executable ../../../bin/threadlocal_test
[ 14%] Built target threadlocal_test
[ 14%] Building CXX object muduo/base/tests/CMakeFiles/exception_test.dir/Exception_test.cc.o
[ 14%] Linking CXX executable ../../../bin/exception_test
[ 14%] Built target exception_test
[ 14%] Building CXX object muduo/base/tests/CMakeFiles/blockingqueue_test.dir/BlockingQueue_test.cc.o
[ 14%] Linking CXX executable ../../../bin/blockingqueue_test
[ 14%] Built target blockingqueue_test
[ 14%] Building CXX object muduo/base/tests/CMakeFiles/thread_test.dir/Thread_test.cc.o
[ 14%] Linking CXX executable ../../../bin/thread_test
[ 14%] Built target thread_test
[ 14%] Building CXX object muduo/base/tests/CMakeFiles/blockingqueue_bench.dir/BlockingQueue_bench.cc.o
[ 14%] Linking CXX executable ../../../bin/blockingqueue_bench
[ 14%] Built target blockingqueue_bench
[ 14%] Building CXX object muduo/base/tests/CMakeFiles/asynclogging_test.dir/AsyncLogging_test.cc.o
[ 15%] Linking CXX executable ../../../bin/asynclogging_test
[ 15%] Built target asynclogging_test
[ 15%] Building CXX object muduo/base/tests/CMakeFiles/atomic_unittest.dir/Atomic_unittest.cc.o
[ 15%] Linking CXX executable ../../../bin/atomic_unittest
[ 15%] Built target atomic_unittest
[ 17%] Building CXX object muduo/base/tests/CMakeFiles/mutex_test.dir/Mutex_test.cc.o
[ 17%] Linking CXX executable ../../../bin/mutex_test
[ 17%] Built target mutex_test
[ 18%] Building CXX object muduo/base/tests/CMakeFiles/gzipfile_test.dir/GzipFile_test.cc.o
[ 18%] Linking CXX executable ../../../bin/gzipfile_test
[ 18%] Built target gzipfile_test
[ 18%] Building CXX object muduo/base/tests/CMakeFiles/logfile_test.dir/LogFile_test.cc.o
[ 18%] Linking CXX executable ../../../bin/logfile_test
[ 18%] Built target logfile_test
[ 18%] Building CXX object muduo/base/tests/CMakeFiles/logging_test.dir/Logging_test.cc.o
[ 18%] Linking CXX executable ../../../bin/logging_test
[ 18%] Built target logging_test
[ 19%] Building CXX object muduo/base/tests/CMakeFiles/logstream_bench.dir/LogStream_bench.cc.o
[ 19%] Linking CXX executable ../../../bin/logstream_bench
[ 19%] Built target logstream_bench
[ 19%] Building CXX object muduo/base/tests/CMakeFiles/singleton_test.dir/Singleton_test.cc.o
[ 19%] Linking CXX executable ../../../bin/singleton_test
[ 19%] Built target singleton_test
[ 19%] Building CXX object muduo/base/tests/CMakeFiles/blockingqueue_cpp11_test.dir/BlockingQueue_test.cc.o
[ 21%] Linking CXX executable ../../../bin/blockingqueue_cpp11_test
[ 21%] Built target blockingqueue_cpp11_test
[ 21%] Building CXX object muduo/base/tests/CMakeFiles/logstream_test.dir/LogStream_test.cc.o
[ 21%] Linking CXX executable ../../../bin/logstream_test
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘testLogStreamFloats::test_method()’中：
/home/berlin/code/github/muduo/muduo/base/tests/LogStream_test.cc:157：对‘boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘__static_initialization_and_destruction_0(int, int)’中：
/home/berlin/code/github/muduo/muduo/base/tests/LogStream_test.cc:13：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)’未定义的引用
/home/berlin/code/github/muduo/muduo/base/tests/LogStream_test.cc:26：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)’未定义的引用
/home/berlin/code/github/muduo/muduo/base/tests/LogStream_test.cc:43：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)’未定义的引用
/home/berlin/code/github/muduo/muduo/base/tests/LogStream_test.cc:113：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)’未定义的引用
/home/berlin/code/github/muduo/muduo/base/tests/LogStream_test.cc:172：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o:/home/berlin/code/github/muduo/muduo/base/tests/LogStream_test.cc:186: 跟着更多未定义的参考到 boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)’中：
/usr/local/include/boost/test/tree/test_unit.hpp:249：对‘boost::unit_test::test_case::test_case(boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long, boost::function<void ()> const&)’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘bool boost::test_tools::tt_detail::check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, __gnu_cxx::__versa_string<char, std::char_traits<char>, std::allocator<char>, __gnu_cxx::__sso_string_base>, __gnu_cxx::__versa_string<char, std::char_traits<char>, std::allocator<char>, __gnu_cxx::__sso_string_base> >(boost::test_tools::tt_detail::equal_impl_frwd, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, __gnu_cxx::__versa_string<char, std::char_traits<char>, std::allocator<char>, __gnu_cxx::__sso_string_base> const&, char const*, __gnu_cxx::__versa_string<char, std::char_traits<char>, std::allocator<char>, __gnu_cxx::__sso_string_base> const&, char const*)’中：
/usr/local/include/boost/test/tools/old/impl.hpp:92：对‘boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘bool boost::test_tools::tt_detail::check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, int, int>(boost::test_tools::tt_detail::equal_impl_frwd, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, int const&, char const*, int const&, char const*)’中：
/usr/local/include/boost/test/tools/old/impl.hpp:92：对‘boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)’未定义的引用
collect2: error: ld returned 1 exit status
muduo/base/tests/CMakeFiles/logstream_test.dir/build.make:95: recipe for target 'bin/logstream_test' failed
make[2]: *** [bin/logstream_test] Error 1
CMakeFiles/Makefile2:1045: recipe for target 'muduo/base/tests/CMakeFiles/logstream_test.dir/all' failed
make[1]: *** [muduo/base/tests/CMakeFiles/logstream_test.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

berlin@berlin-virtual-machine:~/下载/clion-2017.2/bin$ dpkg -l |grep libboost
ii  libboost-all-dev                           1.58.0.1ubuntu1                                     amd64        Boost C++ Libraries development files (ALL) (default version)
ii  libboost-atomic-dev:amd64                  1.58.0.1ubuntu1                                     amd64        atomic data types, operations, and memory ordering constraints (default version)
ii  libboost-atomic1.58-dev:amd64              1.58.0+dfsg-5ubuntu3.1                              amd64        atomic data types, operations, and memory ordering constraints
ii  libboost-atomic1.58.0:amd64                1.58.0+dfsg-5ubuntu3.1                              amd64        atomic data types, operations, and memory ordering constraints
ii  libboost-chrono-dev:amd64                  1.58.0.1ubuntu1                                     amd64        C++ representation of time duration, time point, and clocks (default version)
ii  libboost-chrono1.58-dev:amd64              1.58.0+dfsg-5ubuntu3.1                              amd64        C++ representation of time duration, time point, and clocks
ii  libboost-chrono1.58.0:amd64                1.58.0+dfsg-5ubuntu3.1                              amd64        C++ representation of time duration, time point, and clocks
ii  libboost-context-dev:amd64                 1.58.0.1ubuntu1                                     amd64        provides a sort of cooperative multitasking on a single thread (default version)
ii  libboost-context1.58-dev:amd64             1.58.0+dfsg-5ubuntu3.1                              amd64        provides a sort of cooperative multitasking on a single thread
ii  libboost-context1.58.0:amd64               1.58.0+dfsg-5ubuntu3.1                              amd64        provides a sort of cooperative multitasking on a single thread
ii  libboost-coroutine-dev:amd64               1.58.0.1ubuntu1                                     amd64        provides a sort of cooperative multitasking on a single thread (default version)
ii  libboost-coroutine1.58-dev:amd64           1.58.0+dfsg-5ubuntu3.1                              amd64        provides a sort of cooperative multitasking on a single thread
ii  libboost-coroutine1.58.0:amd64             1.58.0+dfsg-5ubuntu3.1                              amd64        provides a sort of cooperative multitasking on a single thread
ii  libboost-date-time-dev:amd64               1.58.0.1ubuntu1                                     amd64        set of date-time libraries based on generic programming concepts (default version)
ii  libboost-date-time1.58-dev:amd64           1.58.0+dfsg-5ubuntu3.1                              amd64        set of date-time libraries based on generic programming concepts
ii  libboost-date-time1.58.0:amd64             1.58.0+dfsg-5ubuntu3.1                              amd64        set of date-time libraries based on generic programming concepts
ii  libboost-dev:amd64                         1.58.0.1ubuntu1                                     amd64        Boost C++ Libraries development files (default version)
ii  libboost-exception-dev:amd64               1.58.0.1ubuntu1                                     amd64        library to help write exceptions and handlers (default version)
ii  libboost-exception1.58-dev:amd64           1.58.0+dfsg-5ubuntu3.1                              amd64        library to help write exceptions and handlers
ii  libboost-filesystem-dev:amd64              1.58.0.1ubuntu1                                     amd64        filesystem operations (portable paths, iteration over directories, etc) in C++ (default version)
ii  libboost-filesystem1.58-dev:amd64          1.58.0+dfsg-5ubuntu3.1                              amd64        filesystem operations (portable paths, iteration over directories, etc) in C++
ii  libboost-filesystem1.58.0:amd64            1.58.0+dfsg-5ubuntu3.1                              amd64        filesystem operations (portable paths, iteration over directories, etc) in C++
ii  libboost-graph-dev:amd64                   1.58.0.1ubuntu1                                     amd64        generic graph components and algorithms in C++ (default version)
ii  libboost-graph-parallel-dev                1.58.0.1ubuntu1                                     amd64        generic graph components and algorithms in C++ (default version)
ii  libboost-graph-parallel1.58-dev            1.58.0+dfsg-5ubuntu3.1                              amd64        generic graph components and algorithms in C++
ii  libboost-graph-parallel1.58.0              1.58.0+dfsg-5ubuntu3.1                              amd64        generic graph components and algorithms in C++
ii  libboost-graph1.58-dev:amd64               1.58.0+dfsg-5ubuntu3.1                              amd64        generic graph components and algorithms in C++
ii  libboost-graph1.58.0:amd64                 1.58.0+dfsg-5ubuntu3.1                              amd64        generic graph components and algorithms in C++
ii  libboost-iostreams-dev:amd64               1.58.0.1ubuntu1                                     amd64        Boost.Iostreams Library development files (default version)
ii  libboost-iostreams1.58-dev:amd64           1.58.0+dfsg-5ubuntu3.1                              amd64        Boost.Iostreams Library development files
ii  libboost-iostreams1.58.0:amd64             1.58.0+dfsg-5ubuntu3.1                              amd64        Boost.Iostreams Library
ii  libboost-locale-dev:amd64                  1.58.0.1ubuntu1                                     amd64        C++ facilities for localization (default version)
ii  libboost-locale1.58-dev:amd64              1.58.0+dfsg-5ubuntu3.1                              amd64        C++ facilities for localization
ii  libboost-locale1.58.0:amd64                1.58.0+dfsg-5ubuntu3.1                              amd64        C++ facilities for localization
ii  libboost-log-dev                           1.58.0.1ubuntu1                                     amd64        C++ logging library (default version)
ii  libboost-log1.58-dev                       1.58.0+dfsg-5ubuntu3.1                              amd64        C++ logging library
ii  libboost-log1.58.0                         1.58.0+dfsg-5ubuntu3.1                              amd64        C++ logging library
ii  libboost-math-dev:amd64                    1.58.0.1ubuntu1                                     amd64        Boost.Math Library development files (default version)
ii  libboost-math1.58-dev:amd64                1.58.0+dfsg-5ubuntu3.1                              amd64        Boost.Math Library development files
ii  libboost-math1.58.0:amd64                  1.58.0+dfsg-5ubuntu3.1                              amd64        Boost.Math Library
ii  libboost-mpi-dev                           1.58.0.1ubuntu1                                     amd64        C++ interface to the Message Passing Interface (MPI) (default version)
ii  libboost-mpi-python-dev                    1.58.0.1ubuntu1                                     amd64        C++ interface to the Message Passing Interface (MPI), Python Bindings (default version)
ii  libboost-mpi-python1.58-dev                1.58.0+dfsg-5ubuntu3.1                              amd64        C++ interface to the Message Passing Interface (MPI), Python Bindings
ii  libboost-mpi-python1.58.0                  1.58.0+dfsg-5ubuntu3.1                              amd64        C++ interface to the Message Passing Interface (MPI), Python Bindings
ii  libboost-mpi1.58-dev                       1.58.0+dfsg-5ubuntu3.1                              amd64        C++ interface to the Message Passing Interface (MPI)
ii  libboost-mpi1.58.0                         1.58.0+dfsg-5ubuntu3.1                              amd64        C++ interface to the Message Passing Interface (MPI)
ii  libboost-program-options-dev:amd64         1.58.0.1ubuntu1                                     amd64        program options library for C++ (default version)
ii  libboost-program-options1.58-dev:amd64     1.58.0+dfsg-5ubuntu3.1                              amd64        program options library for C++
ii  libboost-program-options1.58.0:amd64       1.58.0+dfsg-5ubuntu3.1                              amd64        program options library for C++
ii  libboost-python-dev                        1.58.0.1ubuntu1                                     amd64        Boost.Python Library development files (default version)
ii  libboost-python1.58-dev                    1.58.0+dfsg-5ubuntu3.1                              amd64        Boost.Python Library development files
ii  libboost-python1.58.0                      1.58.0+dfsg-5ubuntu3.1                              amd64        Boost.Python Library
ii  libboost-random-dev:amd64                  1.58.0.1ubuntu1                                     amd64        Boost Random Number Library (default version)
ii  libboost-random1.58-dev:amd64              1.58.0+dfsg-5ubuntu3.1                              amd64        Boost Random Number Library
ii  libboost-random1.58.0:amd64                1.58.0+dfsg-5ubuntu3.1                              amd64        Boost Random Number Library
ii  libboost-regex-dev:amd64                   1.58.0.1ubuntu1                                     amd64        regular expression library for C++ (default version)
ii  libboost-regex1.58-dev:amd64               1.58.0+dfsg-5ubuntu3.1                              amd64        regular expression library for C++
ii  libboost-regex1.58.0:amd64                 1.58.0+dfsg-5ubuntu3.1                              amd64        regular expression library for C++
ii  libboost-serialization-dev:amd64           1.58.0.1ubuntu1                                     amd64        serialization library for C++ (default version)
ii  libboost-serialization1.58-dev:amd64       1.58.0+dfsg-5ubuntu3.1                              amd64        serialization library for C++
ii  libboost-serialization1.58.0:amd64         1.58.0+dfsg-5ubuntu3.1                              amd64        serialization library for C++
ii  libboost-signals-dev:amd64                 1.58.0.1ubuntu1                                     amd64        managed signals and slots library for C++ (default version)
ii  libboost-signals1.58-dev:amd64             1.58.0+dfsg-5ubuntu3.1                              amd64        managed signals and slots library for C++
ii  libboost-signals1.58.0:amd64               1.58.0+dfsg-5ubuntu3.1                              amd64        managed signals and slots library for C++
ii  libboost-system-dev:amd64                  1.58.0.1ubuntu1                                     amd64        Operating system (e.g. diagnostics support) library (default version)
ii  libboost-system1.58-dev:amd64              1.58.0+dfsg-5ubuntu3.1                              amd64        Operating system (e.g. diagnostics support) library
ii  libboost-system1.58.0:amd64                1.58.0+dfsg-5ubuntu3.1                              amd64        Operating system (e.g. diagnostics support) library
ii  libboost-test-dev:amd64                    1.58.0.1ubuntu1                                     amd64        components for writing and executing test suites (default version)
ii  libboost-test1.58-dev:amd64                1.58.0+dfsg-5ubuntu3.1                              amd64        components for writing and executing test suites
ii  libboost-test1.58.0:amd64                  1.58.0+dfsg-5ubuntu3.1                              amd64        components for writing and executing test suites
ii  libboost-thread-dev:amd64                  1.58.0.1ubuntu1                                     amd64        portable C++ multi-threading (default version)
ii  libboost-thread1.58-dev:amd64              1.58.0+dfsg-5ubuntu3.1                              amd64        portable C++ multi-threading
ii  libboost-thread1.58.0:amd64                1.58.0+dfsg-5ubuntu3.1                              amd64        portable C++ multi-threading
ii  libboost-timer-dev:amd64                   1.58.0.1ubuntu1                                     amd64        C++ wall clock and CPU process timers (default version)
ii  libboost-timer1.58-dev:amd64               1.58.0+dfsg-5ubuntu3.1                              amd64        C++ wall clock and CPU process timers
ii  libboost-timer1.58.0:amd64                 1.58.0+dfsg-5ubuntu3.1                              amd64        C++ wall clock and CPU process timers
ii  libboost-tools-dev                         1.58.0.1ubuntu1                                     amd64        Boost C++ Libraries development tools (default version)
ii  libboost-wave-dev:amd64                    1.58.0.1ubuntu1                                     amd64        C99/C++ preprocessor library (default version)
ii  libboost-wave1.58-dev:amd64                1.58.0+dfsg-5ubuntu3.1                              amd64        C99/C++ preprocessor library
ii  libboost-wave1.58.0:amd64                  1.58.0+dfsg-5ubuntu3.1                              amd64        C99/C++ preprocessor library
ii  libboost1.58-dev:amd64                     1.58.0+dfsg-5ubuntu3.1                              amd64        Boost C++ Libraries development files
ii  libboost1.58-tools-dev                     1.58.0+dfsg-5ubuntu3.1                              amd64        Boost C++ Libraries development tools

**Comment by chenshuo** [comment]
Have you installed `libboost-test-dev` ?

**Comment by berlinhuang** [comment]
恩 已经解决
