### ISSUE TITLE
写echo client和echo server时，超时问题

### ISSUE THREAD

**Issue by echo0109** [chenshuo/muduo#289]
client端在连接建立的时候，记下发送消息的时间戳和下次收到server端发送来的消息的时间戳进行比较，如果超时时间少于1s，超时差不多是1s 10个超时
代码如下：
https://gist.github.com/echo0109/1c1cf2981443281965ab6bdfd1113b5f                                                                               
echo_server 就是examples下的echo文件夹的server代码
发现这样的一个超时问题，麻烦陈老师能帮忙解释, 感谢

**Comment by echo0109** [comment]
以下是超时日志
20170821 14:58:29.659686Z 17845 INFO  receive_time: 20170821 14:58:29.659646 send_time_: 20170821 14:58:29.571697 - echo_client.cc:39
20170821 14:58:29.947460Z 17845 ERROR count_: 3375 timeout. - echo_client.cc:38
20170821 14:58:29.947506Z 17845 INFO  receive_time: 20170821 14:58:29.947440 send_time_: 20170821 14:58:29.812743 - echo_client.cc:39
20170821 14:58:30.193775Z 17845 ERROR count_: 5425 timeout. - echo_client.cc:38
20170821 14:58:30.193820Z 17845 INFO  receive_time: 20170821 14:58:30.193768 send_time_: 20170821 14:58:30.099358 - echo_client.cc:39
20170821 14:58:30.437017Z 17845 ERROR count_: 7467 timeout. - echo_client.cc:38
20170821 14:58:30.437048Z 17845 INFO  receive_time: 20170821 14:58:30.437008 send_time_: 20170821 14:58:30.350488 - echo_client.cc:39
20170821 14:58:30.699126Z 17845 ERROR count_: 9531 timeout. - echo_client.cc:38
20170821 14:58:30.699151Z 17845 INFO  receive_time: 20170821 14:58:30.699116 send_time_: 20170821 14:58:30.534373 - echo_client.cc:39
20170821 14:58:30.940517Z 17845 ERROR count_: 11563 timeout. - echo_client.cc:38
20170821 14:58:30.940533Z 17845 INFO  receive_time: 20170821 14:58:30.940510 send_time_: 20170821 14:58:30.839342 - echo_client.cc:39
20170821 14:58:31.202370Z 17845 ERROR count_: 13617 timeout. - echo_client.cc:38
20170821 14:58:31.202390Z 17845 INFO  receive_time: 20170821 14:58:31.202364 send_time_: 20170821 14:58:31.098607 - echo_client.cc:39
20170821 14:58:31.448371Z 17845 ERROR count_: 15657 timeout. - echo_client.cc:38
20170821 14:58:31.448388Z 17845 INFO  receive_time: 20170821 14:58:31.448365 send_time_: 20170821 14:58:31.372315 - echo_client.cc:39
20170821 14:58:31.695367Z 17845 ERROR count_: 17711 timeout. - echo_client.cc:38
20170821 14:58:31.695389Z 17845 INFO  receive_time: 20170821 14:58:31.695360 send_time_: 20170821 14:58:31.620016 - echo_client.cc:39

**Comment by echo0109** [comment]
之所以写这样的一个case，是因为生产环境中遇到了一个很类似的超时问题，从server端来看，并没有超时，并且消息是很快发往client端，但是client端把receive_time打印出来的时候，发现receive time就已经晚了。所以我简化了这样的一个场景，写了一个重要的case，希望老师能帮忙解释，或者说我写case的问题还是其他问题

**Comment by chenshuo** [comment]
抱歉，看不懂你想问什么。从你贴出的日志来看，也看不出超时。你说的“超时”究竟指什么？

**Comment by echo0109** [comment]
`#include "echo_client.h"                                                  
                                                                          
#include <muduo/base/Logging.h>                                           
#include <muduo/net/EventLoop.h>                                          
#include <string>                                                         
                                                                          
#include <boost/bind.hpp>                                                 
                                                                          
EchoClient::EchoClient(muduo::net::EventLoop* loop,                       
                       const muduo::net::InetAddress& addr)               
  : client_(loop, addr, "EchoClient"), count_(0), loop_(loop) {           
  client_.setConnectionCallback(                                          
      boost::bind(&EchoClient::onConnection, this, _1));                  
  client_.setMessageCallback(                                             
      boost::bind(&EchoClient::onMessage, this, _1, _2, _3));             
}                                                                         
                                                                          
void EchoClient::connect() {                                              
  client_.connect();                                                      
}                                                                         
                                                                          
void EchoClient::onConnection(const muduo::net::TcpConnectionPtr& conn) { 
  LOG_INFO << "EchoServer - " << conn->peerAddress().toIpPort() << " -> " 
           << conn->localAddress().toIpPort() << " is "                   
           << (conn->connected() ? "UP" : "DOWN");                        
  conn->setTcpNoDelay(true);                                              
  ++count_;                                                               
  muduo::string msg("Hello");                                             
  conn->send(msg);                                                        
  send_time_ = muduo::Timestamp::now();                                   
}                                                                         
                                                                          
void EchoClient::onMessage(const muduo::net::TcpConnectionPtr& conn,      
                           muduo::net::Buffer* buf,                       
                           muduo::Timestamp receive_time) {               
  ++count_;        
  muduo::string msg("Hello");                                                      
  conn->send(msg);                                                                 
  send_time_ = muduo::Timestamp::now();                                            
  loop_->runAfter(0.1,                                                             
                  boost::bind(&EchoClient::onTimeout, this, count_, receive_time));
}                                                                                  
                                                                                   
void EchoClient::onTimeout(uint64_t count, muduo::Timestamp receive_time) {        
  if (count == count_) {                                                           
    LOG_INFO << "seq: " << count << " timeout, receive_time: "                     
        << receive_time.toFormattedString()                                        
        << " send_time_: " << send_time_.toFormattedString();                      
  }                                                                                
}            `
对不起，没有把问题说清楚。
过程是client端收到server端发送来的消息之后，继续重新开始下一轮的发送消息。同时启动一个超时计时器。超时时间是100ms，如果100ms以内，Client端收到server的消息，就认为不超时，但是如果client端在100ms以内还没有收到server反馈的消息，就认为这条消息超时。
然后我在超时的时候，打印了下消息在poll拿到消息时的时间戳和client发送该消息时候的时间戳，可以从日志里看到，两者的时间差确实超过了100ms。
按我的理解，这种的超时有点多了。试图查过为何会超时，但是并没有找到真正的原因

**Comment by chenshuo** [comment]
在我的 Ubuntu 14.04 上，无法重现你描述的现象。

**Comment by echo0109** [comment]
我在Ubuntu14.10上测试了，还是有，但是比centos(6.5, 7.0,这两个版本我都试过了，这两个版本差不多的级别）的要少很多。差不多是几分钟一次。我自己再排查看看，感谢。
以下是我贴出来的Ubuntu 14.10上的超时情况。确实比Centos好很多
20170823 07:27:59.163992Z 20201 INFO  pid = 20201 - client_main.cc:11
20170823 07:27:59.164209Z 20201 INFO  TcpClient::TcpClient[EchoClient] - connector 0x76C590 - TcpClient.cc:71
20170823 07:27:59.164243Z 20201 INFO  TcpClient::connect[EchoClient] - connecting to 0.0.0.0:2007 - TcpClient.cc:109
20170823 07:27:59.164382Z 20201 INFO  EchoServer - 127.0.0.1:2007 -> 127.0.0.1:57762 is UP - echo_client.cc:23
20170823 07:29:50.848707Z 20201 ERROR seq: 1879794 timeout, send_time_: 20170823 07:29:50.714971 receive_time: 20170823 07:29:50.848695 now: 20170823 07:29:50.848698 - echo_client.cc:39
20170823 07:33:06.676333Z 20201 ERROR seq: 5180460 timeout, send_time_: 20170823 07:33:06.547034 receive_time: 20170823 07:33:06.676310 now: 20170823 07:33:06.676314 - echo_client.cc:39
20170823 07:33:06.973314Z 20201 ERROR seq: 5182370 timeout, send_time_: 20170823 07:33:06.787640 receive_time: 20170823 07:33:06.973305 now: 20170823 07:33:06.973309 - echo_client.cc:39
20170823 07:38:38.564841Z 20201 ERROR seq: 10814578 timeout, send_time_: 20170823 07:38:37.767119 receive_time: 20170823 07:38:38.564818 now: 20170823 07:38:38.564829 - echo_client.cc:39

**Comment by echo0109** [comment]
非常抱歉，查明了原因，是因为LOG打印太频繁了，导致影响了server。最后server端发消息发晚了。
库没有问题，我会关了这个issue
