### ISSUE TITLE
当使用短连接时,EventLoop::loop()比较繁忙,有没有方法优化?

### ISSUE THREAD

**Issue by jianghbwork** [chenshuo/muduo#295]
主线程运行下面代码,跑起来echoserver.
  EventLoop loop;
  InetAddress listenAddr(2007);
  int idleSeconds = 10;
  EchoServer server(&loop, listenAddr, idleSeconds);
  server.start();
  loop.loop();

那么,如果使用大量的使用 短连接,send,recv,然后close掉.
此时会发现,主线程的将异常繁忙,查看了EventLoop::loop()的代码,应该是这里面异常繁忙.
请问有没有比较好的方法解决,这里比较繁忙的话势必会影响整体的短连接处理能力.

**Comment by chenshuo** [comment]
Use SO_REUSEPORT to distribute loads to multiple threads if it's available to you.
Check examples/shorturl/shorturl.cc for example.
