### ISSUE TITLE
关于ThreadLocalSingleton.h中判断complete type的疑问

### ISSUE THREAD

**Issue by kangyijie5473** [chenshuo/muduo#301]
陈硕老师您好，买了您的书在学习网络编程，对muduo中的代码有些疑问，希望您能解答。  

在master分支的ThreadLocalSingleton.h中的destructor方法，为了判断是否为complete type，为什么不直接使用一个sizeof来进行判断呢 

```
  //ThreadLocalSingleton.h
  static void destructor(void* obj)
  {
    assert(obj == t_value_);
    typedef char T_must_be_complete_type[sizeof(T) == 0 ? -1 : 1];  //这里的作用是？
    T_must_be_complete_type dummy; (void) dummy;                     //dummy的作用是？
    delete t_value_;
    t_value_ = 0;
  }

```

**Comment by demiaowu** [comment]
这样编译期就能检查是不是有问题

**Comment by kangyijie5473** [comment]
是的，这样就可以完成编译期检查，我的意思是: 我不明白下面这两行代码的作用
```
typedef char T_must_be_complete_type[sizeof(T) == 0 ? -1 : 1]; 
T_must_be_complete_type dummy; (void) dummy;                  
```
如果只是为了判断T是否为一个complete type，那么直接通过sizeof来判断可以吗，如这样：
```
size_t temp = sizeof(T);
```
感谢您的回复。

**Comment by demiaowu** [comment]
你是可以通过size_t temp = sizeof(T)来判断，但是这个只能再运行期发现错误。而muduo的代码则是在编译器发现错误，所以肯定推荐muduo的做法，毕竟错误越早暴露越好。具体解释如下：
typedef char T_must_be_complete_type[sizeof(T) == 0 ? -1 : 1]; 
T_must_be_complete_type dummy; 
上面两行代码是为了实现编译期间发现incomplete type，因为如果是incomplete_type，那么这两句话就是：
1： typedef char T_must_be_complete_type[-1]; 
2： T_must_be_complete_type dummy;
那么编译器就会报错，因为sizeof在编译期间就完成了计算，实际上一般情况下 第1句就会报错。
(void) dummy; 
最后这句只是为了消除编译器的警告，因为T_must_be_complete_type dummy; 定义的dummy变量没被使用过，编译器就会发出警告，所以加上(void) dummy; 只是为了消除编译器警告，没有其它用途。

**Comment by kangyijie5473** [comment]
是的，我们都希望错误越早暴露越好，但就像您说的“sizeof在编译期间就完成了计算”，而我写的`size_t temp = sizeof(T)`同样也是编译期发现错误啊，毕竟只要使用到sizeof就可以在编译期找到错误。

当然，我这样写还是会报warning，感谢您的指导，可以通过强制类型转换消除warning，这一点我学到了。

**Comment by demiaowu** [comment]
1. sizeof(T)虽然在编译器完成了计算，但是不一定会报错，不一定~你可以把所有的incomplete type找过来试一下就知道了
2. warning是提示有定义的变量未被使用，（void）dummy只是简单的用一下，几乎没有消耗

**Comment by kangyijie5473** [comment]
好的，我想我明白了。
