### ISSUE TITLE
eclipse编译问题

### ISSUE THREAD

**Issue by BeijingWks** [chenshuo/muduo#303]
## Version of cmake, gcc and boost? (If not from distro.)
您好，
我是您的读者，也买了书。
我现在有个问题，想用eclipse+cdt的方式编译muduo库，net和base已经导入，但是发现在net/protorpc/RpcChannel.cc并没有<muduo/net/protorpc/rpc.pb.h>头文件。有些疑惑，多谢！@chenshuo

**Comment by chenshuo** [comment]
This is not an issue of muduo.
