### ISSUE TITLE
Append endless loop

### ISSUE THREAD

**Issue by demiaowu** [chenshuo/muduo#304]
## master

```
int main()
{
    std::string log("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb");
    std::string filename = "test.log";
    AppendFile logFile(filename);

    while (true)
    {
        logFile.append(log.c_str(), log.size());
    }
    return 0;
}
```
当磁盘写满之后，AppendFile.append()函数中的 size_t x = write（logline+n, remain）; 返回值 x 总是大于零，程序会陷入死循环。复现代码如上

**Comment by demiaowu** [comment]
当盘写满的时候：
```
size_t x = write（logline+n, remain）; 
```
x 返回值大于零，errno会被设置为ENOSPC（28），对应的error message: No space left on device
这样导致数据写入的假象，实际上盘已经满了，数据根本没有写入。理论上此处x应该返回 `0`才对。
```
void FileUtil::AppendFile::append(const char* logline, const size_t len)
{
  // 先写一次
  size_t n = write(logline, len);
  size_t remain = len - n;
  // 没写完，循环写
  while (remain > 0)
  {
    size_t x = write(logline + n, remain);
    if (x == 0)
    {
      int err = ferror(fp_);
      if (err)
      {
        fprintf(stderr, "AppendFile::append() failed %s\n", strerror_tl(err));
      }
      break;
    }
    n += x;
    remain = len - n; // remain -= x
  }

  writtenBytes_ += len;
}
```

**Comment by chenshuo** [comment]
你的程序本身是个死循环。
你认为在磁盘写满的情况下，AppendFile::append() 应该如何表现？

**Comment by demiaowu** [comment]
```
size_t x = write(logline + n, remain);
```
磁盘写满之后，这一句 x 应该返回0才对，但是实际上总是返回一个大于零的值。所以在磁盘写满之后，下面的代码不会进入错误判断逻辑
```
if (x == 0)
    {
      int err = ferror(fp_);
      if (err)
      {
        fprintf(stderr, "AppendFile::append() failed %s\n", strerror_tl(err));
      }
      break;
    }
```

**Comment by chenshuo** [comment]
我认为磁盘写满这种情况不应该由日志库来处理，它除了向 stderr 报错，没有别的手段。而服务器程序的 stderr 通常是重定向到磁盘文件的，既然磁盘满了，数据也写不到文件中，于是错误信息也石沉大海。
像磁盘写满这种错误，应该由你的监控系统来报警，在它真正变满之前就采取措施预防错误发生。

**Comment by demiaowu** [comment]
其实不是讨论AppendFile是否应该负责处理的问题。而是这里fwrite在磁盘的错误情况下，没能返回0，导致代码没能进入错误处理代码，也就是上面贴出来if (x == 0)部分。所以这里建议使用write，至少在我的测试中write没有这个问题，能在磁盘满的情况正确的返回-1，而不是fwrite在磁盘写满之后，没有返回预期的0。（当然这是我这边的测试结果，不清楚是不是fwrite的问题）

**Comment by chenshuo** [comment]
在磁盘写满的情况下，代码是否进入错误处理分支有什么区别吗？你用的是哪个版本的 glibc 有这个问题？
如果用 write，那每次 append 都是系统调用，会增加开销。

**Comment by demiaowu** [comment]
测过两个glibc的版本，一个是ldd (Ubuntu GLIBC 2.23-0ubuntu9) 2.23，还有一个机器不在手边上，后面补充~
