### ISSUE TITLE
EventLoop::runInLoop(Functor cb)  could be dead loop

### ISSUE THREAD

**Issue by xiefan0716** [chenshuo/muduo#312]
```
void EventLoop::runInLoop(Functor cb)  
{
  if (isInLoopThread())  //this can result in dead loop
  {
    cb();
  }
  else
  {
    queueInLoop(std::move(cb));
  }
}
```
Example:
```
EventLoop* g_loop;
void callback_A();
void callback_B();

void callback_A()
{
  g_loop->runInLoop(callback_B);
}

void callback_B()
{
  g_loop->runInLoop(callback_A);
}

int main()
{
  EventLoop loop;
  g_loop = &loop;
  loop.runInLoop(callback_A);
  loop.loop();
}
```

**Comment by chenshuo** [comment]
This is not an issue.
EventLoop::queueInLoop() is designed for this.

**Comment by xiefan0716** [comment]
由于用户编写了错误的代码，导致doPendingFunctors()陷入死循环，这个确实不是框架的问题。
但是EventLoop::runInLoop区分执行时机，是否是过度设计? 
明确告诉调用者，从doPendingFunctors内部再添加的回调，将于下一个调度周期执行，是否会好些?

**Comment by chenshuo** [comment]
1. 不是过度设计。为单线程程序提供 fast path 是常见的需求，如果 muduo 不提供，用户就会自己去实现（判断是否 isInLoopThread()，再决定是直接调用还是跨线程调用）。
2. queueInLoop() 正是“明确告诉调用者，将于下一个调度周期执行”，如果你觉得 runInLoop() 不符合你的预期，可以只用 queueInLoop()。
