### ISSUE TITLE
对端异常关闭连接会有fd泄露的问题？

### ISSUE THREAD

**Issue by Ricardo666666** [chenshuo/muduo#314]
## Linux distro and version? 32-bit or 64-bit?
ubuntu16.04 64-bit
## Branch and version of muduo?
master最新版
## Version of cmake, gcc and boost? (If not from distro.)
cmake3.9.6 gcc 5.4.0 boost最新版

被动关闭连接时，只有在handleRead返回0才会调用handleClose关闭TCP连接，close(fd)。假如对端发送RST把连接重置的话，handleRead返回-1，conncallback调不到，那这样这个fd不就永远泄露了？

**Comment by chenshuo** [comment]
Can you reproduce it?

**Comment by wilkenli** [comment]
这类问题可以通过空闲链接剔除的机制来解决。
不知道作者在handleRead返回小于0时，没有关闭链接是不是这样考虑的？

服务端出现空闲链接的场景：
client在建立链接之后，把网线拔掉或者关掉网络，此时server是收不到数据包的（亲测：同时可以看出tcp的连接是虚拟的），服务端fd如果没有处理，会一直存在，造成泄露。

**Comment by chenshuo** [comment]
read() 如果由于对方 RST 而返回 -1，那么这个 fd 会保持 readable 状态，下一次 read() 会返回 0，然后就走正常关闭连接的流程了。
因此我一开始就问他能不能复现“fd 泄漏”这个情况。
