### ISSUE TITLE
boost-1.66.0 breaks the build

### ISSUE THREAD

**Issue by jghodd** [chenshuo/muduo#315]
## Linux distro and version? x86 or ARM? 32-bit or 64-bit?
arch linux 4.14.13 x86_64

## Branch (master/cpp11/cpp17) and version of muduo?
master

## Version of cmake, gcc and boost? (If not from distro.)
cmake-3.10.1
gcc-7.2.1
boost-1.66.0

[build.log](https://github.com/chenshuo/muduo/files/1640845/build.log)

**Comment by chenshuo** [comment]
Try the cpp11 branch, because gcc-6 enables C++14 by default.

**Comment by jghodd** [comment]
That did it. The cpp11 branch builds just fine. Thanks much.
