### ISSUE TITLE
在判断deque.empty()之前，是否应该加锁，保证此时没有其他线程在生成线程池？

### ISSUE THREAD

**Issue by guhowo** [chenshuo/muduo#321]
https://github.com/chenshuo/muduo/blob/7c2474bdf568f7ac7a6c8fbb5ace653e8881206a/muduo/base/ThreadPool.cc#L94
陈老师你好，我还有一个疑问：从原子性角度触发总觉得该给<Task> deque_加锁？有点冒昧，sorry;)

**Comment by chenshuo** [comment]
你说的是哪个 `deque`？`ThreadPool` 没有 `deque_` 成员。
如果你说的是 `queue_`，那么每次访问都是加了锁的。
如果你说的是 `threads_`，它是个 `vector`，不是 `deque`。
`ThreadPool` 的正常用法是在 `start()` 之后才调用其 `run()`，根据 pthread_create 的 happens-before 语意，访问 `threads_` 不必加锁。

**Comment by guhowo** [comment]
你好，我说的是boost::ptr_vector<muduo::Thread> threads_; 还真不是deque_。谢纠正。
