### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by huangxx21** [chenshuo/muduo#323]
用法：
INT32_T CGytpCmdMuduoServer::startFtsMuduoServer(void)
{
    if ((mpMuduoEvetnLoop == NULL_PTR) || (mnListentPort == 0U))
    {
        GYT_LOGGER_ERROR("GytpCmdMuduoServer mpMuduoEvetnLoop is NULL or listen port=0");
        return E_ERROR_NO_OBJ;
    }
    //监听端口号
    UINT16_T temppotr = static_cast<UINT16_T>(mnListentPort);
    MODUO_INETADDR_T listenAddr(temppotr);
    NEW_OBJ(mpMuduoTcpServer, MODUO_TCPSERVER_T, mpMuduoEvetnLoop, listenAddr, mstrServerName);
    if (mpMuduoTcpServer == NULL_PTR)
    {
        GYT_LOGGER_ERROR(Poco::format("Create Gytp cmd muduo tcp server failed, error no:[ %d ]", E_ERROR_NO_OBJ).c_str());
        return E_ERROR_NO_OBJ;
    }

    //绑定回调函数
    mpMuduoTcpServer->setConnectionCallback(boost::bind(&CGytpCmdMuduoServer::onClientConnect, this, _1));
    mpMuduoTcpServer->setMessageCallback(boost::bind(&CGytpCmdMuduoServer::onReceiveBuf, this, _1, _2, _3));
    //
    mpMuduoTcpServer->setThreadNum(mnNumThreads);
    GYT_LOGGER_DEBUG(Poco::format("start server for listenting port:[ %d ], subreactor num:[ %d ]", (INT32_T)mnListentPort, mnNumThreads).c_str());
    //启动
    mpMuduoTcpServer->start();
    return E_ERROR_NO_NONE;
}

运行一段时间后崩了
Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fbbbc4e2700 (LWP 9092)]
0x00007fbbda3785f7 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007fbbda3785f7 in raise () from /lib64/libc.so.6
#1  0x00007fbbda379ce8 in abort () from /lib64/libc.so.6
#2  0x00000000004a331b in muduo::Logger::~Logger (this=0x7fbbbc4cb0c0, __in_chrg=<optimized out>) at /opt/muduo/muduo-1.0.9/muduo/base/Logging.cc:200
#3  0x000000000048dc57 in muduo::net::EPollPoller::update (this=this@entry=0x2033c40, operation=operation@entry=3, channel=channel@entry=0x1fa8110) at /opt/muduo/muduo-1.0.9/muduo/net/poller/EPollPoller.cc:190
#4  0x000000000048e5c9 in muduo::net::EPollPoller::updateChannel (this=0x2033c40, channel=0x1fa8110) at /opt/muduo/muduo-1.0.9/muduo/net/poller/EPollPoller.cc:147
#5  0x00000000004961f5 in enableWriting (this=<optimized out>) at /opt/muduo/muduo-1.0.9/muduo/net/Channel.h:75
#6  muduo::net::TcpConnection::sendInLoop (this=0xc1d1a60, data=<optimized out>, len=<optimized out>) at /opt/muduo/muduo-1.0.9/muduo/net/TcpConnection.cc:189
#7  0x0000000000497887 in sendInLoop (message=..., this=0xc1d1a60) at /opt/muduo/muduo-1.0.9/muduo/net/TcpConnection.cc:136
#8  muduo::net::TcpConnection::send (this=0xc1d1a60, message=...) at /opt/muduo/muduo-1.0.9/muduo/net/TcpConnection.cc:100
#9  0x00000000004979d4 in muduo::net::TcpConnection::send (this=<optimized out>, data=<optimized out>, len=<optimized out>) at /opt/muduo/muduo-1.0.9/muduo/net/TcpConnection.cc:91
#10 0x000000000047d37e in CGytpDataMuduoServer::doSendDataToClient (this=0x1f710a0, conn=..., sessstate=@0x10fc8d38: 2, sesscontent="", sess=..., protype=@0x10fc8d3c: E_FTS_PROTOCOL_TYPE_GYTPS, cmdconn=...) at ../src/server/ftsNetServerUtil.cpp:2537
#11 0x000000000047980a in CGytpDataMuduoServer::onClientConnect (this=0x1f710a0, conn=...) at ../src/server/ftsNetServerUtil.cpp:2096
#12 0x0000000000485294 in boost::_mfi::mf1<void, CGytpDataMuduoServer, boost::shared_ptr<muduo::net::TcpConnection> const&>::operator() (this=0xc1d1af0, p=0x1f710a0, a1=...) at ../third_party/boost/include/boost/bind/mem_fn_template.hpp:165
#13 0x0000000000484375 in boost::_bi::list2<boost::_bi::value<CGytpDataMuduoServer*>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, CGytpDataMuduoServer, boost::shared_ptr<muduo::net::TcpConnection> const&>, boost::_bi::rrlist1<boost::shared_ptr<muduo::net::TcpConnection> const&> > (this=0xc1d1b00, f=..., a=...) at ../third_party/boost/include/boost/bind/bind.hpp:319
#14 0x0000000000483842 in boost::_bi::bind_t<void, boost::_mfi::mf1<void, CGytpDataMuduoServer, boost::shared_ptr<muduo::net::TcpConnection> const&>, boost::_bi::list2<boost::_bi::value<CGytpDataMuduoServer*>, boost::arg<1> > >::operator()<boost::shared_ptr<muduo::net::TcpConnection> const&> (this=0xc1d1af0, a1=...) at ../third_party/boost/include/boost/bind/bind.hpp:1306
#15 0x0000000000482beb in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, CGytpDataMuduoServer, boost::shared_ptr<muduo::net::TcpConnection> const&>, boost::_bi::list2<boost::_bi::value<CGytpDataMuduoServer*>, boost::arg<1> > >, void, boost::shared_ptr<muduo::net::TcpConnection> const&>::invoke (function_obj_ptr=..., a0=...) at ../third_party/boost/include/boost/function/function_template.hpp:159
#16 0x0000000000494c65 in operator() (a0=..., this=0xc1d1ae8) at /usr/local/include/boost/function/function_template.hpp:771
#17 muduo::net::TcpConnection::connectEstablished (this=0xc1d1a60) at /opt/muduo/muduo-1.0.9/muduo/net/TcpConnection.cc:331
#18 0x000000000048b971 in operator() (this=0x1435e340) at /usr/local/include/boost/function/function_template.hpp:771
#19 muduo::net::EventLoop::doPendingFunctors (this=this@entry=0x7fbbbc4d1b10) at /opt/muduo/muduo-1.0.9/muduo/net/EventLoop.cc:311
#20 0x000000000048bb4f in muduo::net::EventLoop::loop (this=this@entry=0x7fbbbc4d1b10) at /opt/muduo/muduo-1.0.9/muduo/net/EventLoop.cc:129
#21 0x00000000004a2ca8 in muduo::net::EventLoopThread::threadFunc (this=0x2046b60) at /opt/muduo/muduo-1.0.9/muduo/net/EventLoopThread.cc:73
#22 0x00000000004a7088 in operator() (this=0x1ff5f20) at /usr/local/include/boost/function/function_template.hpp:771
#23 runInThread (this=0x1ff5f20) at /opt/muduo/muduo-1.0.9/muduo/base/Thread.cc:94
#24 muduo::detail::startThread (obj=0x1ff5f20) at /opt/muduo/muduo-1.0.9/muduo/base/Thread.cc:124
#25 0x00007fbbdeb77dc5 in start_thread () from /lib64/libpthread.so.0
#26 0x00007fbbda43921d in clone () from /lib64/libc.so.6

**Comment by chenshuo** [comment]
请提供 Short, Self Contained, Compilable, Example 以复现故障。
zhuanlan.zhihu.com/p/20752519
