### ISSUE TITLE
网络很差的情况下，反复重传，导致数据流阻塞怎么处理？

### ISSUE THREAD

**Issue by oucaijun** [chenshuo/muduo#325]
## Linux distro and version? x86 or ARM? 32-bit or 64-bit?
ARM 32-bit
## Branch (master/cpp11/cpp17) and version of muduo?
cpp11
## Version of cmake, gcc and boost? (If not from distro.)

![ez8 av i fuzk7na q20](https://user-images.githubusercontent.com/5211072/39565993-a12e2d38-4eec-11e8-9179-127bdafd3d24.png)

**Comment by oucaijun** [comment]
代码架构参考muduo\examples\protobuf\codec
使用codec_.send(conn, *messageToSend) 传数据流，每秒约传1000字节，抓包如图，一直重传。

**Comment by oucaijun** [comment]
我的网卡是中兴4G模块，使用电信4G卡，信号差的时候极易出现卡死。

**Comment by 522623905** [comment]
我也是。。不知道这种情况怎么解决，我这边网卡有问题，每秒超过400字节，就一直重传了

**Comment by chenshuo** [comment]
It's not an issue of muduo.
