### ISSUE TITLE
找不到<muduo/net/protorpc/google-inl.h>头文件

### ISSUE THREAD

**Issue by leitmily** [chenshuo/muduo#326]
linux下编译安装完成后在release-install/include/muduo/net/protorpc目录下没有google-inl.h头文件，只能从源码中拷贝过来。
还有在编译protobuf扩展包的时候不能安装protobuf-compiler和libprotobuf-dev，不然编译失败，只能从protobuf的源码编译安装

**Comment by chenshuo** [comment]
Version and branch of muduo?
Version of protobuf?
