### ISSUE TITLE
请问什么情况下用Bounded Blockingqueue呢？因为我看到很多项目都是多线程配合Blockingqueue使用的？我换成Bounded Blockingqueue后也没有发现异常。使用Bounded之后，如果是快的生产者和慢的消费者，会导致producer阻塞吧？谢谢

### ISSUE THREAD

**Issue by guhowo** [chenshuo/muduo#330]
https://github.com/chenshuo/muduo/blob/a3327e24f43c9ef7bcd9a16235da1c779b2d111e/muduo/base/BoundedBlockingQueue.h#L20

**Comment by shawvi** [comment]
https://blog.csdn.net/kangroger/article/details/47129139
