### ISSUE TITLE
在CentOS上编译源码的问题

### ISSUE THREAD

**Issue by SJunTer** [chenshuo/muduo#331]
## Linux distro and version? x86 or ARM? 32-bit or 64-bit?
CentOS 7.5 3.10.0-693.el7.x86_64
## Branch (master/cpp11/cpp17) and version of muduo?
master, muduo v1.1.0
## Version of cmake, gcc and boost? (If not from distro.)
cmake 2.8.12.2, gcc 4.8.5, boost 1.67.0

安装了最新版本的boost 1.67.0编译net/AsyncLogging.cc时出现`static_ptr_move`类型不匹配等错误。换成boost 1.57.0后解决。
之后编译net/FileUtil.cc提示`off_t`类型找不到，临时加了<sys/types.h>可以通过，望修正。

**Comment by lqxandxl** [comment]
用1.5.7可以，我自己的是centos6.9 4.17.0-1.el6.elrepo.x86_64，gcc4.4.7，boost换成1.4.1或者1.6.7都不行。不过后面这个net/FileUtil.cc没有遇到相关的问题。顺便问一下，protobuf需要特定的版本吗？如果补充上依赖的库版本号就好了。
