### ISSUE TITLE
compile failed because cannot find -lpthreads

### ISSUE THREAD

**Issue by wpp2014** [chenshuo/muduo#338]
My system is Ubuntu 18.04 x64, the version of gcc is 7.3.0, the version of cmake is 3.10.2, the branch is cpp11.
[CMakeError.log](https://github.com/chenshuo/muduo/files/2173835/CMakeError.log)
[CMakeOutput.log](https://github.com/chenshuo/muduo/files/2173836/CMakeOutput.log)

**Comment by feihongmeilian** [comment]
sudo apt install libboost-dev libprotobuf-dev

**Comment by wpp2014** [comment]
Thanks，this problem is solved.
