### ISSUE TITLE
关于 TcpConnection::sendInLoop 内 高水位标 问题

### ISSUE THREAD

**Issue by andylau004** [chenshuo/muduo#340]
void TcpConnection::sendInLoop(const void* data, size_t len)
{
。。。
    assert(remaining <= len);
    // 没有错误，并且还有未写完的数据（说明内核发送缓冲区满，要将未写完的数据添加到output buffer中）
    if (!faultError && remaining > 0)
    {
        /* 获取写缓冲区数据总量 */
        size_t oldLen = outputBuffer_.readableBytes();

        // 如果超过highWaterMark_（高水位标），回调highWaterMarkCallback_
        if (oldLen + remaining >= highWaterMark_
                && oldLen < highWaterMark_
                && highWaterMarkCallback_)
        {
            loop_->queueInLoop(boost::bind(highWaterMarkCallback_, shared_from_this(), oldLen + remaining));
        }

        //把没有写完的数据追加到输出缓冲区中，然后开启对可写事件的监听（如果之前没开的话）
        //下次调用send 也会将数据添加到outputBuffer_ 的末尾而不直接write），并关注POLLOUT 事件，当内核发送缓冲区不为满，即发生
        outputBuffer_.append(static_cast<const char*>(data)+nwrote, remaining);
        if (!channel_->isWriting())
        {
            //可写事件，调用TcpConnection::handleWrite()
            channel_->enableWriting(); // 关注POLLOUT事件
        }
    }
}

 上面是我整理的TcpConnection::sendInLoop 代码。

发现在TcpConnection::sendInLoop 函数内，
        /* 获取写缓冲区数据总量 */
        size_t oldLen = outputBuffer_.readableBytes();

        // 如果超过highWaterMark_（高水位标），回调highWaterMarkCallback_
        if (oldLen + remaining >= highWaterMark_
                && oldLen < highWaterMark_
                && highWaterMarkCallback_)
        {
            loop_->queueInLoop(boost::bind(highWaterMarkCallback_, shared_from_this(), oldLen + remaining));
        }

这块不是很理解。
如果代码走到这个位置，说明，发送数据没有错误，但是没能够一次write发送完给对方，
这个时候，有个if (oldLen + remaining >= highWaterMark_ 来判断是否大于高水位标志。

oldLen 是 要发送数据整个长度（因为没有outputBuffer_.retrieve），所以可以认为是 outputBuffer内所有待发送数据长度。
此处为什么 用 oldLen + remaining（还剩下没发送长度） 这两个长度相加 ，  再跟 highWaterMark_ 想比较。 此处不是太理解。有没有比较了解这块的，多谢指点。

**Comment by andylau004** [comment]
@giantchen @chenshuo @zieckey 请教了。

**Comment by andylau004** [comment]
自己顶下。

**Comment by andylau004** [comment]
@lilijreey　
了解么，帮忙看看。

**Comment by andylau004** [comment]
@zieckey  魏哥了解这个么？请教了。

**Comment by chenshuo** [comment]
This is not an issue of muduo.
