### ISSUE TITLE
Cancel 定时器的问题

### ISSUE THREAD

**Issue by jucai** [chenshuo/muduo#344]
void TimerQueue::cancelInLoop(TimerId timerId)
{
  loop_->assertInLoopThread();
  assert(timers_.size() == activeTimers_.size());
  ActiveTimer timer(timerId.timer_, timerId.sequence_);
  ActiveTimerSet::iterator it = activeTimers_.find(timer);
  if (it != activeTimers_.end())
  {
    size_t n = timers_.erase(Entry(it->first->expiration(), it->first));
    assert(n == 1); (void)n;
    delete it->first; // FIXME: no delete please
    activeTimers_.erase(it);
  }
  else if (callingExpiredTimers_)
  {
    cancelingTimers_.insert(timer);
  }
  assert(timers_.size() == activeTimers_.size());
}

这里如果检测到callingExpiredTimers_为true，就放到一个列表中，等待被删除。但其实handleRead() 和 cancelInLoop() 都在同一个线程中执行，他们不会同时被两个线程执行，所以callingExpiredTimers_ 貌似永远为false， 这样是不是没达到cancel timer的目的呢？

**Comment by chenshuo** [comment]
书第 331 页。

**Comment by jucai** [comment]
@chenshuo 明白了，感谢！
