### ISSUE TITLE
1.0.0编译出错

### ISSUE THREAD

**Issue by rwxdfbb** [chenshuo/muduo#35]
系统：ubuntu12.04
cmake版本：2.8.7
boost版本：1.53
gcc，g++版本：4.6.4

之前编译0.9.3版本没问题，按照编译说明，执行./build.sh -j2，报错如下（最后部分截取）：

/usr/local/boost_1_53_0/boost/ptr_container/detail/move.hpp: 在构造函数‘boost::ptr_container_detail::move_ptrs::move_source<Ptr>::move_source(Ptr&) [with Ptr = boost::ptr_container_detail::static_move_ptrmuduo::detail::FixedBuffer<4000000, boost::ptr_container_detail::clone_deleterboost::ptr_container_detail::reversible_ptr_container<boost::ptr_container_detail::sequence_config<muduo::detail::FixedBuffer<4000000, std::vector<void*, std::allocator<void*> > >, boost::heap_clone_allocator>::null_clone_allocator<false> > >]’中:
/usr/local/boost_1_53_0/boost/ptr_container/detail/move.hpp:39:37：自‘boost::ptr_container_detail::move_ptrs::move_source<T> boost::ptr_container_detail::move(T&) [with T = boost::ptr_container_detail::static_move_ptrmuduo::detail::FixedBuffer<4000000, boost::ptr_container_detail::clone_deleterboost::ptr_container_detail::reversible_ptr_container<boost::ptr_container_detail::sequence_config<muduo::detail::FixedBuffer<4000000, std::vector<void*, std::allocator<void*> > >, boost::heap_clone_allocator>::null_clone_allocator<false> > >]’实例化
/home/sourcetest/muduo/muduo/base/AsyncLogging.cc:42:62：从此处实例化
/usr/local/boost_1_53_0/boost/ptr_container/detail/move.hpp:23:5: 错误： ‘ptr’的声明隐藏了‘this’的一个成员 [-Werror=shadow]
cc1plus: all warnings being treated as errors
make[2]: **\* [muduo/base/CMakeFiles/muduo_base_cpp11.dir/AsyncLogging.cc.o] 错误 1
make[2]: **\* 正在等待未完成的任务....
make[1]: **\* [muduo/base/CMakeFiles/muduo_base_cpp11.dir/all] 错误 2
make: **\* [all] 错误 2

**Comment by lin1314** [comment]
-Werror 是这个东西的原因吧, 什么boost bug? 我把它从CMakeLists.txt里注释掉 有啥影响吗?

**Comment by Tridu33** [comment]
我也出现这个问题了，我卸载了boost1.73换成boost1.55即可
