### ISSUE TITLE
想不懂为啥要使用boost库...

### ISSUE THREAD

**Issue by susahdh** [chenshuo/muduo#360]

**Comment by yifanernei** [comment]
muduo发布时，c++11标准还没有吧
更不要说库的开发是经过了更早前很长时间才能成型

**Comment by yifanernei** [comment]
在没有c11之前，boost的很多特性（智能指针，线程，bind，any等等）还是能极大的降低开发难度的（学习也需要成本，但是是值得的），当然也可以不用，自己去实现需要的特性。放弃boost为了实现兼容、通用而做的处理，自己实现的版本会更适合自己的需求，也会简单的多。
但是boost的实现思路都是结晶啊，大部分情况下自己造的轮子从性能，可靠性上肯定都要弱一些。
即使不直接使用muduo，它实现的一些思路、小技巧也是可以参考借鉴的，没必要非得用它的完整版不是，关键是从中能吸取到什么。

李智胜

kris.huang <notifications@github.com> 于 2018年11月19日周一 19:45写道：

**Comment by chenshuo** [comment]
This is not a forum.
