### ISSUE TITLE
我想添加webSocket server支持

### ISSUE THREAD

**Issue by Zhu-Pei** [chenshuo/muduo#362]
我想把webSocket server实现为类似TCP server的类，我在实现的时候创建了一个webSocket server 和 webSocketConnection类，并各自包含一个TCPserver和Tcpconnection的指针；然后我发现这样会有很多问题比如可写事件回调时机,webSocketConnection的生命期之类的。所以我就想尝试通过继承来实现，这样是一个好主意吗？我看您的书说不提倡用继承解决问题，那我主要应该考虑哪些问题呢？

**Comment by chenshuo** [comment]
This is not a forum.
