### ISSUE TITLE
我遇到个奇怪的问题，编译出来的软件在不同机器上会崩溃，目前没有找到问题原因是什么，先贴出问题，

### ISSUE THREAD

**Issue by w2q1227** [chenshuo/muduo#365]
InetAddress.cc 的 InetAddress::toIpPort() 函数修改（加上了日志）
string InetAddress::toIpPort() const
{
  char buf[64] = "";
  sockets::toIpPort(buf, sizeof buf, getSockAddr());
  LOG_INFO<<"buftotle:"<<buf;
  return buf;
  // return "0.0.0.0:1995";
}
SocketsOps.cc sockets::toIpPort和sockets::toIp函数，加上日志
void sockets::toIpPort(char* buf, size_t size,
                       const struct sockaddr* addr)
{
  toIp(buf,size, addr);
  size_t end = ::strlen(buf);
  const struct sockaddr_in* addr4 = sockaddr_in_cast(addr);
  uint16_t port = sockets::networkToHost16(addr4->sin_port);
  assert(size > end);
  LOG_INFO<<"port:"<<port;
  LOG_INFO<<"buf:"<<buf;
  LOG_INFO<<"end:"<<end;
  LOG_INFO<<"size:"<<size;
  snprintf(buf+end, size-end, ":%u", port);
  LOG_INFO<<"bufover:"<<buf;
}

void sockets::toIp(char* buf, size_t size,
                   const struct sockaddr* addr)
{
  LOG_INFO<<"addr->sa_family:"<<addr->sa_family<<"\nAF_INET:"<<AF_INET;
  if (addr->sa_family == AF_INET)
  {
    assert(size >= INET_ADDRSTRLEN);
    const struct sockaddr_in* addr4 = sockaddr_in_cast(addr);
    ::inet_ntop(AF_INET, &addr4->sin_addr, buf, static_cast<socklen_t>(size));
    LOG_INFO<<"&addr4->sin_addr:"<<&addr4->sin_addr;
    LOG_INFO<<"buf:"<<buf;
    LOG_INFO<<"static_cast<socklen_t>(size):"<<static_cast<socklen_t>(size);
  }
  else if (addr->sa_family == AF_INET6)
  {
    assert(size >= INET6_ADDRSTRLEN);
    const struct sockaddr_in6* addr6 = sockaddr_in6_cast(addr);
    ::inet_ntop(AF_INET6, &addr6->sin6_addr, buf, static_cast<socklen_t>(size));
  }
}

正常情况下调用会这样子打印 （编辑机）
20181129 10:42:22.371654Z 32125 INFO  addr->sa_family:2
AF_INET:2 - SocketsOps.cc:214
20181129 10:42:22.371720Z 32125 INFO  &addr4->sin_addr:0x7FFFBA110904 - SocketsOps.cc:220
20181129 10:42:22.373312Z 32125 INFO  buf:0.0.0.0 - SocketsOps.cc:221
20181129 10:42:22.374174Z 32125 INFO  static_cast<socklen_t>(size):64 - SocketsOps.cc:222
20181129 10:42:22.374672Z 32125 INFO  port:1995 - SocketsOps.cc:203
20181129 10:42:22.375198Z 32125 INFO  buf:0.0.0.0 - SocketsOps.cc:204
20181129 10:42:22.375579Z 32125 INFO  end:7 - SocketsOps.cc:205
20181129 10:42:22.375924Z 32125 INFO  size:64 - SocketsOps.cc:206
20181129 10:42:22.376003Z 32125 INFO  bufover:0.0.0.0:1995 - SocketsOps.cc:208
20181129 10:42:22.376010Z 32125 INFO  buftotle:0.0.0.0:1995 - InetAddress.cc:96
当程序换测试主机时候这样子的
20181129 10:22:38.949409Z 32846 INFO  addr->sa_family:2
AF_INET:2 - SocketsOps.cc:214
20181129 10:22:38.949448Z 32846 INFO  &addr4->sin_addr:0x7FFD5F842E64 - SocketsOps.cc:220
20181129 10:22:38.949453Z 32846 INFO  buf:0.0.0.0 - SocketsOps.cc:221
20181129 10:22:38.949460Z 32846 INFO  static_cast<socklen_t>(size):64 - SocketsOps.cc:222
20181129 10:22:38.949465Z 32846 INFO  port:1995 - SocketsOps.cc:203
20181129 10:22:38.949470Z 32846 INFO  buf:0.0.0.0 - SocketsOps.cc:204
20181129 10:22:38.949474Z 32846 INFO  end:7 - SocketsOps.cc:205
20181129 10:22:38.949479Z 32846 INFO  size:64 - SocketsOps.cc:206
20181129 10:22:38.949484Z 32846 INFO  bufover:0.0.0.0:1995 - SocketsOps.cc:208
非法指令
gdb如下
0x00000000004374a6 in std::char_traits<char>::length (__s=0x7fffffffe250 "0.0.0.0:1995") at /usr/include/c++/5/bits/char_traits.h:267
267	      { return __builtin_strlen(__s); }
(gdb) bt
#0  0x00000000004374a6 in std::char_traits<char>::length (__s=0x7fffffffe250 "0.0.0.0:1995") at /usr/include/c++/5/bits/char_traits.h:267
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (__a=..., __s=0x7fffffffe250 "0.0.0.0:1995", this=0x7fffffffe2f0)
    at /usr/include/c++/5/bits/basic_string.h:456
#2  muduo::net::InetAddress::toIpPort[abi:cxx11]() const (this=<optimized out>) at /home/w27/muduo-master/muduo/net/InetAddress.cc:96
#3  0x000000000040ecf0 in main () at main.cpp:282

初步判断是在 测试主机 时指针出了问题，但是不明白在不改源码的情况下怎么样避免这个问题，希望得到解答

**Comment by chenshuo** [comment]
把 https://github.com/chenshuo/muduo/blob/master/CMakeLists.txt#L28 的 -march=native 注释掉，再重新编译。
或者把根据你的最老的 CPU 型号来调整这一行参数。

**Comment by w2q1227** [comment]
解决了，多谢陈硕大大
