### ISSUE TITLE
Muduo exmaple compile error please

### ISSUE THREAD

**Issue by kbi12** [chenshuo/muduo#369]
**The muduo library building succeeded.**

I copied the muduo example source and compiled it in my workspace

```
g++ -std="c++11" -c echo.cpp main.cpp -I/home/MuduoWorkspace/build/release-install-cpp11/include -L/home/MuduoWorkspace/build/release-install-cpp11/lib

g++ -std="c++11" -o out echo.o main.o -I/home/MuduoWorkspace/build/release-install-cpp11/include -L/home/MuduoWorkspace/build/release-install-cpp11/lib
```

 The following error occurred.

echo.o: In function `EchoServer :: EchoServer (muduo :: net :: EventLoop *, muduo :: net :: InetAddress const &) '
echo.cpp :( text + 0x82): undefined reference to `muduo :: net :: TcpServer :: TcpServer (muduo :: net :: EventLoop *, muduo :: net :: InetAddress const &, std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>> const &, muduo :: net :: TcpServer :: Option)
echo.cpp: (. text + 0x22c): undefined reference to `muduo :: net :: TcpServer :: ~ TcpServer () '
echo.o: In function `EchoServer :: start () ':
echo.cpp :(. text + 0x266): undefined reference to `muduo :: net :: TcpServer :: start ()
echo.o: In function `EchoServer :: onConnection (std :: shared_ptr <muduo :: net :: TcpConnection> const &) '
echo.cpp: (. text + 0x2f9): undefined reference to `muduo :: net :: InetAddress :: toIpPort [abi: cxx11] () const '
echo.cpp: (. text + 0x325): undefined reference to `muduo :: net :: InetAddress :: toIpPort [abi: cxx11] () const '
echo.cpp: (. text + 0x35b): undefined reference to `muduo :: Logger :: Logger (muduo :: Logger :: SourceFile, int)
echo.cpp: (. text + 0x3d5): undefined reference to `muduo :: Logger :: ~ Logger () '
echo.cpp: (. text + 0x407): undefined reference to `muduo :: Logger :: ~ Logger () '
echo.o: In function `EchoServer :: onMessage (std :: shared_ptr <muduo :: net :: TcpConnection> const &, muduo :: net :: Buffer *, muduo :: Timestamp) ':
echo.cpp: (. text + 0x4d8): undefined reference to `muduo :: Timestamp :: toString [abi: cxx11] () const '
echo.cpp: (. text + 0x53a): undefined reference to `muduo :: Logger :: Logger (muduo :: Logger :: SourceFile, int)
echo.cpp: (. text + 0x56c): undefined reference to `muduo :: LogStream :: operator << (unsigned long) '
echo.cpp: (. text + 0x5aa): undefined reference to `muduo :: Logger :: ~ Logger () '
echo.cpp: (. text + 0x5f6): undefined reference to `muduo :: net :: TcpConnection :: send (muduo :: StringPiece const &) '
echo.cpp: (. text + 0x629): undefined reference to `muduo :: Logger :: ~ Logger () '
echo.o: In function `muduo :: Logger :: logLevel () ':
echo.cpp :(. text._ZN5muduo6Logger8logLevelEv [_ZN5muduo6Logger8logLevelEv] + 0x6): undefined reference to `muduo :: g_logLevel '
main.o: In function `main ':
main.cpp: (. text + 0x63): undefined reference to `muduo :: Logger :: Logger (muduo :: Logger :: SourceFile, int)
main.cpp: (. text + 0x89): undefined reference to `muduo :: LogStream :: operator << (int)
main.cpp: (. text + 0x98): undefined reference to `muduo :: Logger :: ~ Logger () '
main.cpp :(. text + 0xa7): undefined reference to `muduo :: net :: EventLoop :: EventLoop ()
main.cpp: (. text + 0xc5): undefined reference to `muduo :: net :: InetAddress :: InetAddress (unsigned short, bool, bool) '
main.cpp :(. text + 0x103): undefined reference to `muduo :: net :: EventLoop :: loop ()
main.cpp :(. text + 0x121): undefined reference to `muduo :: net :: EventLoop :: ~ EventLoop ()
main.cpp: (. text + 0x149): undefined reference to `muduo :: Logger :: ~ Logger () '
main.cpp :(. text + 0x17a): undefined reference to `muduo :: net :: EventLoop :: ~ EventLoop ()
main.o: In function `EchoServer :: ~ EchoServer () ':
main.cpp :(. text._ZN10EchoServerD2Ev [_ZN10EchoServerD5Ev] + 0x14): undefined reference to `muduo :: net :: TcpServer :: ~ TcpServer () '
collect2: error: ld returned 1 exit status

Thank you for your help.

g ++ version: 5.60

**Comment by zhangyu0310** [comment]
without -lmuduo_net

**Comment by kbi12** [comment]
thank!!!!!!!
