### ISSUE TITLE
Should std::mutex replace the pthread_mutex_t ?

### ISSUE THREAD

**Issue by jingsong-liu** [chenshuo/muduo#381]
https://github.com/chenshuo/muduo/blob/d980315dc054b122612f423ee2e1316cb14bd3b5/muduo/base/Mutex.h#L197

modern c++ style

**Comment by chenshuo** [comment]
What's the point?
Why std::mutex is better than pthread_mutex_t ?

**Comment by jingsong-liu** [comment]
Thanks for reply.

No vital point, just move the hand-writing implementation to standard library, then unique_lock, lock_guard, scoped_lock ... etc can be used and save some work.

Only my personal opinion because save this work will need additional work.

**Comment by chenshuo** [comment]
C++11's thread library is over designed, I don't like it.
