### ISSUE TITLE
请问， muduo可以用来做支持HTTP的下载服务器程序吗？类似nginx的下载功能，如果可以，我应该参考哪个示例，谢谢

### ISSUE THREAD

**Issue by wuqingwei** [chenshuo/muduo#382]

**Comment by chenshuo** [comment]
什么叫“支持HTTP的下载服务器”？
你到底是要 HTTP server 还是 HTTP client ？
如果是 HTTP server，直接用 nginx 就行，不用自己写代码。
如果是 HTTP client，用 curl，例子见 `/examples/curl`。

**Comment by wuqingwei** [comment]
> 什么叫“支持HTTP的下载服务器”？
> 你到底是要 HTTP server 还是 HTTP client ？
> 如果是 HTTP server，直接用 nginx 就行，不用自己写代码。
> 如果是 HTTP client，用 curl，例子见 `/examples/curl`。

谢谢回复， 我的意思是HTTP server。因为我觉得nginx太大，如果想自己 实现HTTP server用于下载，需要支持进度，断点续传，有没有必要自己写代码？

**Comment by chenshuo** [comment]
Nginx 的可执行文件不到 1MB，你说它太大，你想要多大的？
你说想自己实现 HTTP server 用于下载，又问有没有必要自己写代码，这不是前后矛盾吗？
HTTP server “支持进度”是什么意思？HTTP server 为什么要关心下载进度，你想拿这个“进度”干什么用？

**Comment by wuqingwei** [comment]
> Nginx 的可执行文件不到 1MB，你说它太大，那你想要多大的？
> 你说想自己实现 HTTP server 用于下载，又问有没有必要自己写代码，这不是前后矛盾吗？
> 你的原始需求究竟是什么，是要做下载还是想写 HTTP server？
> HTTP server “支持进度”是什么意思？HTTP server 为什么要关心下载进度，你想拿这个“进度”干什么用？

需求是做下载，用HTTP协议实现，目前在寻找可用的开源库或者框架。

**Comment by chenshuo** [comment]
Good luck!
