### ISSUE TITLE
会不会考虑收发数据引入协程

### ISSUE THREAD

**Issue by hzhxxx** [chenshuo/muduo#383]
GitHub issues are for tracking bugs, not for general discussing like a forum.

If you have a general question to ask, send it to mailing list:

muduo-library@googlegroups.com

Or visit:
https://groups.google.com/forum/#!forum/muduo-library

When file an issue muduo, please provide a [SSCCE](http://sscce.org):
Short, Self Contained, Correct (Compilable), Example.

Also specify the exact environment where the issue occurs:

**Comment by chenshuo** [comment]
This is not a forum.
