### ISSUE TITLE
asio/chat/loadtest去掉连接时的usleep，有时一小部分client不能连接？

### ISSUE THREAD

**Issue by zywww** [chenshuo/muduo#387]
启动:
asio_chat_server 10010
asio_chat_loadtest 0 10010 1000 8

`
for (int i = 0; i < g_connections; ++i)
    {
      clients[i].reset(new ChatClient(loopPool.getNextLoop(), serverAddr));
      clients[i]->connect();
      //usleep(200); // 注释掉
    }
`
这时候loadtest会打印all connected，但是10s过后却不能收到1000条信息。
调试发现server只收到900+条连接，但是client却有1000条连接，
也就是client和server连接数不一致，为什么？

**Comment by zywww** [comment]
这时候client有1000连接，但是server只有900+连接

**Comment by chenshuo** [comment]
你修改了 muduo 的代码，然后程序运行出现了问题，这不是 muduo 的 issue 吧？
