### ISSUE TITLE
C++11的问题

### ISSUE THREAD

**Issue by sunlulu427** [chenshuo/muduo#389]
C++11中已经包含了thread类和mutex类为什么您没有使用呢？如果用的话肯定会减少很多不必要的代码。

**Comment by chenshuo** [comment]
C++ 的 mutex 没有 thread safety annotation, 也不支持 assertLocked() 等操作。
C++ 的 thread 拿不到 tid，而且你也改不了它在 top(1) 里显示的名称。

**Comment by sunlulu427** [comment]
嗯，谢谢您的回复，但是C++11还提供了lock_guard类来管理mutex，在mutex类中包含了try_lock()来判断是否已经上锁，而在thread类中，有get_id()是可以得到tid的，名称问题我觉得由于线程池中的线程本来很少，直接用变量名标识也够用了吧。

**Comment by chenshuo** [comment]
你完全没看懂我在说什么。

lock_guard/mutex 没有 thread safety annotation 吧？它不支持 GUARDED_BY(mu)。https://clang.llvm.org/docs/ThreadSafetyAnalysis.html

mutex 的 try_lock() 能判断当前线程是否已经拿到了锁吗？try_lock() 返回 false，你怎么知道是当前线程已经拿到了锁，还是别的线程已经拿到了锁？

thread 的 get_id() 返回的是 pid_t 吗？跟你在 Linux 操作系统的任务管理器里看到的是相同的 id 吗？
你用变量名标识的 thread，其名称能在 Linux 操作系统的任务管理器里看到吗？
