### ISSUE TITLE
build.sh失败

### ISSUE THREAD

**Issue by Spdwal** [chenshuo/muduo#390]
环境：
Fedroa 28-64
Linux kernel version：4.17.12

gcc : 8.0.1
cmake: 3.11.2
boost: 1.66

报错信息：
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/parallels/Downloads/src/build/release-cpp11/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_3a9ff/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_3a9ff.dir/build.make CMakeFiles/cmTC_3a9ff.dir/build
gmake[1]: Entering directory '/home/parallels/Downloads/src/build/release-cpp11/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_3a9ff.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_3a9ff.dir/CheckSymbolExists.c.o   -c /home/parallels/Downloads/src/build/release-cpp11/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_3a9ff
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3a9ff.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_3a9ff.dir/CheckSymbolExists.c.o  -o cmTC_3a9ff 
CMakeFiles/cmTC_3a9ff.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_3a9ff.dir/build.make:87: cmTC_3a9ff] Error 1
gmake[1]: Leaving directory '/home/parallels/Downloads/src/build/release-cpp11/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:126: cmTC_3a9ff/fast] Error 2

File /home/parallels/Downloads/src/build/release-cpp11/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/parallels/Downloads/src/build/release-cpp11/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_861cc/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_861cc.dir/build.make CMakeFiles/cmTC_861cc.dir/build
gmake[1]: Entering directory '/home/parallels/Downloads/src/build/release-cpp11/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_861cc.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_861cc.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_861cc
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_861cc.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_861cc.dir/CheckFunctionExists.c.o  -o cmTC_861cc -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_861cc.dir/build.make:87: cmTC_861cc] Error 1
gmake[1]: Leaving directory '/home/parallels/Downloads/src/build/release-cpp11/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:126: cmTC_861cc/fast] Error 2

在 #338 中我发现有人和我一样的问题，但是我没有在这个issue中找到解决方案。

**Comment by chenshuo** [comment]
This is not a bug of Muduo, because the code you are compiling is not from Muduo.
