### ISSUE TITLE
编译出错，很难过。。

### ISSUE THREAD

**Issue by ssslifengxiang** [chenshuo/muduo#392]
GitHub issues are for tracking bugs, not for general discussing like a forum.

If you have a general question to ask, send it to mailing list:

muduo-library@googlegroups.com

Or visit:
https://groups.google.com/forum/#!forum/muduo-library

When file an issue muduo, please provide a [SSCCE](http://sscce.org):
Short, Self Contained, Correct (Compilable), Example.

Also specify the exact environment where the issue occurs:

## Linux distro and version? x86 or ARM? 32-bit or 64-bit?
x86 64
## Branch (cpp98/cpp11/cpp17) and version of muduo?
master
## Version of cmake, gcc and boost? (If not from distro.)
cmake 3.5.1
gcc 5.5
boost 1.58

**Comment by ssslifengxiang** [comment]
[ 37%] Building CXX object examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/ttcp_asio_async.cc.o
/home/MUDUO/muduo/examples/ace/ttcp/ttcp_asio_async.cc: In function ‘void doAccept(boost::asio::ip::tcp::acceptor&)’:
/home/MUDUO/muduo/examples/ace/ttcp/ttcp_asio_async.cc:147:76: error: ‘boost::asio::ip::tcp::acceptor {aka class boost::asio::basic_socket_acceptor<boost::asio::ip::tcp>}’ has no member named ‘get_io_service’
   TtcpServerConnectionPtr new_connection(new TtcpServerConnection(acceptor.get_io_service()));
                                                                            ^
examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/build.make:62: recipe for target 'examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/ttcp_asio_async.cc.o' failed
make[2]: *** [examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/ttcp_asio_async.cc.o] Error 1
CMakeFiles/Makefile2:2398: recipe for target 'examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/all' failed
make[1]: *** [examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ssslifengxiang** [comment]
自己本地虚拟机上编译一次过，但是阿里云上买的学生服务器，搞了两天一直卡在这里。。

**Comment by chenshuo** [comment]
I don't have access to the environment you mentioned, so it's not reproducible.
If you can run muduo on your own virtual machine, it's not an issue.

**Comment by wigginskuang** [comment]
我编译的时候也是这样子，环境在ubuntu18，真机
[ 34%] Building CXX object muduo/net/CMakeFiles/muduo_net.dir/TimerQueue.cc.o
/home/kuangweijian/workspace/muduo/muduo-master/examples/ace/ttcp/ttcp_asio_async.cc: In function ‘void doAccept(boost::asio::ip::tcp::acceptor&)’:
/home/kuangweijian/workspace/muduo/muduo-master/examples/ace/ttcp/ttcp_asio_async.cc:147:76: error: ‘boost::asio::ip::tcp::acceptor {aka class boost::asio::basic_socket_acceptor<boost::asio::ip::tcp>}’ has no member named ‘get_io_service’
   TtcpServerConnectionPtr new_connection(new TtcpServerConnection(acceptor.get_io_service()));
                                                                            ^~~~~~~~~~~~~~
[ 34%] Linking CXX static library ../../lib/libmuduo_net.a
[ 34%] Built target muduo_net
Scanning dependencies of target sudoku_stat_unittest
[ 34%] Building CXX object examples/sudoku/CMakeFiles/sudoku_stat_unittest.dir/stat_unittest.cc.o
examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/build.make:62: recipe for target 'examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/ttcp_asio_async.cc.o' failed
make[2]: *** [examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/ttcp_asio_async.cc.o] Error 1
CMakeFiles/Makefile2:2510: recipe for target 'examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/all' failed
make[1]: *** [examples/ace/ttcp/CMakeFiles/ttcp_asio_async.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 34%] Linking CXX executable ../../bin/sudoku_stat_unittest
[ 34%] Built target sudoku_stat_unittest
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wigginskuang** [comment]
好像是因为Boost 1.70移除了get_io_service()
