### ISSUE TITLE
对于 EventLoop::runInLoop 的建议

### ISSUE THREAD

**Issue by zshorz** [chenshuo/muduo#402]
最近在学习您的网络库时，发现在queueInLoop之后加入一个wakeup也许会更好？
比如改成下面这样
```cpp
void EventLoop::runInLoop(Functor cb)
{
  if (isInLoopThread())
  {
    cb();
  }
  else
  {
    queueInLoop(std::move(cb));
    wakeup(); // 这里添加一个wakeup
  }
}
```

我遇到的一种情况：
使用TcpServer::setThreadNum(n),设置了多个线程。
对于每个新的连接，server都会从线程池中选择一个ioLoop来处理这个新的连接
`ioLoop->runInLoop(std::bind(&TcpConnection::connectEstablished, conn));`
但是如果ioLoop上没有任何其他事件发生，connectEstablished最坏情况下必须等待`kPollTimeMs = 10000`毫秒，等到poll超时返回才会被执行。
就导致了，连接已经连上了，但却不能立即读取数据
每一个新的连接大概率都不能立即读取数据（即使数据已经来到），所以我建议加一个wakeup来解决这种情况。

**Comment by zshorz** [comment]
#403 我斗胆提交一个

**Comment by chenshuo** [comment]
`queueInLoop()` 里已经有 `wakeup()` 了。所以你遇到的 bug 的根源不在这里。

**Comment by zshorz** [comment]
对不起 ，我弱智了，您的代码没问题，是我跟着写的时候没有给queueInLoop加wakeup
