### ISSUE TITLE
TcpConnection::send中关于std::bind和StringPiece的问题

### ISSUE THREAD

**Issue by zshorz** [chenshuo/muduo#413]
```cpp
void TcpConnection::send(const StringPiece& message)
{
  if (state_ == kConnected)
  {
    if (loop_->isInLoopThread())
    {
      sendInLoop(message);
    }
    else
    {
      void (TcpConnection::*fp)(const StringPiece& message) = &TcpConnection::sendInLoop;
      loop_->runInLoop(
          std::bind(fp,
                    this,     // FIXME
                    message.as_string()));
                    //std::forward<string>(message)));
    }
  }
}
```
sendInLoop需要一个StringPiece&的参数
想问一下这里`message.as_string()`之后，`bind`保存的是返回的`string`的拷贝，还是将`string`又赋值给一个`StringPiece`类保存了下来。
如果是后者那么`string`析构后`StringPiece`中的指针指向的内存不就释放了
我网页查的很久`bind`保存参数的机制但是还是没弄清，`bind`应该是保存了`string`的拷贝对么？
请大神解惑
`bind`是事先知道`func`的参数类型然后准备对应类型接收，还是不知道只管接收，用的时候让它自己类型转换之类的

**Comment by chengchenwish** [comment]
StringPiece不占有资源，相当于std::string_view，而std::string是独占资源的。而as_string()是构建了一个新的std::string对象。



---原始邮件---
发件人: "zsh"<notifications@github.com&gt;
发送时间: 2019年10月23日(星期三) 晚上10:37
收件人: "chenshuo/muduo"<muduo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [chenshuo/muduo] TcpConnection::send中关于std::bind和StringPiece的问题 (#413)


void TcpConnection::send(const StringPiece&amp; message) {   if (state_ == kConnected)   {     if (loop_-&gt;isInLoopThread())     {       sendInLoop(message);     }     else     {       void (TcpConnection::*fp)(const StringPiece&amp; message) = &amp;TcpConnection::sendInLoop;       loop_-&gt;runInLoop(           std::bind(fp,                     this,     // FIXME                     message.as_string()));                     //std::forward<string&gt;(message)));     }   } }
 
想问一下这里message.as_string()之后，bind保存的是返回的string的拷贝，还是将string又赋值给一个StringPiece类保存了下来。
 如果是后者那么string析构后StringPiece中的指针指向的内存不就释放了
 我网页查的很久bind保存参数的机制但是还是没弄清，bind应该是保存了string的拷贝对么？
 请大神解惑

**Comment by zshorz** [comment]
> 
> StringPiece不占有资源，相当于std::string_view，而std::string是独占资源的。而as_string()是构建了一个新的std::string对象。
> […](#)
> ---原始邮件--- 发件人: "zsh"<notifications@github.com&gt; 发送时间: 2019年10月23日(星期三) 晚上10:37 收件人: "chenshuo/muduo"<muduo@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [chenshuo/muduo] TcpConnection::send中关于std::bind和StringPiece的问题 (#413) void TcpConnection::send(const StringPiece&amp; message) { if (state_ == kConnected) { if (loop_-&gt;isInLoopThread()) { sendInLoop(message); } else { void (TcpConnection::*fp)(const StringPiece&amp; message) = &amp;TcpConnection::sendInLoop; loop_-&gt;runInLoop( std::bind(fp, this, // FIXME message.as_string())); //std::forward<string&gt;(message))); } } } 想问一下这里message.as_string()之后，bind保存的是返回的string的拷贝，还是将string又赋值给一个StringPiece类保存了下来。 如果是后者那么string析构后StringPiece中的指针指向的内存不就释放了 我网页查的很久bind保存参数的机制但是还是没弄清，bind应该是保存了string的拷贝对么？ 请大神解惑 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我知道这个类的用法，我想问的是bind保存的是一个怎样的拷贝，是string还是stringpiece
因为回调参数需要一个stringpiece，但是传给bind的是一个string，stringpiece又可以通过string构造，所以我想问的其实是bind保存的是哪一个

**Comment by chengchenwish** [comment]
string 应该在sendInLoop函数调用完再析构吧。可以写一个UT 测一下。

**Comment by chengchenwish** [comment]
string 是函数调用栈上创建的对象，在调用栈返回之前不会析构。

**Comment by zshorz** [comment]
> 
> 
> string 是函数调用栈上创建的对象，在调用栈返回之前不会析构。

这里面调用as_string()产生的string是会析构的，但是他的copy会被bind保存，我其实问的是一个关于bind的问题

**Comment by chenshuo** [comment]
> 我想问的是bind保存的是一个怎样的拷贝，是string还是stringpiece

如果有人告诉你答案，你有办法验证他说的是对还是错吗？

**Comment by zshorz** [comment]
源码看不太懂，写程序猜了一下
```cpp
class A
{
public:
    A(){cout << "A" << endl;}
    ~A(){cout << "~A" << endl;}
};
class B
{
public:
    B(){cout  <<"default" << endl;}
    B(A){cout << "BA" << endl;}
};
void f(B){}
function<void ()> fun;
int main()
{
    {
        A a;
        fun = std::bind(f,a);
    }
    cout << "-----------" <<endl;
    fun();
    return 0;
}
```

输出：
```
A
~A
~A
~A
-----------
BA
~A
~A
```
虽然不知道为什么A的析构器调用了这么多次，但是在B构造后，又发生了A的析构，
说明A被保存了起来，而不是而不是通过A构造B，再保存B。
