### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by eclair-lumiere** [chenshuo/muduo#414]
[ 33%] Building CXX object muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec.dir/ProtobufCodecLite.cc.o
/root/home/muduo/muduo/net/protobuf/ProtobufCodecLite.cc: In member function ‘virtual int muduo::net::ProtobufCodecLite::serializeToBuffer(const google::protobuf::Message&, muduo::net::Buffer*)’:
/root/home/muduo/muduo/net/protobuf/ProtobufCodecLite.cc:114:36: error: ‘int google::protobuf::MessageLite::ByteSize() const’ is deprecated: Please use ByteSizeLong() instead [-Werror=deprecated-declarations]
   int byte_size = message.ByteSize();
                                    ^
In file included from /usr/local/include/google/protobuf/generated_enum_util.h:36:0,
                 from /usr/local/include/google/protobuf/generated_enum_reflection.h:44,                 from /usr/local/include/google/protobuf/generated_message_reflection.h:48,
                 from /usr/local/include/google/protobuf/message.h:122,
                 from /root/home/muduo/muduo/net/protorpc/google-inl.h:39,
                 from /root/home/muduo/muduo/net/protobuf/ProtobufCodecLite.cc:15:
/usr/local/include/google/protobuf/message_lite.h:402:7: note: declared here
   int ByteSize() const { return internal::ToIntSize(ByteSizeLong()); }
       ^
/root/home/muduo/muduo/net/protobuf/ProtobufCodecLite.cc:121:58: error: ‘int google::protobuf::MessageLite::ByteSize() const’ is deprecated: Please use ByteSizeLong() instead [-Werror=deprecated-declarations]
     ByteSizeConsistencyError(byte_size, message.ByteSize(), static_cast<int>(end - star                                                          ^
In file included from /usr/local/include/google/protobuf/generated_enum_util.h:36:0,
                 from /usr/local/include/google/protobuf/generated_enum_reflection.h:44,                 from /usr/local/include/google/protobuf/generated_message_reflection.h:48,
                 from /usr/local/include/google/protobuf/message.h:122,
                 from /root/home/muduo/muduo/net/protorpc/google-inl.h:39,
                 from /root/home/muduo/muduo/net/protobuf/ProtobufCodecLite.cc:15:
/usr/local/include/google/protobuf/message_lite.h:402:7: note: declared here
   int ByteSize() const { return internal::ToIntSize(ByteSizeLong()); }
       ^
cc1plus: all warnings being treated as errors
muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec.dir/build.make:62: recipe for target 'muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec.dir/ProtobufCodecLite.cc.o' failed
make[2]: *** [muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec.dir/ProtobufCodecLite.cc.o] Error 1
CMakeFiles/Makefile2:1976: recipe for target 'muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec.dir/all' failed
make[1]: *** [muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

## Linux distro and version? x86 or ARM? 32-bit or 64-bit?
Ubuntu16.04  x86_64  64-bit
## Branch (cpp98/cpp11/cpp17) and version of muduo?
master
## Version of cmake, gcc and boost? (If not from distro.)
cmake version 3.5.1
gcc 5.4.0
libboost1.58-dev:amd64

**Comment by chenshuo** [comment]
Change `ByteSize()` to `ByteSizeLong()` if your protobuf library is too new.

**Comment by eclair-lumiere** [comment]
> Change `ByteSize()` to `ByteSizeLong()` if your protobuf library is too new.

Thank you.
