### ISSUE TITLE
关于在windows下移植中移植问题

### ISSUE THREAD

**Issue by wey580231** [chenshuo/muduo#417]
拜读了代码后，想在windows下对muduo库进行功能移植。移植中对于eventfd和timerfd这两个功能遇到了障碍，在windows下没有相应的实现。目前我采取的措施是通过一个udp socket来模拟eventfd的唤醒功能。想请教下有没有更好的实现方式？

**Comment by TheWaveLab** [comment]
可以考虑使用libuv

**Comment by TheWaveLab** [comment]
> 
> 
> 拜读了代码后，想在windows下对muduo库进行功能移植。移植中对于eventfd和timerfd这两个功能遇到了障碍，在windows下没有相应的实现。目前我采取的措施是通过一个udp socket来模拟eventfd的唤醒功能。想请教下有没有更好的实现方式？

可以考虑使用libuv

**Comment by wey580231** [comment]
谢谢~
