### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by hardway2008** [chenshuo/muduo#418]
#Linux distro and version? x86 or ARM? 32-bit or 64-bit?
  x86 ubuntu18.04 64bit
## Branch (cpp98/cpp11/cpp17) and version of muduo?
  cpp11
## Version of cmake, gcc and boost? (If not from distro.)
  cmake version 3.10.2
  Boost version: 1.65.1
  gcc 7.4.0
  protoc 3.8.0

Building CXX object muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/rpc.pb.cc.o
In file included from /home/leo/workspace/source/build/release-cpp11/muduo/net/protorpc/rpc.pb.cc:4:0:
/home/leo/workspace/source/build/release-cpp11/muduo/net/protorpc/rpc.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/build.make:69: recipe for target 'muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/rpc.pb.cc.o' failed
make[2]: *** [muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/rpc.pb.cc.o] Error 1
CMakeFiles/Makefile2:1875: recipe for target 'muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/all' failed
make[1]: *** [muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

请问编译muduo库需要哪个版本的protobuf?

**Comment by chenshuo** [comment]
Try deleting release-cpp11/ and rebuild.  You probably upgraded protobuf but didn't re-generate .pb.cc files.
