### ISSUE TITLE
编译muduo库时报boost错误

### ISSUE THREAD

**Issue by liujiejie** [chenshuo/muduo#419]
## Linux distro and version? x86 or ARM? 32-bit or 64-bit?
Linux version 3.10.0-327.el7.x86_64   x86   64-bit
## Branch (cpp98/cpp11/cpp17) and version of muduo?
cpp11    muduo-2.0.0
## Version of cmake, gcc and boost? (If not from distro.)
cmake: 3.3.2
gcc: 4.8.5
boost: boost_1_71_0

准备在项目中使用muduo库，希望能尽快解答，非常感谢。
1.
/home/zz/lib/boost_1_71_0/boost/concept/detail/has_constraints.hpp:44:58: error: use of old-style cast [-Werror=old-style-cast]
       , value = sizeof( detail::has_constraints_((Model*)0) ) == sizeof(detail::yes) );

2.
/home/lj/lib/boost_1_71_0/boost/circular_buffer/base.hpp:1023:5: error: declaration of ‘alloc’ shadows a member of 'this' [-Werror=shadow]
     : base(boost::empty_init_t(), alloc), m_buff(0), m_end(0), m_first(0), m_last(0), m_size(0) {}

**Comment by qazwsxedckll** [comment]
第一个是(Model*)是c的强转，第二个是alloc覆盖了外面的同名member，都不是什么大事。要么把warning视为error关了，要么把shadow和old-style-cast关了。你不会想去动boost库吧。

**Comment by liujiejie** [comment]
嗯，解决了，谢谢，还有一个：
3./home/lj/lib/boost_1_71_0/boost/mpl/aux_/preprocessed/gcc/template_arity.hpp:83:32: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
需要屏蔽掉-Wconversion
