### ISSUE TITLE
编译muduo时报找不到protobuf

### ISSUE THREAD

**Issue by liujiejie** [chenshuo/muduo#420]
## Linux distro and version? x86 or ARM? 32-bit or 64-bit?
Linux  64
## Branch (cpp98/cpp11/cpp17) and version of muduo?
cpp11
## Version of cmake, gcc and boost? (If not from distro.)

[xx@local muduo-2.0.0]$ echo $PROTOBUF_INCLUDE_DIR
/home/xx/lib/protobuf-3.10.1/release/include/
[xx@local muduo-2.0.0]$ echo^C
[xx@local muduo-2.0.0]$ echo $PROTOBUF_LIBRARY
/home/xx/lib/protobuf-3.10.1/release/lib/

`[@local muduo-2.0.0]$ ./build.sh protobuf_all
++ pwd
+ SOURCE_DIR=/home/xx/lib/muduo-2.0.0
+ BUILD_DIR=../build
+ BUILD_TYPE=release
+ INSTALL_DIR=../release-install-cpp11
+ CXX=g++
+ ln -sf ../build/release-cpp11/compile_commands.json
+ mkdir -p ../build/release-cpp11
+ cd ../build/release-cpp11
+ cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=../release-install-cpp11 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON /home/lj/lib/muduo-2.0.0
-- Boost version: 1.71.0
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR)
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR)
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- CXX_FLAGS = -DCHECK_PTHREAD_RETURN_VALUE -D_FILE_OFFSET_BITS=64 -Wall -Wextra -Werror -Wno-unused-parameter -Woverloaded-virtual -Wpointer-arith -Wwrite-strings -march=native -std=c++11 -rdynamic -O2 -DNDEBUG
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lj/lib/build/release-cpp11
+ make protobuf_all
make: *** No rule to make target `protobuf_all'.  Stop.
`

已经指定了protobuf的目录，但是编译muduo还是会报找不到protobuf，这是什么原因啊？？

**Comment by prettykernel** [comment]
请先参考 https://github.com/chenshuo/muduo/blob/master/.travis.yml，使用 apt-get 安装所有依赖。
