### ISSUE TITLE
bazel build failure with llvm

### ISSUE THREAD

**Issue by wangsu502** [chenshuo/muduo#421]
ERROR: /home/wangsu/.cache/bazel/_bazel_wangsu/fed691259f92afcde51abaed59869647/external/muduo/muduo/base/BUILD.bazel:1:1: C++ compilation of rule '@muduo//muduo/base:base' failed (Exit 1) clang failed: error executing command external/llvm_toolchain/bin/clang -U_FORTIFY_SOURCE -fstack-protector -fno-omit-frame-pointer -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign '-std=c++17' '-stdlib=libc++' -MD -MF ... (remaining 20 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/muduo/muduo/base/Date.cc:57:10: error: member access into incomplete type 'const struct tm'
        t.tm_year+1900,
         ^
/usr/include/wchar.h:83:8: note: forward declaration of 'tm'
struct tm;
       ^
external/muduo/muduo/base/Date.cc:58:10: error: member access into incomplete type 'const struct tm'
        t.tm_mon+1,
         ^
/usr/include/wchar.h:83:8: note: forward declaration of 'tm'
struct tm;
       ^
external/muduo/muduo/base/Date.cc:59:10: error: member access into incomplete type 'const struct tm'
        t.tm_mday))
         ^
/usr/include/wchar.h:83:8: note: forward declaration of 'tm'
struct tm;
       ^
3 errors generated.
Target //ds:main-ds failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.090s, Critical Path: 0.76s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by chenshuo** [comment]
Try include time.h in Date.cc
