### ISSUE TITLE
一次收到消息太多，导致Buffer结构不断拷贝扩大，使服务短暂停止

### ISSUE THREAD

**Issue by liujiejie** [chenshuo/muduo#422]
GitHub issues are for tracking bugs, not for general discussing like a forum.

If you have a general question to ask, send it to mailing list:

muduo-library@googlegroups.com

Or visit:
https://groups.google.com/forum/#!forum/muduo-library

When file an issue muduo, please provide a [SSCCE](http://sscce.org):
Short, Self Contained, Correct (Compilable), Example.

Also specify the exact environment where the issue occurs:

## Linux distro and version? x86 or ARM? 32-bit or 64-bit?
Linux 
## Branch (cpp98/cpp11/cpp17) and version of muduo?
cpp11
## Version of cmake, gcc and boost? (If not from distro.)
boost：1.71

你好，我在实际使用muduo的过程中，有这样一个场景：
1.客户端，往服务端不断发送512字节数据，并从服务端收响应，确认服务端收到多少条消息。
2.服务端，从客户端收消息，每获取一次消息，按消息大小获取当前收到多少条消息，然后把这个消息条数返回给客户端。
问题是，当服务端收到的数据量太大，Buffer结构会不断拷贝扩大，使服务短暂停止，也会导致客户端一段时间收不到服务端的响应。以下是客户端收到消息的响应，最后几条，20多秒才收到响应，RECV 关键字后面跟的是收到响应消息的条数。
server.cpp:

> 
void onMessage(const TcpConnectionPtr& conn, Buffer* buf, Timestamp)
{
	LOG_WARN << "begin ";
	size_t recv_size = buf->readableBytes();
	int count = recv_size / 128;
	recv_msg_count += count;
	return_index_str.appendInt64(recv_msg_count);
	conn->send(&return_index_str);

	buf->retrieveAsString(128 * count);
	LOG_WARN << "recv_msg_count " << recv_msg_count << " recv_size " << recv_size;
}

> 

client.cpp:
void* SyncDataThread(void* arg)
{
	std::string message;
	for (int i = 0; i < 128; ++i)
	{
		message.push_back(static_cast<char>(47));
	}

	ThreadData* thread_data = (ThreadData*)arg;
	while (run_g)
	{
		thread_data->conn->send(message);
	}

	return NULL;
}
void onMessage(const TcpConnectionPtr& conn, Buffer* buf, Timestamp time)
{
	size_t recv_size = buf->readableBytes();
	int count = recv_size / 8;
	int read_index = count * 8 - 8;
	if (read_index > 0)
	{
		buf->retrieve(read_index);
		int64_t current_index = buf->readInt64();
		LOG_INFO << "onMessage RECV " << current_index;
	}
}

会出现：
20191128 08:33:05.447646Z  2791 WARN  begin  - server.cpp:31
20191128 08:33:05.447653Z  2791 WARN  recv_msg_count 2533178 recv_size 21796 - server.cpp:47
20191128 08:33:10.485236Z  2791 WARN  begin  - server.cpp:31
20191128 08:33:10.485300Z  2791 WARN  recv_msg_count 2534171 recv_size 127104 - server.cpp:47

如果我把server的LOG_WARN删掉了就会出现：
20191128 07:09:13.081419Z  6365 INFO  onMessage RECV 900491321 - client.cpp:109
20191128 07:09:13.094496Z  6365 INFO  onMessage RECV 930739343 - client.cpp:109
20191128 07:09:13.128861Z  6365 INFO  onMessage RECV 989184792 - client.cpp:109
20191128 07:09:13.237572Z  6365 INFO  onMessage RECV 1175997802 - client.cpp:109
20191128 07:09:13.512062Z  6365 INFO  onMessage RECV 1705829539 - client.cpp:109
20191128 07:09:14.196504Z  6365 INFO  onMessage RECV 3632626542 - client.cpp:109
20191128 07:09:16.291605Z  6365 INFO  onMessage RECV 9913869110 - client.cpp:109
20191128 07:09:20.893491Z  6365 INFO  onMessage RECV 18108680633 - client.cpp:109
20191128 07:09:30.928978Z  6365 INFO  onMessage RECV 27940861681 - client.cpp:109
20191128 07:09:52.150305Z  6365 INFO  onMessage RECV 39357650013 - client.cpp:109

我想要的效果是每一秒中，都会有很多响应回来，请问这个要怎么修改下呢？

**Comment by chenshuo** [comment]
你什么时候在 Server 端调用 Buffer::retrieve() ?

**Comment by liujiejie** [comment]
> 你什么时候在 Server 端调用 Buffer::retrieve() ?

onMessage函数里面的buf->retrieveAsString(128 * count);
上面的代码里面有贴的

**Comment by chenshuo** [comment]
“把server的LOG_WARN删掉”为什么会影响程序的行为？

**Comment by liujiejie** [comment]
发现是客户端内存泄漏，如果server有打印，处理的就会慢一点，内存也就没那么快满，定位到是我自己创建的那个pthread线程在发送数据的时候泄漏的，不知道是哪里泄漏了呢？看不出来啊。请大神指点下。
void* SyncDataThread(void* arg)
{
    std::string message;
    for (int i = 0; i < 128; ++i)
    {
        message.push_back(static_cast(47));
    }
    ThreadData* thread_data = (ThreadData*)arg;
    while (run_g)
    {
	thread_data->conn->send(message);
    }
    return NULL;
}

**Comment by chenshuo** [comment]
你说的“每秒发10w都发不了”是指 client 还是 server？
“数据发不出去，堵住占用内存”是指占 client 内存还是 server 内存？

你前面说“问题是，当服务端收到的数据量太大，Buffer结构会不断拷贝扩大，使服务短暂停止”，是说 server 的内存占用太多？后面又说 client 数据发不出去，占用太多 client 内存？我完全看糊涂了。

**Comment by liujiejie** [comment]
抱歉，是我搞错了，并不是“当服务端收到的数据量太大，Buffer结构会不断拷贝扩大，使服务短暂停止”这个原因。
“每秒发10w都发不了”是指 client 
“堵住占用内存”是指占 client 内存

**Comment by chenshuo** [comment]
采用 Non-blocking IO 的 client 是不能用一个 white(true) 循环来不停地发送消息，你要么在收到 server 的响应之后发送下一批消息，要么用 high water mark callback 在本地发送缓冲区清空之后发送下一批消息。

**Comment by liujiejie** [comment]
> 采用 Non-blocking IO 的 client 是不能用一个 white(true) 循环来不停地发送消息，你要么在收到 server 的响应之后发送下一批消息，要么用 high water mark callback 在本地发送缓冲区清空之后发送下一批消息。

嗯，我试下，我还有另外一个问题，现在我想在项目中使用，但是muduo现有的日志格式跟我们其他组件的日志格式不同，这个怎么修改muduo的日志格式呢？muduo的日志带锁吗？

**Comment by qazwsxedckll** [comment]
看源码，不行去看书的第五章，硕哥关了吧，#419也是。
