### ISSUE TITLE
Optimize:  Reduce one copy in setReadCallback

### ISSUE THREAD

**Issue by hankai17** [chenshuo/muduo#423]
In Channel.h we see follow
```
 void setReadCallback(ReadEventCallback cb)
  { readCallback_ = std::move(cb); }
```
The para is “ReadEventCallback”. I'd prefer to replace it by "ReadEventCallback& "

**Comment by chenshuo** [comment]
If you change the parameter to `ReadEventCallback&`, it will break use case like

```c++
channel->setReadCallback(std::bind(&ThisClass::onMessage, this, _1, _2, _3));
```
