### ISSUE TITLE
后期会添加数据库方面的东西么

### ISSUE THREAD

**Issue by upckz** [chenshuo/muduo#427]
GitHub issues are for tracking bugs, not for general discussing like a forum.

If you have a general question to ask, send it to mailing list:

muduo-library@googlegroups.com

Or visit:
https://groups.google.com/forum/#!forum/muduo-library

When file an issue muduo, please provide a [SSCCE](http://sscce.org):
Short, Self Contained, Correct (Compilable), Example.

Also specify the exact environment where the issue occurs:

**Comment by chenshuo** [comment]
This is very unprofessional.
