### ISSUE TITLE
Mac 编译出错，求看

### ISSUE THREAD

**Issue by kangzr** [chenshuo/muduo#434]
/usr/local/include/boost/concept/detail/has_constraints.hpp:44:50: error: use of old-style cast [-Werror,-Wold-style-cast]
      , value = sizeof( detail::has_constraints_((Model*)0) ) == sizeof(detail::yes) );
                                                 ^       ~
/usr/local/include/boost/config/detail/suffix.hpp:394:72: note: expanded from macro 'BOOST_STATIC_CONSTANT'
#     define BOOST_STATIC_CONSTANT(type, assignment) static const type assignment
                                                                       ^~~~~~~~~~
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/base/AsyncLogging.cc:6:
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/base/AsyncLogging.h:10:
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/base/BoundedBlockingQueue.h:12:
In file included from /usr/local/include/boost/circular_buffer.hpp:58:
In file included from /usr/local/include/boost/circular_buffer/base.hpp:22:
In file included from /usr/local/include/boost/concept_check.hpp:20:
In file included from /usr/local/include/boost/concept/assert.hpp:35:
/usr/local/include/boost/concept/detail/general.hpp:31:29: error: use of old-style cast [-Werror,-Wold-style-cast]
    static void failed() { ((Model*)0)->~Model(); }
                            ^       ~
/usr/local/include/boost/concept/detail/general.hpp:39:29: error: use of old-style cast [-Werror,-Wold-style-cast]
    static void failed() { ((Model*)0)->~Model(); }
                            ^       ~
/usr/local/include/boost/concept/detail/general.hpp:47:29: error: use of old-style cast [-Werror,-Wold-style-cast]
    static void failed() { ((Model*)0)->constraints(); }
                            ^       ~
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/base/AsyncLogging.cc:6:
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/base/AsyncLogging.h:10:
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/base/BoundedBlockingQueue.h:12:
In file included from /usr/local/include/boost/circular_buffer.hpp:58:
In file included from /usr/local/include/boost/circular_buffer/base.hpp:22:
In file included from /usr/local/include/boost/concept_check.hpp:31:
/usr/local/include/boost/concept/usage.hpp:16:30: error: use of old-style cast [-Werror,-Wold-style-cast]
    ~usage_requirements() { ((Model*)0)->~Model(); }
                             ^       ~
5 errors generated.
make[2]: *** [muduo/base/CMakeFiles/muduo_base.dir/AsyncLogging.cc.o] Error 1
make[1]: *** [muduo/base/CMakeFiles/muduo_base.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Building CXX object muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/RpcCodec.cc.o
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/protorpc/RpcCodec.cc:12:
/Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/endian.h:15:10: error: 'endian.h' file not found with <angled> include; use "quotes" instead
#include <endian.h>
         ^~~~~~~~~~
         "endian.h"
/Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/endian.h:15:10: error: non-portable path to file '<Endian.h>'; specified path differs in case from file name
      on disk [-Werror,-Wnonportable-include-path]
#include <endian.h>
         ^~~~~~~~~~
         <Endian.h>
/Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/endian.h:31:10: error: use of undeclared identifier 'htobe64'
  return htobe64(host64);
         ^
/Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/endian.h:36:10: error: use of undeclared identifier 'htobe32'
  return htobe32(host32);
         ^
/Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/endian.h:41:10: error: use of undeclared identifier 'htobe16'
  return htobe16(host16);
         ^
/Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/endian.h:46:10: error: use of undeclared identifier 'be64toh'
  return be64toh(net64);
         ^
/Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/endian.h:51:10: error: use of undeclared identifier 'be32toh'
  return be32toh(net32);
         ^
/Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/endian.h:56:10: error: use of undeclared identifier 'be16toh'
  return be16toh(net16);
         ^
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/protorpc/RpcCodec.cc:13:
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/TcpConnection.h:23:
In file included from /usr/local/include/boost/any.hpp:20:
In file included from /usr/local/include/boost/type_index.hpp:29:
In file included from /usr/local/include/boost/type_index/stl_type_index.hpp:47:
In file included from /usr/local/include/boost/container_hash/hash.hpp:21:
/usr/local/include/boost/container_hash/detail/hash_float.hpp:109:32: error: use of old-style cast [-Werror,-Wold-style-cast]
            return hash_binary((char*) &v, 4);
                               ^       ~~
/usr/local/include/boost/container_hash/detail/hash_float.hpp:119:32: error: use of old-style cast [-Werror,-Wold-style-cast]
            return hash_binary((char*) &v, 8);
                               ^       ~~
/usr/local/include/boost/container_hash/detail/hash_float.hpp:128:32: error: use of old-style cast [-Werror,-Wold-style-cast]
            return hash_binary((char*) &v, 10);
                               ^       ~~
/usr/local/include/boost/container_hash/detail/hash_float.hpp:137:32: error: use of old-style cast [-Werror,-Wold-style-cast]
            return hash_binary((char*) &v, 16);
                               ^       ~~
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/protorpc/RpcCodec.cc:13:
In file included from /Users/zhongrunkang/MySpace/MyGit/muduo/muduo/net/TcpConnection.h:23:
In file included from /usr/local/include/boost/any.hpp:20:
In file included from /usr/local/include/boost/type_index.hpp:29:
In file included from /usr/local/include/boost/type_index/stl_type_index.hpp:47:
/usr/local/include/boost/container_hash/hash.hpp:282:26: error: use of old-style cast [-Werror,-Wold-style-cast]
                 seed ^= (std::size_t) (positive >> i) + (seed<<6) + (seed>>2);
                         ^             ~~~~~~~~~~~~~~~
/usr/local/include/boost/container_hash/hash.hpp:284:22: error: use of old-style cast [-Werror,-Wold-style-cast]
             seed ^= (std::size_t) val + (seed<<6) + (seed>>2);
                     ^             ~~~
/usr/local/include/boost/container_hash/hash.hpp:302:26: error: use of old-style cast [-Werror,-Wold-style-cast]
                 seed ^= (std::size_t) (val >> i) + (seed<<6) + (seed>>2);
                         ^             ~~~~~~~~~~
/usr/local/include/boost/container_hash/hash.hpp:304:22: error: use of old-style cast [-Werror,-Wold-style-cast]
             seed ^= (std::size_t) val + (seed<<6) + (seed>>2);
                     ^             ~~~
16 errors generated.
make[2]: *** [muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/RpcCodec.cc.o] Error 1
make[1]: *** [muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/all] Error 2
make: *** [all] Error 2

**Comment by chenshuo** [comment]
MAC is not supported.
