### ISSUE TITLE
The LogStream::Buffer

### ISSUE THREAD

**Issue by 841974180** [chenshuo/muduo#435]
GitHub issues are for tracking bugs, not for general discussing like a forum.

If you have a general question to ask, send it to mailing list:

muduo-library@googlegroups.com

Or visit:
https://groups.google.com/forum/#!forum/muduo-library

When file an issue muduo, please provide a [SSCCE](http://sscce.org):
Short, Self Contained, Correct (Compilable), Example.

Also specify the exact environment where the issue occurs:

## Linux distro and version? x86 or ARM? 32-bit or 64-bit?
Linux  64bit
## Branch (cpp98/cpp11/cpp17) and version of muduo?
cpp11
## Version of cmake, gcc and boost? (If not from distro.)
cmake boost1.69

single log message length is more than 4000, when i used "LOG_INFO << log message;" The print is
"  - func line". So I change the LogStream.h::84 detail::FixedBuffer<detail::kLargeBuffer> and build again muduo and try build my program.

Here is my test code:
muduo::net::EventLoop loop;
LOG_INFO <<  some word and length more than 4000
loop.loop();
retrurn 0;

Segmentation fault is occured EPollPoller construtor and error message is Cannot access memory at 
Address

**Comment by chenshuo** [comment]
IIUC, you modified muduo, then there's a SEGFAULT.

What you do expect me to do without showing your modification?

**Comment by 841974180** [comment]
Is this is wrong way to print large message?what is correctly behavior

**Comment by chenshuo** [comment]
Try change kSmallBuffer to a larger number, like 15000.

**Comment by 841974180** [comment]
Thanks
