### ISSUE TITLE
ThreadPool::run()可能会阻塞的问题。

### ISSUE THREAD

**Issue by GGGGITFKBJG** [chenshuo/muduo#458]
问题是这样的：
当队列满时，生产者线程也会阻塞。ThreadPool::stop()只是唤醒了阻塞的消费者线程。
假如某时刻队列已满，消费者线程正忙于执行已取出的任务，生产者线程放置操作会阻塞。这时另一个线程调用stop()想关闭线程池，就会造成生产者线程永远都阻塞在wait()上。

代码是这样：
```cpp
#include "muduo/base/ThreadPool.h"
#include <stdio.h>
#include "muduo/base/CurrentThread.h"

using namespace muduo;

ThreadPool pool;

void longtimeTask() {  // 每个任务需要5秒完成
  printf("Thread %s taken a task.\n", CurrentThread::name());
  CurrentThread::sleepUsec(5000000);
  printf("Thread %s done the task.\n", CurrentThread::name());
}

void func() {
  pool.run(longtimeTask);  // 这个刚放入会被取出执行
  pool.run(longtimeTask);  // 这个会占满队列
  pool.run(longtimeTask);  // 应该会阻塞在这里
}

int main() {
  pool.setMaxQueueSize(1);
  pool.start(1);

  Thread t1(func, "t1");  // 让t1放置3个任务.
  t1.start();

  CurrentThread::sleepUsec(1000000);  // 1秒后关闭pool
  pool.stop();
  printf("Pool stoped.\n");

  t1.join();// t1会一直阻塞.
  return 0;
}
```

上面的代码执行时不能正常退出。
让stop()也唤醒生产者，并且给run()加上if (running_)判断可以解决这个问题。
这是代码的漏洞，还是我的用法不正确？

**Comment by chenshuo** [comment]
可以算是 bug，ThreadPool 没有考虑 `stop()` 之后继续调用 `run()` 的情况，在 `stop()` 里也没有考虑去唤醒已经阻塞的 `run()`。
如果打算修复，那”`stop()` 之后继续调用 `run()`” 应该具有什么样的行为？

**Comment by GGGGITFKBJG** [comment]
> 可以算是 bug，ThreadPool 没有考虑 `stop()` 之后继续调用 `run()` 的情况，在 `stop()` 里也没有考虑去唤醒已经阻塞的 `run()`。
> 如果打算修复，那”`stop()` 之后继续调用 `run()`” 应该具有什么样的行为？

上面代码中的第三个<code>run()</code>是在<code>stop()</code>**之前**调用并陷入阻塞的。所以即使排除掉<code>stop()</code>后再调用<code>run()</code>的情况，<code>run()</code>永远阻塞也是有可能出现的。
我的想法是在<code>run()</code>的while循环条件里面加上对<code>running_</code>的判断，这样如果<code>stop()</code>后再调用<code>run()</code> OR 遇上前面代码中的小概率情况，它就会直接退出 OR 被唤醒后退出。
```cpp
while (QueueIsFull() && running_) {
    notFull_.Wait();
}
if (!running_) LOG and return;
```

**Comment by chenshuo** [comment]
如果你的项目确实需要支持这个应用场景，那么可以提个 PR。
或者在 `run()` 的前面加一条注释，告诉用户如果提前 `stop()`，`run()` 有可能一直阻塞。

muduo 作为服务端开发的库，通常在设计上没有考虑程序正常退出的需求。目前 `TcpClient` 也对销毁的支持不够好。

**Comment by lsaejn** [comment]
你好，是不是应该这样写呢？
{
  MutexLockGuard lock(mutex_);
  running_ = false;
}
  notEmpty_.notifyAll();
  notFull_.notifyAll();

**Comment by GGGGITFKBJG** [comment]
> 你好，是不是应该这样写呢？
> {
> MutexLockGuard lock(mutex_);
> running_ = false;
> }
> notEmpty_.notifyAll();
> notFull_.notifyAll();

这两种写法都可以的，各有好坏。
https://1feng.github.io/2016/07/20/signal-with-mutex-locked-or-not/

**Comment by lsaejn** [comment]
> > 你好，是不是应该这样写呢？
> > {
> > MutexLockGuard lock(mutex_);
> > running_ = false;
> > }
> > notEmpty_.notifyAll();
> > notFull_.notifyAll();
> 
> 这两种写法都可以的，各有好坏。
> https://1feng.github.io/2016/07/20/signal-with-mutex-locked-or-not/

我用了std::condition_variable, 所以感觉这里不加锁都行。。
