### ISSUE TITLE
在AsyncLogging的109行的判断buffersToWrite.size()大于2后resize是否必要，因为后面总会clear。

### ISSUE THREAD

**Issue by Super-long** [chenshuo/muduo#459]
GitHub issues are for tracking bugs, not for general discussing like a forum.

If you have a general question to ask, send it to mailing list:

muduo-library@googlegroups.com

Or visit:
https://groups.google.com/forum/#!forum/muduo-library

When file an issue muduo, please provide a [SSCCE](http://sscce.org):
Short, Self Contained, Correct (Compilable), Example.

Also specify the exact environment where the issue occurs:

**Comment by Super-long** [comment]
首先clear和resize都不会减少capacity，不存在容器上的考虑。我认为加上的原因是当resize为2以后第二个if判断不一定成功，所以此时buffersToWrite中可能不为零，而前端写入日志块是使用push_back的，所以要clear一下，否则下一次写入就会有一整个日志块是空的了。这样看来不进行这个大于2的判断也是可以的，因为后面会clear。

**Comment by chenshuo** [comment]
代码里有一行注释，说明其目的：

> // drop non-bzero-ed buffers, avoid trashing

简单说就是想反复使用前面创建的两个 `newBuffer1` 和 `newBuffer2`，尽量把第 51 行临时分配的 `Buffer` 尽早释放。
