### ISSUE TITLE
一个关于isMainThread的问题

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [chenshuo/muduo#462]
您好，很荣幸可以学习您的源码，我看到源码中有一处没明白
bool CurrentThread::isMainThread()
{
  return tid() == ::getpid();
}

我看到tid中是调用了
pid_t tid = static_cast<pid_t>(::syscall(SYS_gettid));

我自己写了一段程序在主线程中调用是
    pid_t tid = static_cast<pid_t>(::syscall(SYS_gettid));
    printf("%d\n",getgid());
    printf("%d\n",tid);

发现结果是
1000
8992

并不会相等，请问您这段程序 没有阅读明白为什么要这么写，希望收到您的回复，感谢

**Comment by tan-wei** [comment]
```c++
printf("%d\n",getgid());
```
你这个地方获取的是组ID……看看是不是笔误。

**Comment by LeiZhang-Hunter** [comment]
谢谢 啊啊啊啊啊，居然是笔误

**Comment by LeiZhang-Hunter** [comment]
刚才看到了一个吉利的数字 ，commit 777 哈哈哈，谢谢解答
