### ISSUE TITLE
请教一个问题  通信协议的设计啥证明设计的？跟redis一样用RESP2吗

### ISSUE THREAD

**Issue by xiaozhitaba** [chenshuo/muduo#464]
GitHub issues are for tracking bugs, not for general discussing like a forum.

If you have a general question to ask, send it to mailing list:

muduo-library@googlegroups.com

Or visit:
https://groups.google.com/forum/#!forum/muduo-library

When file an issue muduo, please provide a [SSCCE](http://sscce.org):
Short, Self Contained, Correct (Compilable), Example.

Also specify the exact environment where the issue occurs:

**Comment by xiaozhitaba** [comment]
变长协议（协议头+payload）?

**Comment by chenshuo** [comment]
This is not an issue of muduo. GitHub issues are not for discussion like this.
