### ISSUE TITLE
在CentOS环境下安装muduo库，进度条到23后出现错误：make[2]: *** [bin/logstream_test] 错误 1 make[1]: *** [muduo/base/tests/CMakeFiles/logstream_test.dir/all] 错误 2

### ISSUE THREAD

**Issue by Jamesuhao** [chenshuo/muduo#471]
boost库已yum安装
具体错误信息：
[ 22%] Building CXX object muduo/base/tests/CMakeFiles/logstream_test.dir/LogStream_test.cc.o
[ 23%] Linking CXX executable ../../../bin/logstream_test
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘testLogStreamFloats::test_method()’中：
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:157：对‘boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘bool boost::test_tools::tt_detail::check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, int, int>(boost::test_tools::tt_detail::equal_impl_frwd, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, int const&, char const*, int const&, char const*)’中：
/usr/local/include/boost/test/tools/old/impl.hpp:92：对‘boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)’未定义的引用
/usr/local/include/boost/test/tools/old/impl.hpp:92：对‘boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)’中：
/usr/local/include/boost/test/tree/test_unit.hpp:267：对‘boost::unit_test::test_case::test_case(boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long, boost::function<void ()> const&)’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘__static_initialization_and_destruction_0(int, int) [clone .constprop.101]’中：
/usr/local/include/boost/test/unit_test_log.hpp:227：对‘boost::unit_test::unit_test_log_t::instance()’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘__static_initialization_and_destruction_0(int, int) [clone .constprop.101]’中：
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:13：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:13：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:26：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:26：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:43：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:43：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:113：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:113：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:172：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:172：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:186：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:186：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:199：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:199：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:217：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:217：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:237：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:237：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:263：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/test/source_code/muduo-master/muduo/base/tests/LogStream_test.cc:263：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘bool boost::test_tools::tt_detail::check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, std::string, std::string>(boost::test_tools::tt_detail::equal_impl_frwd, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, std::string const&, char const*, std::string const&, char const*)’中：
/usr/local/include/boost/test/tools/old/impl.hpp:92：对‘boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘bool boost::test_tools::tt_detail::check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, int, int>(boost::test_tools::tt_detail::equal_impl_frwd, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, int const&, char const*, int const&, char const*)’中：
/usr/local/include/boost/test/tools/old/impl.hpp:92：对‘boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)’未定义的引用
collect2: error: ld returned 1 exit status
make[2]: *** [bin/logstream_test] 错误 1
make[1]: *** [muduo/base/tests/CMakeFiles/logstream_test.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by Jamesuhao** [comment]
boost库已安装

**Comment by chenshuo** [comment]
请根据提问模板提供以下基本信息：

Specify the exact environment where the issue occurs:

* Linux distro and version? x86 or ARM? 32-bit or 64-bit?
* Branch (cpp98/cpp11/cpp17) and version of muduo?
* Version of cmake, gcc and boost? (If not from distro.)

**Comment by Jamesuhao** [comment]
Linux版本为CentOS7，X86
cpp 11
cmake：3.11.2，gcc： 5.3.1  bost ：1.69

**Comment by chenshuo** [comment]
CentOS 7 官方 yum 自带的软件版本是：

* cmake 2.8.12
* gcc: 4.8.5
* boost: 1.53.0

我在 CentOS 7.8 下使用以上官方版本的 package 能正常编译 muduo。

**Comment by Jamesuhao** [comment]
解决了，是我boost库安装出错了，谢谢回复。

**Comment by sx-zhao** [comment]
> 解决了，是我boost库安装出错了，谢谢回复。
大神，怎么解决的，我也遇到这个问题，我的环境是：
cmake 2.8.12
gcc: 4.8.5
boost: 1.53.0

**Comment by sx-zhao** [comment]
> 解决了，是我boost库安装出错了，谢谢回复。

----------------------------------------------
请问你是怎么解决的？我也遇到了这个问题，我的环境是：
cmake 2.8.12
gcc: 4.8.5
boost: 1.53.0

**Comment by sx-zhao** [comment]
> > 解决了，是我boost库安装出错了，谢谢回复。
> 
> 请问你是怎么解决的？我也遇到了这个问题，我的环境是：
> cmake 2.8.12
> gcc: 4.8.5
> boost: 1.53.0


哦，原来是需要把其他高版本的boost卸载了才行。。。
