### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by LaVine-WU** [chenshuo/muduo#472]
在linux环境下执行./bash.sh命令编译，报错：
Cmake Error: The following variables are used in this project, but they are set to NOTFOUND, Please set them or make sure they are set and tested correctly in the CMake files: Boost_INCLUDE_DIR(ADVANCED)
请问有什么解决的方法？

**Comment by chenshuo** [comment]
Is this an issue of muduo? If so, please fill the template.

Specify the exact environment where the issue occurs:

* Linux distro and version? x86 or ARM? 32-bit or 64-bit?
* Branch (cpp98/cpp11/cpp17) and version of muduo?
* Version of cmake, gcc and boost? (If not from distro.)

**Comment by wo4chenkewen** [comment]
@LaVine-WU , you do not install c++ boost maybe.

**Comment by LaVine-WU** [comment]
> @ LaVine-WU，您可能未安装c ++ boost。



> 这是muduo问题吗？如果是这样，请填写模板。
> 
> 指定发生问题的确切环境：
> 
> * Linux发行版和版本？x86还是ARM？32位还是64位？
> * 分公司（cpp98 / cpp11 / cpp17）和版本的mudu吗？
> * cmake，gcc和boost版本？（如果不是来自发行版。）

thank you. I have solved this problem because the Boost library is not installed properly.

**Comment by LaVine-WU** [comment]
> @LaVine-WU , you do not install c++ boost maybe.

Yes, there was an error when installing the Boost library, and it has now been resolved. Thank you!
