### ISSUE TITLE
编译运行echo例子，报致命错误，““#include "examples/simple/echo/echo.h"没有那个文件或目录”

### ISSUE THREAD

**Issue by haoqipaopao** [chenshuo/muduo#473]
我使用如下两种方式编译运行echo的例子，都报致命错误。
1. 使用下列命令编译：
`g++ -o echo echo.cc -lmuduo_net -lmuduo_base -lpthread`

2. 尝试使用Makefile文件编译运行，也是同样的错误，Makefile的文件内容如下：
```
lib_path = -L/root/unix/build/release-install/lib/
header_path = -I/root/unix/build/release-install/include/
LIBS=-lmuduo_net -lmuduo_base -lpthread
CFLAGS=$(lib_path) $(header_path)
CC=g++
echo_server: main.o echo.o
	$(CC)  $(CFLAGS) -o echo_server main.o echo.o $(LIBS)

main.o:main.cc
	$(CC)  $(CFLAGS) -c main.cc

echo.o: echo.cc echo.h
	$(CC) $(CFLAGS) -c echo.cc
```
![2](https://user-images.githubusercontent.com/16208127/87285344-0025d880-c52a-11ea-942f-182477712dbc.png)

![1](https://user-images.githubusercontent.com/16208127/87279358-25aae600-c51a-11ea-98b1-7bd75901fa70.png)

**Comment by ForestEnchantress** [comment]
。。。

**Comment by haoqipaopao** [comment]
> 。。。

如果你知道是怎么做，可以给出解答吗？

**Comment by ForestEnchantress** [comment]
你看下在-I后目录下，以及系统默认头文件目录(/usr/include,/usr/local/include)下,是否存在你的#include ""中指示的文件

**Comment by haoqipaopao** [comment]
> 你看下在-I后目录下，以及系统默认头文件目录(/usr/include,/usr/local/include)下,是否存在你的#include ""中指示的文件

嗯嗯，就是目录写的不对了。谢谢你的解答，已解决。

**Comment by Yiwen233** [comment]
> > 你看下在-I后目录下，以及系统默认头文件目录(/usr/include,/usr/local/include)下,是否存在你的#include ""中指示的文件
> 
> 嗯嗯，就是目录写的不对了。谢谢你的解答，已解决。
> ![image](https://user-images.githubusercontent.com/16208127/88129662-3985d480-cc0b-11ea-9cb6-8b3cb350d6dc.png)

为什么我的还是没用阿。我的/usr/include 和 /usr/local/include 以及/usr/lib 都有相关文件，还是显示echo.h没有那个目录。
你说的那个Makefile文件是那个，我把能找的都找了，但是都没有找到设置lib_path head_path的makefile文件

**Comment by Yiwen233** [comment]
> > > 你看下在-I后目录下，以及系统默认头文件目录(/usr/include,/usr/local/include)下,是否存在你的#include ""中指示的文件
> > 
> > 
> > 嗯嗯，就是目录写的不对了。谢谢你的解答，已解决。
> > ![image](https://user-images.githubusercontent.com/16208127/88129662-3985d480-cc0b-11ea-9cb6-8b3cb350d6dc.png)
> 
> 为什么我的还是没用阿。我的/usr/include 和 /usr/local/include 以及/usr/lib 都有相关文件，还是显示echo.h没有那个目录。
> 你说的那个Makefile文件是那个，我把能找的都找了，但是都没有找到设置lib_path head_path的makefile文件

VS Code错误提示：
examples/simple/echo/echo.h: 没有那个文件或目录

**Comment by Yiwen233** [comment]
已解决！

**Comment by NJM97** [comment]
> 已解决！

方便请教一下是怎么解决的吗？遇到了同样的问题

**Comment by Yiwen233** [comment]
路径问题，换成相对路径或者绝对路径都行



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月30日(星期五) 晚上9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenshuo/muduo] 编译运行echo例子，报致命错误，““#include &quot;examples/simple/echo/echo.h&quot;没有那个文件或目录” (#473)





  
已解决！
  
方便请教一下是怎么解决的吗？遇到了同样的问题
