### ISSUE TITLE
安装muduo编译出错

### ISSUE THREAD

**Issue by caozuoba** [chenshuo/muduo#479]
[  1%] Built target atomic_unittest
[  6%] Built target muduo_base
[  7%] Built target threadpool_test
[  7%] Built target thread_test
[ 10%] Built target timestamp_unittest
[ 10%] Built target singleton_test
[ 11%] Built target threadlocalsingleton_test
[ 11%] Built target boundedblockingqueue_test
[ 12%] Built target processinfo_test
[ 12%] Built target asynclogging_test
[ 14%] Built target threadlocal_test
[ 14%] Built target blockingqueue_test
[ 14%] Built target timezone_unittest
[ 15%] Built target fileutil_test
[ 15%] Built target fork_test
[ 16%] Built target blockingqueue_bench
[ 16%] Built target singleton_threadlocal_test
[ 18%] Linking CXX executable ../../../bin/logstream_test
[ 19%] Built target exception_test
[ 20%] Built target gzipfile_test
[ 20%] Built target date_unittest
[ 20%] Built target logfile_test
[ 22%] Built target logging_test
Scanning dependencies of target thread_bench
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘bool boost::test_tools::tt_detail::check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(boost::test_tools::tt_detail::equal_impl_frwd, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) [clone .constprop.114]’中：
/usr/local/include/boost/test/utils/lazy_ostream.hpp:61：对‘boost::unit_test::lazy_ostream::inst’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘testLogStreamBooleans::test_method()’中：
/usr/local/include/boost/test/utils/lazy_ostream.hpp:61：对‘boost::unit_test::lazy_ostream::inst’未定义的引用
/usr/local/include/boost/test/utils/lazy_ostream.hpp:61：对‘boost::unit_test::lazy_ostream::inst’未定义的引用
/usr/local/include/boost/test/utils/lazy_ostream.hpp:61：对‘boost::unit_test::lazy_ostream::inst’未定义的引用
/usr/local/include/boost/test/utils/lazy_ostream.hpp:61：对‘boost::unit_test::lazy_ostream::inst’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o:/usr/local/include/boost/test/utils/lazy_ostream.hpp:61: 跟着更多未定义的参考到 boost::unit_test::lazy_ostream::inst
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘__static_initialization_and_destruction_0(int, int) [clone .constprop.113]’中：
/usr/local/include/boost/test/unit_test_log.hpp:227：对‘boost::unit_test::unit_test_log_t::instance()’未定义的引用
CMakeFiles/logstream_test.dir/LogStream_test.cc.o：在函数‘__static_initialization_and_destruction_0(int, int) [clone .constprop.113]’中：
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:13：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:13：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:26：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:26：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:43：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:43：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:113：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:113：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:172：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:172：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:186：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:186：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:199：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:199：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:217：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:217：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:237：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:237：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:263：对‘boost::unit_test::decorator::collector_t::instance()’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/LogStream_test.cc:263：对‘boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)’未定义的引用
collect2: error: ld returned 1 exit status
muduo/base/tests/CMakeFiles/logstream_test.dir/build.make:95: recipe for target 'bin/logstream_test' failed
make[2]: *** [bin/logstream_test] Error 1
CMakeFiles/Makefile2:745: recipe for target 'muduo/base/tests/CMakeFiles/logstream_test.dir/all' failed
make[1]: *** [muduo/base/tests/CMakeFiles/logstream_test.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 23%] Building CXX object muduo/base/tests/CMakeFiles/thread_bench.dir/Thread_bench.cc.o
[ 23%] Linking CXX executable ../../../bin/thread_bench
CMakeFiles/thread_bench.dir/Thread_bench.cc.o：在函数‘main’中：
/home/student/Downloads/muduo-master/muduo/base/tests/Thread_bench.cc:60：对‘muduo::Thread::Thread(std::function<void ()>, std::string const&)’未定义的引用
/home/student/Downloads/muduo-master/muduo/base/tests/Thread_bench.cc:72：对‘muduo::Thread::Thread(std::function<void ()>, std::string const&)’未定义的引用
collect2: error: ld returned 1 exit status
muduo/base/tests/CMakeFiles/thread_bench.dir/build.make:95: recipe for target 'bin/thread_bench' failed
make[2]: *** [bin/thread_bench] Error 1
CMakeFiles/Makefile2:1004: recipe for target 'muduo/base/tests/CMakeFiles/thread_bench.dir/all' failed
make[1]: *** [muduo/base/tests/CMakeFiles/thread_bench.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chenshuo** [comment]
请根据提问模板提供以下基本信息：

Specify the exact environment where the issue occurs:

* Linux distro and version? x86 or ARM? 32-bit or 64-bit?
* Branch (cpp98/cpp11/cpp17) and version of muduo?
* Version of cmake, gcc and boost? (If not from distro.)

**Comment by caozuoba** [comment]
> 请根据提问模板提供以下基本信息：
> 
> Specify the exact environment where the issue occurs:
> 
> * Linux distro and version? x86 or ARM? 32-bit or 64-bit?
> * Branch (cpp98/cpp11/cpp17) and version of muduo?
> * Version of cmake, gcc and boost? (If not from distro.)

Ubantu 18.04;x86_64
cpp11;the lastest version
cmake 3.3.2;boost1 .65

**Comment by chenshuo** [comment]
我在 Ubuntu 18.04 上使用 `sudo apt install g++ cmake libboost-dev libboost-test-dev` 安装之后，能正常编译 muduo cpp11。

**Comment by caozuoba** [comment]
> 我在 Ubuntu 18.04 上使用 `sudo apt install g++ cmake libboost-dev libboost-test-dev` 安装之后，能正常编译 muduo cpp11。

可能是我boost库连接的问题，我再尝试下，实在不行再来麻烦您
