### ISSUE TITLE
关于您书中二进制兼容的疑惑

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [chenshuo/muduo#483]
您好很高兴可以阅读到您的书籍，其中有一段我不是很懂

如果客户代码里有 Bar* pBar; pBar->memberA = xx;，那么肯定不安全，因为 memberA 的新 Bar 的偏移可能会变。相反，如果只通过成员函数来访问对象的数据成员，客户端不需要用到 data member 的 offsets，那么可能是安全的。

说实话我不是很懂陈硕说的这段demo的意思，class 一般定义在一个头文件中，.so库一般是实现，.h文件在预处理阶段就被编译到了二进制中，为什么成员变量
的偏移量会发生改变？除非去改.cc文件否则应该很难出现问题

**Comment by chenshuo** [comment]
version 1:

```c++
// Header
class Bar {
  void foo();
  int memberA;
};
```

你用这个头文件和 .so 库编译了你的程序，运行良好。

version 2, 修复了一些 bug，并增加了一个成员

```c++
// Header
class Bar {
  void foo();
  int id;
  int memberA;
};
```

如果你继续用旧的 .so，那当然什么事都不会发生。
但是你如果把 .so 库替换为新的版本，就会出现二进制兼容性的问题。

两种情况：
1. Bar 是 .so 创建的（Factory method），传给你一个指针，那么你的程序用旧的偏移去访问 memberA 会出错。
2. Bar 是你的程序创建（new）的，你调用位于 .so 中的成员函数 foo()，那么成员函数用新的偏移去访问 memberA 一样会出错。

**Comment by LeiZhang-Hunter** [comment]
非常感谢您的回复
