### ISSUE TITLE
《Linux多线程服务端编程》--第五章 高效的多线程日志的一点疑问

### ISSUE THREAD

**Issue by dongqh** [chenshuo/muduo#484]
您好：
“第五章 高效的多线程日志”的5.4小节(P120)，第一段最后是怎样做到节省一次内存拷贝的？

**Comment by giantchen** [comment]
这一段提到的常规做法是先写到 LogStream 的 Buffer 成员中（调用 Buffer::append() 拷贝到 Buffer::data_），然后调用 Buffer::toString() 从 Buffer::data_ 拷贝得到一个 std::string，再放到 BlockingQueue<std::string> 里，这里拷贝了两次数据。

书上提到减少一次拷贝的做法是 LogStream 直接使用 std::string::append()，这样就不用拷贝到 Buffer::data_ 再拷出来到 std::string。

**Comment by dongqh** [comment]
> 这一段提到的常规做法是先写到 LogStream 的 Buffer 成员中（调用 Buffer::append() 拷贝到 Buffer::data_），然后调用 Buffer::toString() 从 Buffer::data_ 拷贝得到一个 std::string，再放到 BlockingQueuestd::string 里，这里拷贝了两次数据。
> 
> 书上提到减少一次拷贝的做法是 LogStream 直接使用 std::string::append()，这样就不用拷贝到 Buffer::data_ 再拷出来到 std::string。

多谢了
