### ISSUE TITLE
/net/InetAddress.cc declaration error

### ISSUE THREAD

**Issue by jeffreycsj** [chenshuo/muduo#510]
port declaration error

**Comment by chenshuo** [comment]
?

**Comment by jeffreycsj** [comment]
您好，我在Linux centos编译时，遇到了port的定义错误，我改了参数名，编译通过了，所以发了一个这个东西

---Original---
From: "Shuo ***@***.***&gt;
Date: Fri, Apr 23, 2021 03:48 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chenshuo/muduo] /net/InetAddress.cc declaration error (#510)




 
?

**Comment by jeffreycsj** [comment]
可能是我的编译环境有问题，我在本地下是正确的，云服务器上编译有点问题，应该环境问题，晚上回去升级下



---Original---
From: "Shuo ***@***.***&gt;
Date: Fri, Apr 23, 2021 03:48 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chenshuo/muduo] /net/InetAddress.cc declaration error (#510)




 
?

**Comment by hallo128** [comment]
我也遇到了port的声明错误，目前也还不知道要怎么改
<img width="1020" alt="截屏2021-04-30 下午11 24 31" src="https://user-images.githubusercontent.com/19713203/116717206-3a099200-aa0b-11eb-8e5d-2bb9e95e39ec.png">

**Comment by zengpeng2018** [comment]
> 我也遇到了port的声明错误，目前也还不知道要怎么改
> <img alt="截屏2021-04-30 下午11 24 31" width="1020" src="https://user-images.githubusercontent.com/19713203/116717206-3a099200-aa0b-11eb-8e5d-2bb9e95e39ec.png">

直接拉master的代码编译同样遇到了这个问题。改用tag版本的代码编译通过

**Comment by chenshuo** [comment]
Should be fixed now in 9aaeda812.
