### ISSUE TITLE
在代码里没看到处理EINTR和EAGAIN的错误处理，不太了解这个机制，还有读返回0关闭客户端，小于0却不直接关闭，这个机制是什么样的？

### ISSUE THREAD

**Issue by yijuwang** [chenshuo/muduo#533]
GitHub issues are for tracking bugs, not for general discussing like a forum.

If you have a general question to ask, send it to mailing list:

muduo-library@googlegroups.com

Or visit:
https://groups.google.com/forum/#!forum/muduo-library

When file an issue muduo, please provide a [SSCCE](http://sscce.org):
Short, Self Contained, Correct (Compilable), Example.

If you can't compile muduo, make sure you install `cmake` and `boost` from the
official package repository, e.g. `apt` or `yum`, before opening a bug.
Don't open a bug if you installed boost from a third-party source or
downloaded it by yourself, and couldn't compile muduo, thank you.

Also specify the exact environment where the issue occurs:

**Comment by yijuwang** [comment]
另外也没有设置epoll ET,LT模式，两种处理应该有区别吧

**Comment by chenshuo** [comment]
GitHub Issues is not a forum.
