### ISSUE TITLE
Check return codes everywhere

### ISSUE THREAD

**Issue by elfring** [chenshuo/muduo#54]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [pthread_key_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_key_create.html "thread-specific data key creation") ⇒ [Deleter](https://github.com/chenshuo/muduo/blob/0b3f32254ed4fff61209be77fdd6a8cd42068281/muduo/base/ThreadLocalSingleton.h#L52 "constructor for Deleter")
- [fflush](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fflush.html "flush a stream") ⇒ [FileUtil::AppendFile::flush](https://github.com/chenshuo/muduo/blob/f692f760b26b4eec4db924ed2b2777d6ac369827/muduo/base/FileUtil.cc#L60)

Are any more improvements possible since [the previous request](https://github.com/chenshuo/muduo/issues/17 "Further considerations for error handling?")?

**Comment by chenshuo** [comment]
Close as work as intended.
