### ISSUE TITLE
muduo coredump

### ISSUE THREAD

**Issue by flowly** [chenshuo/muduo#60]
客户端模式下并发想Server发起请求的时候会coredump，具体信息见下面
#0  0x0000003a85e328a5 in raise () from /lib64/libc.so.6
#1  0x0000003a85e34085 in abort () from /lib64/libc.so.6
#2  0x0000003a85e2ba1e in __assert_fail_base () from /lib64/libc.so.6
#3  0x0000003a85e2bb40 in __assert_perror_fail () from /lib64/libc.so.6
#4  0x000000000041a871 in lock (this=0x65d6a0, conn=...) at /home/project/muduo/muduo/base/Mutex.h:81
#5  MutexLockGuard (this=0x65d6a0, conn=...) at /home/project/muduo/muduo/base/Mutex.h:143
#6  muduo::net::TcpClient::removeConnection (this=0x65d6a0, conn=...) at /home/project/muduo/muduo/net/TcpClient.cc:170
#7  0x000000000041fc89 in operator() (this=0x2b2f540047c0) at /usr/include/boost/function/function_template.hpp:1013
#8  muduo::net::TcpConnection::handleClose (this=0x2b2f540047c0) at /home/project/muduo/muduo/net/TcpConnection.cc:372
#9  0x000000000041ffb8 in muduo::net::TcpConnection::handleRead (this=0x2b2f540047c0, receiveTime=...) at /home/project/muduo/muduo/net/TcpConnection.cc:310
#10 0x00000000004280f9 in operator() (this=0x2b2f54004970, receiveTime=<value optimized out>) at /usr/include/boost/function/function_template.hpp:1013
#11 muduo::net::Channel::handleEventWithGuard (this=0x2b2f54004970, receiveTime=<value optimized out>) at /home/project/muduo/muduo/net/Channel.cc:107
#12 0x0000000000428479 in muduo::net::Channel::handleEvent (this=0x2b2f54004970, receiveTime=<value optimized out>) at /home/project/muduo/muduo/net/Channel.cc:79
#13 0x00000000004146b5 in muduo::net::EventLoop::loop (this=0x2b2f4c3f09d0) at /home/project/muduo/muduo/net/EventLoop.cc:125
#14 0x000000000042b503 in muduo::net::EventLoopThread::threadFunc (this=0x648ff0) at /home/project/muduo/muduo/net/EventLoopThread.cc:72
#15 0x000000000042ff41 in operator() (this=0x649130) at /usr/include/boost/function/function_template.hpp:1013
#16 muduo::detail::ThreadData::runInThread (this=0x649130) at /home/project/muduo/muduo/base/Thread.cc:94
#17 0x000000000042fd4e in muduo::detail::startThread (obj=<value optimized out>) at /home/project/muduo/muduo/base/Thread.cc:124
#18 0x0000003a86207851 in start_thread () from /lib64/libpthread.so.0
#19 0x0000003a85ee767d in clone () from /lib64/libc.so.6

**Comment by chenzhuoli** [comment]
求TcpClient提前析构导致core dump的解决办法
